apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-tls
  namespace: redis
spec:
  secretName: redis-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - redis.alexbartleynees.com
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  secretTemplate:
    annotations:
      cert-manager.io/allow-direct-injection: "true"
  # Request CA certificate to be included in the secret
  keystores:
    pkcs12:
      create: false
