apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: definition
  namespace: rabbitmq-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  persistence:
    storage: 20Gi
    storageClassName: "openebs-hostpath"
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  service:
    type: ClusterIP
  rabbitmq:
    additionalConfig: |
      load_definitions = /etc/rabbitmq/definitions.json
  override:
    statefulSet:
      spec:
        template:
          spec:
            volumes:
              - name: definitions
                configMap:
                  name: rabbitmq-definitions
            containers:
              - name: rabbitmq
                volumeMounts:
                  - name: definitions
                    mountPath: /etc/rabbitmq/definitions.json
                    subPath: definitions.json
