apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: definition
  namespace: rabbitmq-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 3
  persistence:
    storage: 20Gi
    storageClassName: ""
  resources:
    requests:
      cpu: 1500m
      memory: 3Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  service:
    type: ClusterIP
