# Reduce Prometheus storage from 50Gi to 5Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 5Gi
---
# Reduce Grafana storage from 10Gi to 2Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 2Gi
---
# Reduce Alertmanager storage from 10Gi to 1Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager-db-alertmanager-kube-prometheus-stack-alertmanager-0
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 1Gi
---
# Reduce Redis master storage from 8Gi to 1Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-master-0
  namespace: redis
spec:
  resources:
    requests:
      storage: 1Gi
---
# Reduce Redis replica storage from 8Gi to 1Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-replicas-0
  namespace: redis
spec:
  resources:
    requests:
      storage: 1Gi
---
# Reduce Loki storage from 10Gi to 2Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-loki-0
  namespace: observability
spec:
  resources:
    requests:
      storage: 2Gi
