apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    chart: openebs
    repoURL: https://openebs.github.io/openebs
    targetRevision: 4.3.3
    helm:
      values: |
        # Disable pre-upgrade hook to avoid Job validation errors
        hooks:
          preUpgrade:
            enabled: false

        openebsNDM:
          enabled: false
        webhook:
          enabled: false
        engines:
          replicated:
            mayastor:
              enabled: false

        # Disable observability components (Loki)
        observability:
          enabled: false
        loki:
          enabled: false

        localpv-provisioner:
          enabled: true
          openebsNDM:
            enabled: false
          hostpathClass:
            enabled: true
            name: "openebs-hostpath"
            isDefaultClass: true
            reclaimPolicy: "Delete"
            volumeBindingMode: "WaitForFirstConsumer"
            basePath: "/var/openebs/local"
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
