apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-tls
  namespace: redis
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: redis-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - redis.alexbartleynees.com
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
