apiVersion: v1
kind: Namespace
metadata:
  name: photos
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ingress
  namespace: photos
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - photos.alexbartleynees.com
      secretName: photos-tls
  rules:
    - host: photos.alexbartleynees.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: immich-service
  namespace: photos
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: immich-service
  namespace: photos
  labels:
    kubernetes.io/service-name: immich-service
addressType: IPv4
ports:
  - name: http
    port: 80
    protocol: TCP
endpoints:
  - addresses:
      - "100.92.229.107"
    conditions: {}
