apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-feedback-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/alex-bartleynees/product-feedback-app-v2.git
      path: deployment/helm-charts/product-feedback-app
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
    - repoURL: registry-1.docker.io/creativefree
      targetRevision: 0.4.0
      chart: my-ingress-chart
      helm:
        valueFiles:
          - $values/components/ingress/product-feedback-app-ingress-values.yaml
    - repoURL: "https://github.com/alex-bartleynees/portfolio-cluster.git"
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: product-feedback
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
