apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: database
spec:
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: creativefree/postgresql-backup-s3
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DATABASE
              value: all
            - name: POSTGRES_HOST
              value: "postgres-db.database.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-credentials
                  key: POSTGRES_USER
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-credentials
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-credentials
                  key: S3_SECRET_ACCESS_KEY
            - name: S3_BUCKET
              value: "postgres-portfolio-backup"
            - name: S3_ENDPOINT
              value: "https://s3.us-east-2.amazonaws.com"
            - name: S3_PREFIX
              value: "postgres-backups"
            - name: SCHEDULE
              value: "0 0 * * *"
            - name: DELETE_OLDER_THAN
              value: "7 days ago"
