apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-proxy
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin-proxy
  template:
    metadata:
      labels:
        app: jellyfin-proxy
      annotations:
        tailscale.com/proxy-class: default
    spec:
      serviceAccountName: proxies
      containers:
      - name: jellyfin-proxy
        image: nginx:alpine
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: jellyfin-proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyfin-proxy-config
  namespace: tailscale
data:
  default.conf: |
    server {
        listen 8096;
        location / {
            proxy_pass http://100.98.211.116:8096;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-proxy-service
  namespace: tailscale
spec:
  selector:
    app: jellyfin-proxy
  ports:
  - port: 8096
    targetPort: 8096

