apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: "*"
    helm:
      values: |
        oauth: {}
        oauthSecretVolume:
          secret:
            secretName: tailscale-oauth
            items:
            - key: CLIENT_ID
              path: client_id
            - key: CLIENT_SECRET
              path: client_secret
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

