---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-badger-data
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: "Prune=false"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath
