apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: default
  source:
    chart: jaeger
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 3.4.0
    helm:
      values: |
        provisionDataStore:
          cassandra: false
          badger:
            enabled: true
            persistence:
              enabled: true
              storageClassName: openebs-hostpath
              accessModes:
                - ReadWriteOnce
              size: 10Gi
        storage:
          type: badger
          options:
            badger:
              directory-key: /badger/key
              directory-value: /badger/data
        allInOne:
          enabled: true  
          args:
            - --badger.ephemeral=false
            - --badger.directory-key=/badger/key
            - --badger.directory-value=/badger/data
          storage:
            type: badger
          persistence:
            enabled: true
            storageClass: openebs-hostpath
            size: 10Gi
            accessModes:
              - ReadWriteOnce
          securityContext:
            fsGroup: 1000
            runAsUser: 1000
            runAsGroup: 1000
          service:
            type: ClusterIP
            ports:
              - name: grpc
                port: 14250
                protocol: TCP
                targetPort: 14250
              - name: binary
                port: 6832
                protocol: UDP
                targetPort: 6832
              - name: http
                port: 14268
                protocol: TCP
                targetPort: 14268
              - name: zipkin
                port: 9411
                protocol: TCP
                targetPort: 9411
              - name: otlp
                port: 4317
                protocol: TCP
                targetPort: 4317
              - name: otlp-http
                port: 4318
                protocol: TCP
                targetPort: 4318
        agent:
          enabled: false
        collector:
          enabled: false
        query:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
