apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.25.0
    helm:
      values: |
        loki:
          auth_enabled: false
          common_config:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: 2022-06-01
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          singleBinary:
            enabled: true
            replicas: 2
            persistence:
              enabled: true
              size: 10Gi
              storageClass: openebs-hostpath
          storage:
            type: filesystem
          storageConfig:
            filesystem:
              directory: /data/loki/chunks
        deploymentMode: SingleBinary
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        ingester:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        distributor:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0
        query_schedule:
          max_outstanding_requests_per_tenant: 2048

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
