apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  addresses:
    - 51.161.130.194/32
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-l2
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ipAddressPools:
    - homelab-pool
