apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-journal-api
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/alex-bartleynees/coffee-journal-api.git
      path: deployment/helm-charts/coffee-journal-api
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: coffee-journal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
