apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-photos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alex-bartleynees/portfolio-cluster.git
    targetRevision: metallb
    path: components/applications/external-services/immich
  destination:
    server: https://kubernetes.default.svc
    namespace: photos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
