apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alex-bartleynees/portfolio-cluster.git
    targetRevision: HEAD
    path: components/applications/external-services/jellyseer
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyseer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
