apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-livesync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alex-bartleynees/portfolio-cluster.git
    targetRevision: metallb
    path: components/obsidian-livesync
  destination:
    server: https://kubernetes.default.svc
    namespace: obsidian
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
