apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/alex-bartleynees/portfolio-cluster.git
    targetRevision: metallb
    path: components/applications/workloads/redis-proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
