apiVersion: v1
kind: Namespace
metadata:
  name: office
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: office-ingress
  namespace: office
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - oods.alexbartleynees.com
      secretName: office-tls
  rules:
    - host: oods.alexbartleynees.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: office-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: office-service
  namespace: office
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: office-service
  namespace: office
  labels:
    kubernetes.io/service-name: office-service
addressType: IPv4
ports:
  - name: http
    port: 80
    protocol: TCP
endpoints:
  - addresses:
      - "100.98.211.116"
    conditions: {}
