apiVersion: v1
kind: Namespace
metadata:
  name: files
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: files-ingress
  namespace: files
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.alexbartleynees.com
      secretName: files-tls
  rules:
    - host: files.alexbartleynees.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: files-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: files-service
  namespace: files
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: files-service
  namespace: files
  labels:
    kubernetes.io/service-name: files-service
addressType: IPv4
ports:
  - name: http
    port: 80
    protocol: TCP
endpoints:
  - addresses:
      - "100.98.211.116"
    conditions: {}
