apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.1.1
    helm:
      values: |
        server:
          config:
            url: https://argo-cd.alexbartleynees.com
            params:
              server.insecure: true
        configs:
          params:
            enableOCI: true
          cm:
            kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
        repoServer:
          env:
            - name: HELM_ENABLE_OIDC
              value: "true"
            - name: XDG_CONFIG_HOME
              value: /.config
            - name: SOPS_AGE_KEY_FILE
              value: /.config/sops/age/keys.txt
          volumes:
            - name: custom-tools
              emptyDir: {}
            - name: sops-age
              secret:
                secretName: sops-age
          initContainers:
            - name: install-ksops
              image: viaductoss/ksops:v4.3.2
              command: ["/bin/sh", "-c"]
              args:
                - |
                  echo "Installing KSOPS..."
                  mv ksops /custom-tools/;
                  mv kustomize /custom-tools/;
                  echo "Done.";
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools
          volumeMounts:
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
            - mountPath: /usr/local/bin/ksops
              name: custom-tools
              subPath: ksops
            - mountPath: /.config/sops/age/keys.txt
              name: sops-age
              subPath: keys.txt
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-server-network-policy
  namespace: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - argo-cd.alexbartleynees.com
      secretName: website-tls
  rules:
    - host: argo-cd.alexbartleynees.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
