apiVersion: v1
kind: Secret
metadata:
  name: sqlconnectionstring
  namespace: product-feedback
  annotations:
    enc.suffix: encrypted
type: Opaque
stringData:
  SQL_CONNECTION_STRING: ENC[AES256_GCM,data:y4RgJSF5UUlUlT56rKAuNN+EgEdOpfkDY6DxJPqxs3447/zTvxrn6ir5AoBeKejQNbPS4iVh3MBJ3CROFIS5TkO7wMb64VtNkQmmLFHbh+uFti5o8BqZaEg=,iv:PAODkW1LVsOEN54U+nOs0fSXBCjA0qVCAb7euD79Hdg=,tag:cVIF3yS+zMy1ElCI6fmC3Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-01-27T18:29:13Z"
  mac: ENC[AES256_GCM,data:93g3ibRaxUW/QREuroVgOdqIlcZ0IfI7SVGhetljTi1gkXeSLZ8NkzeZmAnxfDuGUk7yYcJXeICqrTz5wNeEiNOJmNLw8Wf3ExkKQcbuKP8sMuRVt0H5iJPE3SenPQKHZdbLTjonSuKgXmfL6oHLvNc31s8YeDmSLz1O2q18FaE=,iv:eHlJBFwUryRTRUkKczh7xOxU2YT9O2wd8MfyKqxh2HQ=,tag:dRNzrJAgU8i5wVXukqlpkA==,type:str]
  pgp:
    - created_at: "2025-01-27T18:29:13Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA5oXQ7yzM65bAQ/+JrMadF8jzGuV/0ZudZSXbOtDpkaIqHR+TW0Q/ZgNBC5P
        CPdG3UnJS5oUKwZqWxus8Wjg8y6gBhI4BK1NfGfygFYQqkqsH1kaEjvYyhGwWP/8
        9LJJ800NJIwi+DOXPypI29hfeYH7Wctqy+D8Wv4QYyqeDWWXb0i5kbQRiRqUhi3E
        YmcQn+GX7U5UyWXH+//44Ybh1SrPw0ErXTvRStRlNQlIONN0LuXSKSw3MFP4TNpV
        VoeApAVf4/p5LLJio9j9F6ZRlCr4Wm6spqYnq3V7FDxwfLB21l8zLggn2Quj/NbK
        PzYUEAxllidlzWMedwrOehR0jR/4/hKlA70m7tfIjU8j4Pa17WXSUtzqlP3nspOM
        n3vKpHDbyy9pCkcGRLo4elvL7vZ8MaC041qdGnooDQPscJ9r+53z9aAJaxsVxpTb
        peeKO/CBYQ0OAt3QCTC0VeWPdj2iVujK//UuASv729lVa11N6Ek4gibfLMLhL8qh
        5sFIda07bgymtsk1Pk7X83n0nE8r+LRbAjQ3r/D74W0zB7uMpQzzCawELIQ/GzRV
        85n9pq/nkAJ0xFd9r0Gr73FJ6jqtfy83jm+8bQQ0hFhwPQL0cuJgc63cZOtKh4dR
        F01BhFNgObm4b6xbSRdTDxZ+vq0J8LVZOfzO7nDUmyPq4V4Y2S4VjVMikHJYz4PU
        aAEJAhBBGrV01ZySGKeQCFzfNcKL/sWG1B2WJNncn8B884DE8mL0EOPprXHAsCC3
        8XXGKlocYnSgLQ8rBhdoZwGhktcnzdzHi2+UvRnEUOQqY7dGG+p3LboKGC/EHCao
        mutAitk4SkpZ
        =6loo
        -----END PGP MESSAGE-----
      fp: 1049D3246DF059C2C8F54D289A1743BCB333AE5B
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
