apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:Rigj5N87+HliVf+NwcDuSOCzYUBjAVDsajnQDpOQYosSAbsXe6OzXElXT7T+6Mvr0GdiV7aXv4n5Iijacgygtaa13sk81u6x5j9lcFiwsHagLmJMDU43GA==,iv:hl/akNq1K+Luoo5O2X2z4n3h73Kc72QmpknV7x3pV4o=,tag:6f2rJ8zvy9tGdoQmq1ClOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNG1BbGNwZUdUNitkdXY0
            Q3Z6WGVJV3p1VHVuVzgyaVJQbk05M0s3S0dzCi9kc0xxMFQrN2xjL3FoMDZ3MnFK
            aEJsU3d6M1lacDR6TjhFZ09yQnMrd2cKLS0tIEVKSDZWMFdZcmdrSFJDSkZvb3ZE
            ZXdFb3V2NDlZYnJpMFhnd0FYSDIwenMKUgUeQF48NPMUlZH1yZ0dpWkCNzuCs4hA
            M5dKQYqQru7cFCe1A3rk6SrxbGBW5Ep08DbPMPpU54p2c9ZEpPOtLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T22:55:19Z"
    mac: ENC[AES256_GCM,data:6iq0/fGNPvT503HVXcJj/9SMT+5jiEQFSpf8bCSE+BlpKknE8nwS2KUZz+7C94iWMkbAdzRM62O0QGsDh9mJBvdHZkPhSwYZ0q3ddov5De/nE6QK8Q5RubDJ1de0/blZ4WFxqVbXsLHIzSXHdjVgrYvj/VYkPSH86YyHGtE9jVk=,iv:0C3FnSl2zGdDWGVqnbXhu0Sx0b4WWUBZ5usNk/tQWaQ=,tag:lkU+V51pvIDobeeI6omBIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: keycloak
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Y6OpVzqm1zhvAUU=,iv:tmwKdjh8Y/GYC0itMyjnjQiES6OJe8567PdQRv/3wMg=,tag:ZtZO7nL2pHRm7MmrHPeXgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNG1BbGNwZUdUNitkdXY0
            Q3Z6WGVJV3p1VHVuVzgyaVJQbk05M0s3S0dzCi9kc0xxMFQrN2xjL3FoMDZ3MnFK
            aEJsU3d6M1lacDR6TjhFZ09yQnMrd2cKLS0tIEVKSDZWMFdZcmdrSFJDSkZvb3ZE
            ZXdFb3V2NDlZYnJpMFhnd0FYSDIwenMKUgUeQF48NPMUlZH1yZ0dpWkCNzuCs4hA
            M5dKQYqQru7cFCe1A3rk6SrxbGBW5Ep08DbPMPpU54p2c9ZEpPOtLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T22:55:19Z"
    mac: ENC[AES256_GCM,data:6iq0/fGNPvT503HVXcJj/9SMT+5jiEQFSpf8bCSE+BlpKknE8nwS2KUZz+7C94iWMkbAdzRM62O0QGsDh9mJBvdHZkPhSwYZ0q3ddov5De/nE6QK8Q5RubDJ1de0/blZ4WFxqVbXsLHIzSXHdjVgrYvj/VYkPSH86YyHGtE9jVk=,iv:0C3FnSl2zGdDWGVqnbXhu0Sx0b4WWUBZ5usNk/tQWaQ=,tag:lkU+V51pvIDobeeI6omBIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:THcLktallsc=,iv:LjyqLlP7OaO/KLarA2v4aFhjPonPB7LI0i5naL3aErc=,tag:h1Zfs20xv3VW4xf6U4hL3A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tnl8RUnn/hFrXyc=,iv:gXThys04ZOeYoSJjTSQmbngHwI/WyL3sDNZdLmAaFCw=,tag:5UB/EXsFeQZsZV3YgJwrmg==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:cTGM+OS2kyEuE09VMNAwZuFD9sY=,iv:owDNWd4ouAGweNYnCUQ6tgd0/oMvr9wsZmVi7Kt4/ig=,tag:80sJgNNZI3owT2OJQ4U0Cw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:o7Tgmyt40X0FVHlYzrHb7FIBzB8mynajunPWp2c+D1GqlTloP193AA==,iv:vGlx8KpYjSFOI7W7iupZ7FW0G4nM56KaIMGVnUEoCuk=,tag:xM8ObcVMKUGPIKk8avOGGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNG1BbGNwZUdUNitkdXY0
            Q3Z6WGVJV3p1VHVuVzgyaVJQbk05M0s3S0dzCi9kc0xxMFQrN2xjL3FoMDZ3MnFK
            aEJsU3d6M1lacDR6TjhFZ09yQnMrd2cKLS0tIEVKSDZWMFdZcmdrSFJDSkZvb3ZE
            ZXdFb3V2NDlZYnJpMFhnd0FYSDIwenMKUgUeQF48NPMUlZH1yZ0dpWkCNzuCs4hA
            M5dKQYqQru7cFCe1A3rk6SrxbGBW5Ep08DbPMPpU54p2c9ZEpPOtLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T22:55:19Z"
    mac: ENC[AES256_GCM,data:6iq0/fGNPvT503HVXcJj/9SMT+5jiEQFSpf8bCSE+BlpKknE8nwS2KUZz+7C94iWMkbAdzRM62O0QGsDh9mJBvdHZkPhSwYZ0q3ddov5De/nE6QK8Q5RubDJ1de0/blZ4WFxqVbXsLHIzSXHdjVgrYvj/VYkPSH86YyHGtE9jVk=,iv:0C3FnSl2zGdDWGVqnbXhu0Sx0b4WWUBZ5usNk/tQWaQ=,tag:lkU+V51pvIDobeeI6omBIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:PhIzG4Qc,iv:g6SaZ01e/jux1lPfdXI6UBgh1W+/IcWrQPEgB0ix1hQ=,tag:dCkZx3a7AOtaADR1/aZUyQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:feNxk/83bPXZhbw=,iv:qpAvzW2H3eIyvPRq/ywqMFTJ/LHw4yzVGKz2IIK/l6k=,tag:Mc2uZk9jWHxGx58D1prJSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNG1BbGNwZUdUNitkdXY0
            Q3Z6WGVJV3p1VHVuVzgyaVJQbk05M0s3S0dzCi9kc0xxMFQrN2xjL3FoMDZ3MnFK
            aEJsU3d6M1lacDR6TjhFZ09yQnMrd2cKLS0tIEVKSDZWMFdZcmdrSFJDSkZvb3ZE
            ZXdFb3V2NDlZYnJpMFhnd0FYSDIwenMKUgUeQF48NPMUlZH1yZ0dpWkCNzuCs4hA
            M5dKQYqQru7cFCe1A3rk6SrxbGBW5Ep08DbPMPpU54p2c9ZEpPOtLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T22:55:19Z"
    mac: ENC[AES256_GCM,data:6iq0/fGNPvT503HVXcJj/9SMT+5jiEQFSpf8bCSE+BlpKknE8nwS2KUZz+7C94iWMkbAdzRM62O0QGsDh9mJBvdHZkPhSwYZ0q3ddov5De/nE6QK8Q5RubDJ1de0/blZ4WFxqVbXsLHIzSXHdjVgrYvj/VYkPSH86YyHGtE9jVk=,iv:0C3FnSl2zGdDWGVqnbXhu0Sx0b4WWUBZ5usNk/tQWaQ=,tag:lkU+V51pvIDobeeI6omBIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:5Ji5aF3rhmg=,iv:xd8PpkwbxgXywzfEvjAJ1HXtcjggUGx3u4GlpW8THXw=,tag:sLXKjXSgjywrGfWUy3M3zQ==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:jGNSQc90726wNXs=,iv:EyMq+O0xNOt6G7Jfh2enZ5ADexmyOuS5wnB2d2e/8gU=,tag:SivVEM8DTtMiNgoJzlJhGw==,type:str]
    PASSPHRASE: ENC[AES256_GCM,data:AEK6cK5YzagBIXL+HUsM4OQD4kk4VNisyzTbKyPFtyJ/UQ==,iv:TyclQVw4gqO9WrNJABrDV+H6373eBpua0xZUFWPI0AU=,tag:7uNI/boi3YloR/v08UZ0pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNG1BbGNwZUdUNitkdXY0
            Q3Z6WGVJV3p1VHVuVzgyaVJQbk05M0s3S0dzCi9kc0xxMFQrN2xjL3FoMDZ3MnFK
            aEJsU3d6M1lacDR6TjhFZ09yQnMrd2cKLS0tIEVKSDZWMFdZcmdrSFJDSkZvb3ZE
            ZXdFb3V2NDlZYnJpMFhnd0FYSDIwenMKUgUeQF48NPMUlZH1yZ0dpWkCNzuCs4hA
            M5dKQYqQru7cFCe1A3rk6SrxbGBW5Ep08DbPMPpU54p2c9ZEpPOtLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T22:55:19Z"
    mac: ENC[AES256_GCM,data:6iq0/fGNPvT503HVXcJj/9SMT+5jiEQFSpf8bCSE+BlpKknE8nwS2KUZz+7C94iWMkbAdzRM62O0QGsDh9mJBvdHZkPhSwYZ0q3ddov5De/nE6QK8Q5RubDJ1de0/blZ4WFxqVbXsLHIzSXHdjVgrYvj/VYkPSH86YyHGtE9jVk=,iv:0C3FnSl2zGdDWGVqnbXhu0Sx0b4WWUBZ5usNk/tQWaQ=,tag:lkU+V51pvIDobeeI6omBIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: product-feedback
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:O+MTYNHHi7bAEeFA,iv:J2PYULdC4Wzub6wwiWFqdlWzAZJRqkLDUcjd8Gf7veI=,tag:lY69X7tXS/H11oJQlQopmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNG1BbGNwZUdUNitkdXY0
            Q3Z6WGVJV3p1VHVuVzgyaVJQbk05M0s3S0dzCi9kc0xxMFQrN2xjL3FoMDZ3MnFK
            aEJsU3d6M1lacDR6TjhFZ09yQnMrd2cKLS0tIEVKSDZWMFdZcmdrSFJDSkZvb3ZE
            ZXdFb3V2NDlZYnJpMFhnd0FYSDIwenMKUgUeQF48NPMUlZH1yZ0dpWkCNzuCs4hA
            M5dKQYqQru7cFCe1A3rk6SrxbGBW5Ep08DbPMPpU54p2c9ZEpPOtLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T22:55:19Z"
    mac: ENC[AES256_GCM,data:6iq0/fGNPvT503HVXcJj/9SMT+5jiEQFSpf8bCSE+BlpKknE8nwS2KUZz+7C94iWMkbAdzRM62O0QGsDh9mJBvdHZkPhSwYZ0q3ddov5De/nE6QK8Q5RubDJ1de0/blZ4WFxqVbXsLHIzSXHdjVgrYvj/VYkPSH86YyHGtE9jVk=,iv:0C3FnSl2zGdDWGVqnbXhu0Sx0b4WWUBZ5usNk/tQWaQ=,tag:lkU+V51pvIDobeeI6omBIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_DB_USERNAME: ENC[AES256_GCM,data:+MGGUV+yV/s=,iv:whDA1hGTLAML4Ttxa4lFFP6ecWksQJqnEpJhHT9Unfk=,tag:Ue4OF2PSxdd68EpkNx/b5g==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:MLBLLQmhB21uj5I0TFi+67tCo9o=,iv:ZIuinPHlYnOyxKGE8pBPAyZOHK5i/Dd8B1rOb7yuRIQ=,tag:4OH95TnG1HoN0rbS6fRGFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNG1BbGNwZUdUNitkdXY0
            Q3Z6WGVJV3p1VHVuVzgyaVJQbk05M0s3S0dzCi9kc0xxMFQrN2xjL3FoMDZ3MnFK
            aEJsU3d6M1lacDR6TjhFZ09yQnMrd2cKLS0tIEVKSDZWMFdZcmdrSFJDSkZvb3ZE
            ZXdFb3V2NDlZYnJpMFhnd0FYSDIwenMKUgUeQF48NPMUlZH1yZ0dpWkCNzuCs4hA
            M5dKQYqQru7cFCe1A3rk6SrxbGBW5Ep08DbPMPpU54p2c9ZEpPOtLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T22:55:19Z"
    mac: ENC[AES256_GCM,data:6iq0/fGNPvT503HVXcJj/9SMT+5jiEQFSpf8bCSE+BlpKknE8nwS2KUZz+7C94iWMkbAdzRM62O0QGsDh9mJBvdHZkPhSwYZ0q3ddov5De/nE6QK8Q5RubDJ1de0/blZ4WFxqVbXsLHIzSXHdjVgrYvj/VYkPSH86YyHGtE9jVk=,iv:0C3FnSl2zGdDWGVqnbXhu0Sx0b4WWUBZ5usNk/tQWaQ=,tag:lkU+V51pvIDobeeI6omBIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:yoPVQuA=,iv:RUcLMqPy/XlCDJ9Ig30TLX+/Z3QrAO9Z47oYct9VnhI=,tag:WtQMmv6aLAHuvmbNi8nQOQ==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:NmJNz2UHu+6aGpPXCFZLD9KXK3Q=,iv:llKCDLaSM0/yI24KXyLeN8ueJLY+goFrLaxHjHg8CIQ=,tag:mqVg/7zkIv3qf4HMjzUkoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNG1BbGNwZUdUNitkdXY0
            Q3Z6WGVJV3p1VHVuVzgyaVJQbk05M0s3S0dzCi9kc0xxMFQrN2xjL3FoMDZ3MnFK
            aEJsU3d6M1lacDR6TjhFZ09yQnMrd2cKLS0tIEVKSDZWMFdZcmdrSFJDSkZvb3ZE
            ZXdFb3V2NDlZYnJpMFhnd0FYSDIwenMKUgUeQF48NPMUlZH1yZ0dpWkCNzuCs4hA
            M5dKQYqQru7cFCe1A3rk6SrxbGBW5Ep08DbPMPpU54p2c9ZEpPOtLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T22:55:19Z"
    mac: ENC[AES256_GCM,data:6iq0/fGNPvT503HVXcJj/9SMT+5jiEQFSpf8bCSE+BlpKknE8nwS2KUZz+7C94iWMkbAdzRM62O0QGsDh9mJBvdHZkPhSwYZ0q3ddov5De/nE6QK8Q5RubDJ1de0/blZ4WFxqVbXsLHIzSXHdjVgrYvj/VYkPSH86YyHGtE9jVk=,iv:0C3FnSl2zGdDWGVqnbXhu0Sx0b4WWUBZ5usNk/tQWaQ=,tag:lkU+V51pvIDobeeI6omBIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: seaweedfs
type: Opaque
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:wcVrz78MKn3e++PbKAd7BDWellY+2kdI6xlFQTCKPORAKytHlJhhjFOjgU1WdQivkqAuzN7+Gk+Kexc4TzOibI4Jv4phv9vMFCW6W3CqNgfnOc0CMNAcbQg1LRSM9nqEzRwS7J3NoBpeaWwnmN1/+5psXjQ2IMnZfiAa+IxXUE9BTgBZ6UM4gZ9ugGbUdqXHRL3wDDUGzd+MtRMgNyzVKKiuBilTpsGw+Aqx+7Nz7hfmhMS5BBQS+pOvLDQSgrK0BkDy+1xGu4dwF4qxEcOicqBenotR7Nriuv/BDHduBBpKkRi78HZCEmb3fOPfeCW0sz3SXk/INTffb521yEqjvTHynC996n+Q1oMJT3oK8jtx/NBKtil+X+luapd8HG/7JBbssL+46R4D0gZ3EoNdluwBC2MYzsVMm3to8QRhWK9IUNy1RPNhX7Q6adbUh1fMxQ==,iv:XsVYrauZ2zY+OA7/V/ahbrwmhnpCoSxybQeDgLdcjC8=,tag:QoAS4DK0ClTIthJsIQEJtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNG1BbGNwZUdUNitkdXY0
            Q3Z6WGVJV3p1VHVuVzgyaVJQbk05M0s3S0dzCi9kc0xxMFQrN2xjL3FoMDZ3MnFK
            aEJsU3d6M1lacDR6TjhFZ09yQnMrd2cKLS0tIEVKSDZWMFdZcmdrSFJDSkZvb3ZE
            ZXdFb3V2NDlZYnJpMFhnd0FYSDIwenMKUgUeQF48NPMUlZH1yZ0dpWkCNzuCs4hA
            M5dKQYqQru7cFCe1A3rk6SrxbGBW5Ep08DbPMPpU54p2c9ZEpPOtLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T22:55:19Z"
    mac: ENC[AES256_GCM,data:6iq0/fGNPvT503HVXcJj/9SMT+5jiEQFSpf8bCSE+BlpKknE8nwS2KUZz+7C94iWMkbAdzRM62O0QGsDh9mJBvdHZkPhSwYZ0q3ddov5De/nE6QK8Q5RubDJ1de0/blZ4WFxqVbXsLHIzSXHdjVgrYvj/VYkPSH86YyHGtE9jVk=,iv:0C3FnSl2zGdDWGVqnbXhu0Sx0b4WWUBZ5usNk/tQWaQ=,tag:lkU+V51pvIDobeeI6omBIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-auth
    namespace: product-feedback
type: Opaque
stringData:
    CLIENT_SECRET: ENC[AES256_GCM,data:Vgq6Y6b7ws0rFY3oP+YKlDjbIQPP3QVZtYf16oDuZww=,iv:KVq52BKESNe2LQ+bXFIYg7kQ6/a6U+PbqG0oZtSiR2U=,tag:8juubdcPiJevi8Fo48ZGTw==,type:str]
    ADMIN_CLIENT_SECRET: ENC[AES256_GCM,data:H2Uxso5XorIN8hYOcxZLkIBWvShqhbYP1AIe0ix43zY=,iv:hOfLFKC6UCuwP2b6odEbTDcR+NNjVR4KNB542vuFjdI=,tag:/K5zzo+BWqvNuP5v0bSrRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNG1BbGNwZUdUNitkdXY0
            Q3Z6WGVJV3p1VHVuVzgyaVJQbk05M0s3S0dzCi9kc0xxMFQrN2xjL3FoMDZ3MnFK
            aEJsU3d6M1lacDR6TjhFZ09yQnMrd2cKLS0tIEVKSDZWMFdZcmdrSFJDSkZvb3ZE
            ZXdFb3V2NDlZYnJpMFhnd0FYSDIwenMKUgUeQF48NPMUlZH1yZ0dpWkCNzuCs4hA
            M5dKQYqQru7cFCe1A3rk6SrxbGBW5Ep08DbPMPpU54p2c9ZEpPOtLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T22:55:19Z"
    mac: ENC[AES256_GCM,data:6iq0/fGNPvT503HVXcJj/9SMT+5jiEQFSpf8bCSE+BlpKknE8nwS2KUZz+7C94iWMkbAdzRM62O0QGsDh9mJBvdHZkPhSwYZ0q3ddov5De/nE6QK8Q5RubDJ1de0/blZ4WFxqVbXsLHIzSXHdjVgrYvj/VYkPSH86YyHGtE9jVk=,iv:0C3FnSl2zGdDWGVqnbXhu0Sx0b4WWUBZ5usNk/tQWaQ=,tag:lkU+V51pvIDobeeI6omBIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: blobstorage-auth
    namespace: product-feedback
type: Opaque
stringData:
    BLOB_ACCESS_KEY: ENC[AES256_GCM,data:lk7dPiQt45hUaFq9,iv:WYoaORNDFd6wGz/SoLqayiKuFfAd6ptO2K1z0E1Kqo0=,tag:vy5yLw6qlJj+RpJuIbgrCg==,type:str]
    BLOB_SECRET_KEY: ENC[AES256_GCM,data:KV0gwRFh8rv47tRj,iv:PJMfx48DxJC39IoIM2P7BnUv916cx2Hq8p2gCCHBfOA=,tag:mYDtQwkL2tut+I7Q7GvLcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNG1BbGNwZUdUNitkdXY0
            Q3Z6WGVJV3p1VHVuVzgyaVJQbk05M0s3S0dzCi9kc0xxMFQrN2xjL3FoMDZ3MnFK
            aEJsU3d6M1lacDR6TjhFZ09yQnMrd2cKLS0tIEVKSDZWMFdZcmdrSFJDSkZvb3ZE
            ZXdFb3V2NDlZYnJpMFhnd0FYSDIwenMKUgUeQF48NPMUlZH1yZ0dpWkCNzuCs4hA
            M5dKQYqQru7cFCe1A3rk6SrxbGBW5Ep08DbPMPpU54p2c9ZEpPOtLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T22:55:19Z"
    mac: ENC[AES256_GCM,data:6iq0/fGNPvT503HVXcJj/9SMT+5jiEQFSpf8bCSE+BlpKknE8nwS2KUZz+7C94iWMkbAdzRM62O0QGsDh9mJBvdHZkPhSwYZ0q3ddov5De/nE6QK8Q5RubDJ1de0/blZ4WFxqVbXsLHIzSXHdjVgrYvj/VYkPSH86YyHGtE9jVk=,iv:0C3FnSl2zGdDWGVqnbXhu0Sx0b4WWUBZ5usNk/tQWaQ=,tag:lkU+V51pvIDobeeI6omBIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
