apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:Zg+7Ez3TXrLjKBLW8yEaHd86yj/+I69E6iXfoFu9HoFUlMXEl7n4L7ZCTfsasyqsEAVxRdxOvEaPqSU0XQp71zTuIjtrrwpbasn97KA3gr/HOqyC+kaPBw==,iv:FPFNMBOnakui3Z3OQB4PpTO66wFbFeyZjhOW9vmm1Hg=,tag:i3yn9FrXDg6Qx5YUY3MkeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN3hQUE9ZdkUrMzdRancx
            MXlZMUpOVk91VDRRbzJ6VEFmVHBoaEYrbm1vCmYyVWNCTE5oUFFjajJidll5QzBI
            YnRzRk5iYk5LZlRLRERka0V1dlhOL0UKLS0tIE55TkRIaDR0WURjbzBSZGhIYUJK
            dVdoN3FzZk9zbDFIYmgzN2c4RTZhVnMKgV3l3TJW/hRD3MRCvvrhQWT2KlCUe91L
            7oWhqBMj+S5X2uegI7JwyVBe6OH9/Wkocf9ZKZd9Bxjnl8NW+FlbJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T07:33:58Z"
    mac: ENC[AES256_GCM,data:zKcwrQb7dPzD6ucdOuEBFHMoqKJT5tW14f4VUtmYOtgV58QZ15HmRg7Lu5dsdDEN9irDWiiyafp15OaRLEXIPpRkgBlgoxzAcFwEQP4OMpLDCNj/OzZWdcVnuLrVVPjYpisHtRZIPKW59kDGewYnpipvYDGgVUDf5ZnTDFlrDqE=,iv:mzVnqlvg/yuD8yPIzAI+uCMQqA+Qh9MxXrxBfqYYJms=,tag:1mTYrkpCIrubCNV6v2jTiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:V+UJC3J0zDpE5LM=,iv:jmWzv6coT1U+dx+ZHVcS/QKBb0SXxak2ho4XP6F/Cks=,tag:Bd426sEkiet9PsuYLxGPhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN3hQUE9ZdkUrMzdRancx
            MXlZMUpOVk91VDRRbzJ6VEFmVHBoaEYrbm1vCmYyVWNCTE5oUFFjajJidll5QzBI
            YnRzRk5iYk5LZlRLRERka0V1dlhOL0UKLS0tIE55TkRIaDR0WURjbzBSZGhIYUJK
            dVdoN3FzZk9zbDFIYmgzN2c4RTZhVnMKgV3l3TJW/hRD3MRCvvrhQWT2KlCUe91L
            7oWhqBMj+S5X2uegI7JwyVBe6OH9/Wkocf9ZKZd9Bxjnl8NW+FlbJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T07:33:58Z"
    mac: ENC[AES256_GCM,data:zKcwrQb7dPzD6ucdOuEBFHMoqKJT5tW14f4VUtmYOtgV58QZ15HmRg7Lu5dsdDEN9irDWiiyafp15OaRLEXIPpRkgBlgoxzAcFwEQP4OMpLDCNj/OzZWdcVnuLrVVPjYpisHtRZIPKW59kDGewYnpipvYDGgVUDf5ZnTDFlrDqE=,iv:mzVnqlvg/yuD8yPIzAI+uCMQqA+Qh9MxXrxBfqYYJms=,tag:1mTYrkpCIrubCNV6v2jTiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:8kceRcEDLf0=,iv:q8AnT0o0R3KvRkI4B1WkBJreBzp2woPBy/AMvnHyQPs=,tag:9mpxix+0lye4U8GwlWLUPg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:hfM76lwjjirxh/w=,iv:afaary0S4NIa5YMXNk9fmabBLU4h1kfiX1i4aRpT9tU=,tag:WM4EfIu0fLIZ5BKmCqHuzA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:geJCNWbp4+pLNQ/td1LmCTtRQ1I=,iv:Ky6aNOLNOcrAOeNOWawu6hlUzliXQep1o6fd/7RTY/U=,tag:qOUag0L2INLZ3PKmfMVBwA==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3Hao+aGR416MxPmdZabEUQI2zXGT2EiDtvGJG/lR9PNNqSL0DH6CPg==,iv:F1XAog5E04I6dow0L/aghPXH6Ne+q0Ijg+NX/4amzNo=,tag:euOl4AKfknGvBsQKepcD3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN3hQUE9ZdkUrMzdRancx
            MXlZMUpOVk91VDRRbzJ6VEFmVHBoaEYrbm1vCmYyVWNCTE5oUFFjajJidll5QzBI
            YnRzRk5iYk5LZlRLRERka0V1dlhOL0UKLS0tIE55TkRIaDR0WURjbzBSZGhIYUJK
            dVdoN3FzZk9zbDFIYmgzN2c4RTZhVnMKgV3l3TJW/hRD3MRCvvrhQWT2KlCUe91L
            7oWhqBMj+S5X2uegI7JwyVBe6OH9/Wkocf9ZKZd9Bxjnl8NW+FlbJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T07:33:58Z"
    mac: ENC[AES256_GCM,data:zKcwrQb7dPzD6ucdOuEBFHMoqKJT5tW14f4VUtmYOtgV58QZ15HmRg7Lu5dsdDEN9irDWiiyafp15OaRLEXIPpRkgBlgoxzAcFwEQP4OMpLDCNj/OzZWdcVnuLrVVPjYpisHtRZIPKW59kDGewYnpipvYDGgVUDf5ZnTDFlrDqE=,iv:mzVnqlvg/yuD8yPIzAI+uCMQqA+Qh9MxXrxBfqYYJms=,tag:1mTYrkpCIrubCNV6v2jTiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
