apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:xfehCpVkWj1vTEKQ4pNerpmOgrTJNWlRDku33qry3fP95e5L5PR6a/CdroNaPG19bhR0qp3yqVv9jHS5mqMfs/zxdytXLqS4czjWK60NSsqdmG9CQapRjA==,iv:U4ly0PXcMB1HUvner7Bn0KbtdfefE4iNoHziDQ/Q5cc=,tag:Mt4b2S/30fEn+YkQzkYriw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWlYrcUVwb2NrYjF0engy
            RCtzZmJCNWhvN1dxbE85UDZLa1IvOEhYUzJZCmt0R0ZWWFJveXlPZ2JveUwrc09h
            TlFXb0lqZUpNSjE1ODlWZm13VThUeUUKLS0tIFlPVEVNU2tRTUpFQmF4alBDTWtE
            NXhvbndZNnZscHg5RGhmN3FFRFN1ejgKdIg7KuNfgrK3ZPOmFAHWDfr64KtrpEZU
            itGYkh3gTKouxT+R/hJWOoVBgzVD4fgl5OnxiPAUs+Ydzo9pp799ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:19:14Z"
    mac: ENC[AES256_GCM,data:RlM67Zn1fIurQB3Ic9+iL2/JrdFrCWpIdjvNfJJAgfMv619OxfkI6FqA2K6CT8cWQ5UK4y6djLd8giy+XDkxJ42GNlORsQVE6Ns7CYwVwODBg9lkjVgFUEJqZ+1LqsdnU08T0xt7sAH8t0z1gsXIvIQ2xxa33qOSuuxWmOOpsM0=,iv:3lRrNnT4cQd9IgkBW0FSmOX3gbJyvHETeKglsG+40+Y=,tag:xbE4f/325ea6QmEOBJETbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: keycloak
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9WE5Zr7JXW5L6bc=,iv:3Z70lg6xwFaMblErh/ql+jUtIgv40behlwL6sTc0UcY=,tag:l781n8Y3s7ptBVxf33uBlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWlYrcUVwb2NrYjF0engy
            RCtzZmJCNWhvN1dxbE85UDZLa1IvOEhYUzJZCmt0R0ZWWFJveXlPZ2JveUwrc09h
            TlFXb0lqZUpNSjE1ODlWZm13VThUeUUKLS0tIFlPVEVNU2tRTUpFQmF4alBDTWtE
            NXhvbndZNnZscHg5RGhmN3FFRFN1ejgKdIg7KuNfgrK3ZPOmFAHWDfr64KtrpEZU
            itGYkh3gTKouxT+R/hJWOoVBgzVD4fgl5OnxiPAUs+Ydzo9pp799ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:19:14Z"
    mac: ENC[AES256_GCM,data:RlM67Zn1fIurQB3Ic9+iL2/JrdFrCWpIdjvNfJJAgfMv619OxfkI6FqA2K6CT8cWQ5UK4y6djLd8giy+XDkxJ42GNlORsQVE6Ns7CYwVwODBg9lkjVgFUEJqZ+1LqsdnU08T0xt7sAH8t0z1gsXIvIQ2xxa33qOSuuxWmOOpsM0=,iv:3lRrNnT4cQd9IgkBW0FSmOX3gbJyvHETeKglsG+40+Y=,tag:xbE4f/325ea6QmEOBJETbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:pj6ylxVuapo=,iv:P+7rV9SgGGw4yttWXsSlneL9O93rrYbicNgi3xQGTo8=,tag:FDEoCCz+GW/vZu2LxTWCDQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/NsGo8jfHFxM5mk=,iv:EsWxxRjbbogRGvpud27IQJgrmsFxyIreCXs4vAI8Lg8=,tag:xIQ48ixhxRdgFrohUhpKOg==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:nzQo/q/1AiSFopOCa16bzIWxZbM=,iv:ZSwQ9gueTfF2nKcxNDaxxYEldc0squj0eCa2y+00dUQ=,tag:Fqx2hK2R2wON7CdGbmyHgQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:10872n+2N58Al++zkXUVnn5KcdSFUvtD9P8sJB7GGYvl3+TF3JMUmg==,iv:gLI3Y8VT3jlpiJgMLhxIFmmgTJdi4UUojJPBhgHtfzY=,tag:twES/3J/Mt54NTPreUYWQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWlYrcUVwb2NrYjF0engy
            RCtzZmJCNWhvN1dxbE85UDZLa1IvOEhYUzJZCmt0R0ZWWFJveXlPZ2JveUwrc09h
            TlFXb0lqZUpNSjE1ODlWZm13VThUeUUKLS0tIFlPVEVNU2tRTUpFQmF4alBDTWtE
            NXhvbndZNnZscHg5RGhmN3FFRFN1ejgKdIg7KuNfgrK3ZPOmFAHWDfr64KtrpEZU
            itGYkh3gTKouxT+R/hJWOoVBgzVD4fgl5OnxiPAUs+Ydzo9pp799ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:19:14Z"
    mac: ENC[AES256_GCM,data:RlM67Zn1fIurQB3Ic9+iL2/JrdFrCWpIdjvNfJJAgfMv619OxfkI6FqA2K6CT8cWQ5UK4y6djLd8giy+XDkxJ42GNlORsQVE6Ns7CYwVwODBg9lkjVgFUEJqZ+1LqsdnU08T0xt7sAH8t0z1gsXIvIQ2xxa33qOSuuxWmOOpsM0=,iv:3lRrNnT4cQd9IgkBW0FSmOX3gbJyvHETeKglsG+40+Y=,tag:xbE4f/325ea6QmEOBJETbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:ItRXx3P0,iv:DYE8Kkf950PwizBUWOsMXgyTfueKVDvtjKlnlrTmtp0=,tag:reeHxsAm1fu968+bBKa8Xg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:5tpTjLo9x2aHvNM=,iv:25y7Ng2sMVPw96SETJUq3iQd/UIQ6gL7uni7Xu8YVzc=,tag:5fxUMK4uC1E2wpWoOinMpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWlYrcUVwb2NrYjF0engy
            RCtzZmJCNWhvN1dxbE85UDZLa1IvOEhYUzJZCmt0R0ZWWFJveXlPZ2JveUwrc09h
            TlFXb0lqZUpNSjE1ODlWZm13VThUeUUKLS0tIFlPVEVNU2tRTUpFQmF4alBDTWtE
            NXhvbndZNnZscHg5RGhmN3FFRFN1ejgKdIg7KuNfgrK3ZPOmFAHWDfr64KtrpEZU
            itGYkh3gTKouxT+R/hJWOoVBgzVD4fgl5OnxiPAUs+Ydzo9pp799ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:19:14Z"
    mac: ENC[AES256_GCM,data:RlM67Zn1fIurQB3Ic9+iL2/JrdFrCWpIdjvNfJJAgfMv619OxfkI6FqA2K6CT8cWQ5UK4y6djLd8giy+XDkxJ42GNlORsQVE6Ns7CYwVwODBg9lkjVgFUEJqZ+1LqsdnU08T0xt7sAH8t0z1gsXIvIQ2xxa33qOSuuxWmOOpsM0=,iv:3lRrNnT4cQd9IgkBW0FSmOX3gbJyvHETeKglsG+40+Y=,tag:xbE4f/325ea6QmEOBJETbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:84uCuaE1Akk=,iv:7bASJU1XgbRF3dZkYrlKxbP9OApPUxVCgoO9+XGQ3vU=,tag:LkRrqgF1KstSyq2AJg/fPg==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:ak7jY55j5CnM/3E=,iv:MkTiUCQX/YNZC1HTqgHfgqNcBHcR3nVV8Z7yi+I6UJU=,tag:Ca9RKOJ0zjCfpbtt+8nTGQ==,type:str]
    PASSPHRASE: ENC[AES256_GCM,data:4WDqtPSLr145IfHvgqY9Yi+8XcoYewnTXqw5EbwWBvorPQ==,iv:gZxwziOohUK5CwIhAMa+VGL8nCIDK12GWxWK0JXWuDE=,tag:kTF0QyaJ0jlGO8xvyotpbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWlYrcUVwb2NrYjF0engy
            RCtzZmJCNWhvN1dxbE85UDZLa1IvOEhYUzJZCmt0R0ZWWFJveXlPZ2JveUwrc09h
            TlFXb0lqZUpNSjE1ODlWZm13VThUeUUKLS0tIFlPVEVNU2tRTUpFQmF4alBDTWtE
            NXhvbndZNnZscHg5RGhmN3FFRFN1ejgKdIg7KuNfgrK3ZPOmFAHWDfr64KtrpEZU
            itGYkh3gTKouxT+R/hJWOoVBgzVD4fgl5OnxiPAUs+Ydzo9pp799ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:19:14Z"
    mac: ENC[AES256_GCM,data:RlM67Zn1fIurQB3Ic9+iL2/JrdFrCWpIdjvNfJJAgfMv619OxfkI6FqA2K6CT8cWQ5UK4y6djLd8giy+XDkxJ42GNlORsQVE6Ns7CYwVwODBg9lkjVgFUEJqZ+1LqsdnU08T0xt7sAH8t0z1gsXIvIQ2xxa33qOSuuxWmOOpsM0=,iv:3lRrNnT4cQd9IgkBW0FSmOX3gbJyvHETeKglsG+40+Y=,tag:xbE4f/325ea6QmEOBJETbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: product-feedback
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:fvLRgmXsvPypxEf0,iv:GdkPCit8pJvY1PGL4gZDUNJEoenyOUsokln+FEK3Mk0=,tag:LWwN+7KOhn0BVNQUC7pcxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWlYrcUVwb2NrYjF0engy
            RCtzZmJCNWhvN1dxbE85UDZLa1IvOEhYUzJZCmt0R0ZWWFJveXlPZ2JveUwrc09h
            TlFXb0lqZUpNSjE1ODlWZm13VThUeUUKLS0tIFlPVEVNU2tRTUpFQmF4alBDTWtE
            NXhvbndZNnZscHg5RGhmN3FFRFN1ejgKdIg7KuNfgrK3ZPOmFAHWDfr64KtrpEZU
            itGYkh3gTKouxT+R/hJWOoVBgzVD4fgl5OnxiPAUs+Ydzo9pp799ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:19:14Z"
    mac: ENC[AES256_GCM,data:RlM67Zn1fIurQB3Ic9+iL2/JrdFrCWpIdjvNfJJAgfMv619OxfkI6FqA2K6CT8cWQ5UK4y6djLd8giy+XDkxJ42GNlORsQVE6Ns7CYwVwODBg9lkjVgFUEJqZ+1LqsdnU08T0xt7sAH8t0z1gsXIvIQ2xxa33qOSuuxWmOOpsM0=,iv:3lRrNnT4cQd9IgkBW0FSmOX3gbJyvHETeKglsG+40+Y=,tag:xbE4f/325ea6QmEOBJETbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_DB_USERNAME: ENC[AES256_GCM,data:dAZe7TJ0+gY=,iv:rXgxCx4lhQb5bkBPCWw0Wp+cYAINHruEl9orgLxXDK8=,tag:/bdEboT4B2eIl3FhxOiIsw==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:NZ/BRvSJzIQ81/WZjPE1DdSf6Tc=,iv:aCYcYWcIB0R0wsxUD2TbihVOuq7y+5ISUr1TR52SaY8=,tag:Ye/nymUrtYnNjRog9migQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWlYrcUVwb2NrYjF0engy
            RCtzZmJCNWhvN1dxbE85UDZLa1IvOEhYUzJZCmt0R0ZWWFJveXlPZ2JveUwrc09h
            TlFXb0lqZUpNSjE1ODlWZm13VThUeUUKLS0tIFlPVEVNU2tRTUpFQmF4alBDTWtE
            NXhvbndZNnZscHg5RGhmN3FFRFN1ejgKdIg7KuNfgrK3ZPOmFAHWDfr64KtrpEZU
            itGYkh3gTKouxT+R/hJWOoVBgzVD4fgl5OnxiPAUs+Ydzo9pp799ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:19:14Z"
    mac: ENC[AES256_GCM,data:RlM67Zn1fIurQB3Ic9+iL2/JrdFrCWpIdjvNfJJAgfMv619OxfkI6FqA2K6CT8cWQ5UK4y6djLd8giy+XDkxJ42GNlORsQVE6Ns7CYwVwODBg9lkjVgFUEJqZ+1LqsdnU08T0xt7sAH8t0z1gsXIvIQ2xxa33qOSuuxWmOOpsM0=,iv:3lRrNnT4cQd9IgkBW0FSmOX3gbJyvHETeKglsG+40+Y=,tag:xbE4f/325ea6QmEOBJETbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:2eFsow4=,iv:oVJJynWs8swvCYSAbW4NCtXazvbGjbPLrH8HWcDBASU=,tag:jcE5hVHNkwXMZcu2CilRzQ==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:DVpvMiHw6fc/zaS+lQxvBu6HZZM=,iv:iWZqXb/eRTxipIgrFjTVsS0bvibOKmpmVXyeKs7TFI8=,tag:mQnESWTJ3Ome1Y53WgwTig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWlYrcUVwb2NrYjF0engy
            RCtzZmJCNWhvN1dxbE85UDZLa1IvOEhYUzJZCmt0R0ZWWFJveXlPZ2JveUwrc09h
            TlFXb0lqZUpNSjE1ODlWZm13VThUeUUKLS0tIFlPVEVNU2tRTUpFQmF4alBDTWtE
            NXhvbndZNnZscHg5RGhmN3FFRFN1ejgKdIg7KuNfgrK3ZPOmFAHWDfr64KtrpEZU
            itGYkh3gTKouxT+R/hJWOoVBgzVD4fgl5OnxiPAUs+Ydzo9pp799ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:19:14Z"
    mac: ENC[AES256_GCM,data:RlM67Zn1fIurQB3Ic9+iL2/JrdFrCWpIdjvNfJJAgfMv619OxfkI6FqA2K6CT8cWQ5UK4y6djLd8giy+XDkxJ42GNlORsQVE6Ns7CYwVwODBg9lkjVgFUEJqZ+1LqsdnU08T0xt7sAH8t0z1gsXIvIQ2xxa33qOSuuxWmOOpsM0=,iv:3lRrNnT4cQd9IgkBW0FSmOX3gbJyvHETeKglsG+40+Y=,tag:xbE4f/325ea6QmEOBJETbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: seaweedfs
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:Ar6KHh+tXmC0yIRicm3ebbmifTl37MT5CWQVnWvpeUBinO+O3owlPwJ+eTRAKqG5uVo/NClb1q+mWiBWKe2f8rER6o5ERd6pAe4qUkv7GMEwEX9Fz/i5q5W0lr2bIgE0Ahht/mW3sfRP3KXC2hJcxM9YnJUDbqaTUaC+20H/rPajmzrvrATjDrnj+UT/lLKc6ESnNIUH5n2NpMtaCSnRZv9YYCopmWqbI3Cqw6A1R/GFjvduhjsoo6PXhJwuSqb+j1WjU4A2N68AuhNh9Xs/s+UD/ALzJNIsKSEKWOwcr3esD6pXX2cwVtMpkDxL71fXWru7LuJ+IyXihe41SNfEegkYmCBq7xYYcA5CS5sdDr5/NQXS+EPNmuNUAW6oo+uZiTU34iCdf4ipXL6ZKa3Vue/JXLf6kNcI9XYkLZ9qi+TG0awHU6khg2LXfC6w0pL+AQ==,iv:bLM+Io5PYazY75TdSkkLTBnH6MOzUvR3QuiUyCrTkyM=,tag:DA/+u7HiNzyG94ZX+acn0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWlYrcUVwb2NrYjF0engy
            RCtzZmJCNWhvN1dxbE85UDZLa1IvOEhYUzJZCmt0R0ZWWFJveXlPZ2JveUwrc09h
            TlFXb0lqZUpNSjE1ODlWZm13VThUeUUKLS0tIFlPVEVNU2tRTUpFQmF4alBDTWtE
            NXhvbndZNnZscHg5RGhmN3FFRFN1ejgKdIg7KuNfgrK3ZPOmFAHWDfr64KtrpEZU
            itGYkh3gTKouxT+R/hJWOoVBgzVD4fgl5OnxiPAUs+Ydzo9pp799ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:19:14Z"
    mac: ENC[AES256_GCM,data:RlM67Zn1fIurQB3Ic9+iL2/JrdFrCWpIdjvNfJJAgfMv619OxfkI6FqA2K6CT8cWQ5UK4y6djLd8giy+XDkxJ42GNlORsQVE6Ns7CYwVwODBg9lkjVgFUEJqZ+1LqsdnU08T0xt7sAH8t0z1gsXIvIQ2xxa33qOSuuxWmOOpsM0=,iv:3lRrNnT4cQd9IgkBW0FSmOX3gbJyvHETeKglsG+40+Y=,tag:xbE4f/325ea6QmEOBJETbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
