apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:0Pd+FQmUYa9rL02e9QLq1wEM2t492ywZNdLC8X9Lu+74EiPHJjt41Tr4xAuWCnqvUh2QWRuUkkKrCE4ATeA6jNY2T9b5AJrU7vA1LxRoP6ObJpWBWhe05A==,iv:7CWeUDew+EDl3PUnhOusViyOWU/xsqJKnzI7B2mPzUA=,tag:N0DzU489aHMGZXvZoX4QmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT3R3T25EbTJHeFQyR3R1
            K25rRk90Y0VDK254ZlY3ZlJYSnVoUTF6Q1JJCndHOFFXMGE1dmtuV1JUV0ZNbzlC
            Q1BpVW1XTVh3MUd5ZGpkb0RkaEZINE0KLS0tIE1JMGJjcnVTZ3VmVnpRaWJzM3pT
            Zmx3YkJQSHlOS2RKK1dwbE8zV3VObUkKZXy24bRCI6t+Sz0IJXZndvfnCHyIRan7
            622+H/jqpt3ZzUVP8OqI1KN4q5yDsclICpR/1v/ORSYgUAYkhsGO/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:01:58Z"
    mac: ENC[AES256_GCM,data:ZMKn00ceCwTpnXOeZ3gOlStk8f2rQ8COF5DJK/o1CbwPzeTaYwaKTZR+KhqddIh6jXgcSdorAYFIPv+swpor8K+hyrFcCrQ5KcbRejtu5gfIX6UG7Owo/AXp7hajD4k+G79kEeacGgi9bDBT/qo2cBiacHxxeiThttWw4jbXCeI=,iv:3pxz8Rav2Wj7F0+xihOD/IPNdY9mPh/RfIrW+UJwS4Q=,tag:B/V51nUycfq4GbHOpwQw8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: keycloak
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:coaPvOpLaX3V1eo=,iv:o1wOl+9pDmkCiKx+dF5jutxs2hJRkmIQlNJTpHtV8LA=,tag:MYZn92EuE8TErV/wsWiR1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT3R3T25EbTJHeFQyR3R1
            K25rRk90Y0VDK254ZlY3ZlJYSnVoUTF6Q1JJCndHOFFXMGE1dmtuV1JUV0ZNbzlC
            Q1BpVW1XTVh3MUd5ZGpkb0RkaEZINE0KLS0tIE1JMGJjcnVTZ3VmVnpRaWJzM3pT
            Zmx3YkJQSHlOS2RKK1dwbE8zV3VObUkKZXy24bRCI6t+Sz0IJXZndvfnCHyIRan7
            622+H/jqpt3ZzUVP8OqI1KN4q5yDsclICpR/1v/ORSYgUAYkhsGO/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:01:58Z"
    mac: ENC[AES256_GCM,data:ZMKn00ceCwTpnXOeZ3gOlStk8f2rQ8COF5DJK/o1CbwPzeTaYwaKTZR+KhqddIh6jXgcSdorAYFIPv+swpor8K+hyrFcCrQ5KcbRejtu5gfIX6UG7Owo/AXp7hajD4k+G79kEeacGgi9bDBT/qo2cBiacHxxeiThttWw4jbXCeI=,iv:3pxz8Rav2Wj7F0+xihOD/IPNdY9mPh/RfIrW+UJwS4Q=,tag:B/V51nUycfq4GbHOpwQw8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:NkJm8eJkLtI=,iv:RdfPvi4FKd8a4ph2z4sWbBLRieExdg75lRITfL2TCPg=,tag:x7NGJliNjhnN2KqPSyaYkA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:LY0aigZiI73h9Uk=,iv:kJ5bkhSmM1BXYQuLxPMuuNQMoQgc/3/bu0Z5CwNHwgg=,tag:6RxPPWHuI0Vr6DXA2wKVYw==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:U1qk3kF+zymVcZ+HsGX1gQ0oqmA=,iv:Xf31bsehoDX7P+R66CN3FwF7YcS1P+Llg2AAbM9COdg=,tag:3u988/FknRD9irVcKSWoGQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6fj5HE686dHX4l+nKvLCiS+seZyVIskO9YoA8d3qddN8FdkBB+xgNA==,iv:3oFPbxgJDDE0Hl0z6p56l3ip6vzAv4IbAyIAfZApsBs=,tag:xKWK7YE0U4TyjCu3uN+1eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT3R3T25EbTJHeFQyR3R1
            K25rRk90Y0VDK254ZlY3ZlJYSnVoUTF6Q1JJCndHOFFXMGE1dmtuV1JUV0ZNbzlC
            Q1BpVW1XTVh3MUd5ZGpkb0RkaEZINE0KLS0tIE1JMGJjcnVTZ3VmVnpRaWJzM3pT
            Zmx3YkJQSHlOS2RKK1dwbE8zV3VObUkKZXy24bRCI6t+Sz0IJXZndvfnCHyIRan7
            622+H/jqpt3ZzUVP8OqI1KN4q5yDsclICpR/1v/ORSYgUAYkhsGO/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:01:58Z"
    mac: ENC[AES256_GCM,data:ZMKn00ceCwTpnXOeZ3gOlStk8f2rQ8COF5DJK/o1CbwPzeTaYwaKTZR+KhqddIh6jXgcSdorAYFIPv+swpor8K+hyrFcCrQ5KcbRejtu5gfIX6UG7Owo/AXp7hajD4k+G79kEeacGgi9bDBT/qo2cBiacHxxeiThttWw4jbXCeI=,iv:3pxz8Rav2Wj7F0+xihOD/IPNdY9mPh/RfIrW+UJwS4Q=,tag:B/V51nUycfq4GbHOpwQw8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:3bntS6V5,iv:HZsmIerIlZ06Ky7/OKZ7dKY3RNgIhX+ihoo40pvQIzg=,tag:v0TWyCenP0dLY4iy4egrlQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:V0ank+zn7+Sr9+M=,iv:iZMQ2QX/um1+CbFehitPjFhf1N9kjO2zMKH/1yTYrEo=,tag:lEM0STaNw5Mq6U+T2JES6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT3R3T25EbTJHeFQyR3R1
            K25rRk90Y0VDK254ZlY3ZlJYSnVoUTF6Q1JJCndHOFFXMGE1dmtuV1JUV0ZNbzlC
            Q1BpVW1XTVh3MUd5ZGpkb0RkaEZINE0KLS0tIE1JMGJjcnVTZ3VmVnpRaWJzM3pT
            Zmx3YkJQSHlOS2RKK1dwbE8zV3VObUkKZXy24bRCI6t+Sz0IJXZndvfnCHyIRan7
            622+H/jqpt3ZzUVP8OqI1KN4q5yDsclICpR/1v/ORSYgUAYkhsGO/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:01:58Z"
    mac: ENC[AES256_GCM,data:ZMKn00ceCwTpnXOeZ3gOlStk8f2rQ8COF5DJK/o1CbwPzeTaYwaKTZR+KhqddIh6jXgcSdorAYFIPv+swpor8K+hyrFcCrQ5KcbRejtu5gfIX6UG7Owo/AXp7hajD4k+G79kEeacGgi9bDBT/qo2cBiacHxxeiThttWw4jbXCeI=,iv:3pxz8Rav2Wj7F0+xihOD/IPNdY9mPh/RfIrW+UJwS4Q=,tag:B/V51nUycfq4GbHOpwQw8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:X97IcQDi+I4=,iv:S2cnYje1baX2bSlleqsUQGfoy04c52m4V9+7mRgKxnk=,tag:g2QY88YsQxF+8Zh4g8PVCg==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:oiXxGW3klFK3f/g=,iv:eR4N7p500HuplmUmdxWXwnTufy7sYbS0hXp/xP3B39k=,tag:wbGh1ZQ0Axs1sAkPBhTDHQ==,type:str]
    PASSPHRASE: ENC[AES256_GCM,data:oGOuPQWZEPL986BKAMpA17uErXl5sNOyeQJMqnNCTud6fw==,iv:ppYpA/4hY2pChxCF65Omp9Rr9f83DNyIZwRGwJBlZv4=,tag:MHjEBOL1zETg7B2v+zwoZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT3R3T25EbTJHeFQyR3R1
            K25rRk90Y0VDK254ZlY3ZlJYSnVoUTF6Q1JJCndHOFFXMGE1dmtuV1JUV0ZNbzlC
            Q1BpVW1XTVh3MUd5ZGpkb0RkaEZINE0KLS0tIE1JMGJjcnVTZ3VmVnpRaWJzM3pT
            Zmx3YkJQSHlOS2RKK1dwbE8zV3VObUkKZXy24bRCI6t+Sz0IJXZndvfnCHyIRan7
            622+H/jqpt3ZzUVP8OqI1KN4q5yDsclICpR/1v/ORSYgUAYkhsGO/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:01:58Z"
    mac: ENC[AES256_GCM,data:ZMKn00ceCwTpnXOeZ3gOlStk8f2rQ8COF5DJK/o1CbwPzeTaYwaKTZR+KhqddIh6jXgcSdorAYFIPv+swpor8K+hyrFcCrQ5KcbRejtu5gfIX6UG7Owo/AXp7hajD4k+G79kEeacGgi9bDBT/qo2cBiacHxxeiThttWw4jbXCeI=,iv:3pxz8Rav2Wj7F0+xihOD/IPNdY9mPh/RfIrW+UJwS4Q=,tag:B/V51nUycfq4GbHOpwQw8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: product-feedback
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:h/lfAzIv02W2oDA5,iv:XoZW1CTFJJ9EPC/aYJ41LTPg5yxH1IXg4GBjsB+alio=,tag:U9YOvMH7md2/pMMxzr0edw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT3R3T25EbTJHeFQyR3R1
            K25rRk90Y0VDK254ZlY3ZlJYSnVoUTF6Q1JJCndHOFFXMGE1dmtuV1JUV0ZNbzlC
            Q1BpVW1XTVh3MUd5ZGpkb0RkaEZINE0KLS0tIE1JMGJjcnVTZ3VmVnpRaWJzM3pT
            Zmx3YkJQSHlOS2RKK1dwbE8zV3VObUkKZXy24bRCI6t+Sz0IJXZndvfnCHyIRan7
            622+H/jqpt3ZzUVP8OqI1KN4q5yDsclICpR/1v/ORSYgUAYkhsGO/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:01:58Z"
    mac: ENC[AES256_GCM,data:ZMKn00ceCwTpnXOeZ3gOlStk8f2rQ8COF5DJK/o1CbwPzeTaYwaKTZR+KhqddIh6jXgcSdorAYFIPv+swpor8K+hyrFcCrQ5KcbRejtu5gfIX6UG7Owo/AXp7hajD4k+G79kEeacGgi9bDBT/qo2cBiacHxxeiThttWw4jbXCeI=,iv:3pxz8Rav2Wj7F0+xihOD/IPNdY9mPh/RfIrW+UJwS4Q=,tag:B/V51nUycfq4GbHOpwQw8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_DB_USERNAME: ENC[AES256_GCM,data:TqblRAk6To0=,iv:vvn3NnbZ1czreWiEBuJpSxw1XSOIVNmxV20zqQEsm9o=,tag:ELY3pmmgvtzLEg9/7cMz6g==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:pcbMJjLUSBbiwqREzgar6wrxLqU=,iv:1MN8GMpcxlqRZR4Hu6Upvn3jsxtKHgG+ugoVId60nTI=,tag:qR3AlDtxp0rrVSL5n3kRrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT3R3T25EbTJHeFQyR3R1
            K25rRk90Y0VDK254ZlY3ZlJYSnVoUTF6Q1JJCndHOFFXMGE1dmtuV1JUV0ZNbzlC
            Q1BpVW1XTVh3MUd5ZGpkb0RkaEZINE0KLS0tIE1JMGJjcnVTZ3VmVnpRaWJzM3pT
            Zmx3YkJQSHlOS2RKK1dwbE8zV3VObUkKZXy24bRCI6t+Sz0IJXZndvfnCHyIRan7
            622+H/jqpt3ZzUVP8OqI1KN4q5yDsclICpR/1v/ORSYgUAYkhsGO/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:01:58Z"
    mac: ENC[AES256_GCM,data:ZMKn00ceCwTpnXOeZ3gOlStk8f2rQ8COF5DJK/o1CbwPzeTaYwaKTZR+KhqddIh6jXgcSdorAYFIPv+swpor8K+hyrFcCrQ5KcbRejtu5gfIX6UG7Owo/AXp7hajD4k+G79kEeacGgi9bDBT/qo2cBiacHxxeiThttWw4jbXCeI=,iv:3pxz8Rav2Wj7F0+xihOD/IPNdY9mPh/RfIrW+UJwS4Q=,tag:B/V51nUycfq4GbHOpwQw8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:6iWY9UQ=,iv:IPtoxyJwZm9rzxdApkvn2bPgNHGr1krT/HfR3QJWW4c=,tag:C9B6cB9k4+KTpapxsi8Ktw==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:zufU/BBirXy7LNnFfGKmx1bzg78=,iv:EsobuYLLOLt0SWeClk6o1kDAwF/VJiQZeZ/rLHoLQEU=,tag:To4WBtg/4mtUZp10qccc+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT3R3T25EbTJHeFQyR3R1
            K25rRk90Y0VDK254ZlY3ZlJYSnVoUTF6Q1JJCndHOFFXMGE1dmtuV1JUV0ZNbzlC
            Q1BpVW1XTVh3MUd5ZGpkb0RkaEZINE0KLS0tIE1JMGJjcnVTZ3VmVnpRaWJzM3pT
            Zmx3YkJQSHlOS2RKK1dwbE8zV3VObUkKZXy24bRCI6t+Sz0IJXZndvfnCHyIRan7
            622+H/jqpt3ZzUVP8OqI1KN4q5yDsclICpR/1v/ORSYgUAYkhsGO/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:01:58Z"
    mac: ENC[AES256_GCM,data:ZMKn00ceCwTpnXOeZ3gOlStk8f2rQ8COF5DJK/o1CbwPzeTaYwaKTZR+KhqddIh6jXgcSdorAYFIPv+swpor8K+hyrFcCrQ5KcbRejtu5gfIX6UG7Owo/AXp7hajD4k+G79kEeacGgi9bDBT/qo2cBiacHxxeiThttWw4jbXCeI=,iv:3pxz8Rav2Wj7F0+xihOD/IPNdY9mPh/RfIrW+UJwS4Q=,tag:B/V51nUycfq4GbHOpwQw8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: seaweedfs
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:JtHng7JMtGIq8kWS5j8YJ0gHMHcPfF3vzgG03h9anxOLtULZd64995HJX2MaLEIBPeOzujFdp1L11mnTi/CX8CgITIp8QJNVNhlKck9jB2Ohkk321e/Vlvno/Wq3wO7uwMBBuJiXLAnR+h2TD5rsaPZRR0Exqr4lZxvAWju2gBveLGwtQMuTzkyy50tS8k4YREo9o1J8dQnkt2kK4/3KAHL/WzUZG/BOtps2XZDXfFjDlladQ4tFxLLYU1OrTD3bTtxCAotnSJgOhpDVWDtbIhAx37aBsOQU7LCJsJaYcTGNecJ3n6p5I2ChmMRJ5Xldij5IN6ng4Osimx5X6gFB6KHmqXVgkyu8pluojyeG55Wfho3hYKTa3NFOTUUjocu2i0jfOQtLHvvzfLp1PIs6Y4JngUy88zVN1SdXQwiMWVLY66z+TbqTxunFMcM46dRXUg==,iv:/jqEpGdJSscFnmsET07BJ+6BtisPH66n+n5A0mw5uvA=,tag:lAqU++CjLtSaJuwTGhRwnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT3R3T25EbTJHeFQyR3R1
            K25rRk90Y0VDK254ZlY3ZlJYSnVoUTF6Q1JJCndHOFFXMGE1dmtuV1JUV0ZNbzlC
            Q1BpVW1XTVh3MUd5ZGpkb0RkaEZINE0KLS0tIE1JMGJjcnVTZ3VmVnpRaWJzM3pT
            Zmx3YkJQSHlOS2RKK1dwbE8zV3VObUkKZXy24bRCI6t+Sz0IJXZndvfnCHyIRan7
            622+H/jqpt3ZzUVP8OqI1KN4q5yDsclICpR/1v/ORSYgUAYkhsGO/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:01:58Z"
    mac: ENC[AES256_GCM,data:ZMKn00ceCwTpnXOeZ3gOlStk8f2rQ8COF5DJK/o1CbwPzeTaYwaKTZR+KhqddIh6jXgcSdorAYFIPv+swpor8K+hyrFcCrQ5KcbRejtu5gfIX6UG7Owo/AXp7hajD4k+G79kEeacGgi9bDBT/qo2cBiacHxxeiThttWw4jbXCeI=,iv:3pxz8Rav2Wj7F0+xihOD/IPNdY9mPh/RfIrW+UJwS4Q=,tag:B/V51nUycfq4GbHOpwQw8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT3R3T25EbTJHeFQyR3R1
            K25rRk90Y0VDK254ZlY3ZlJYSnVoUTF6Q1JJCndHOFFXMGE1dmtuV1JUV0ZNbzlC
            Q1BpVW1XTVh3MUd5ZGpkb0RkaEZINE0KLS0tIE1JMGJjcnVTZ3VmVnpRaWJzM3pT
            Zmx3YkJQSHlOS2RKK1dwbE8zV3VObUkKZXy24bRCI6t+Sz0IJXZndvfnCHyIRan7
            622+H/jqpt3ZzUVP8OqI1KN4q5yDsclICpR/1v/ORSYgUAYkhsGO/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:01:58Z"
    mac: ENC[AES256_GCM,data:ZMKn00ceCwTpnXOeZ3gOlStk8f2rQ8COF5DJK/o1CbwPzeTaYwaKTZR+KhqddIh6jXgcSdorAYFIPv+swpor8K+hyrFcCrQ5KcbRejtu5gfIX6UG7Owo/AXp7hajD4k+G79kEeacGgi9bDBT/qo2cBiacHxxeiThttWw4jbXCeI=,iv:3pxz8Rav2Wj7F0+xihOD/IPNdY9mPh/RfIrW+UJwS4Q=,tag:B/V51nUycfq4GbHOpwQw8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
