apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:+OTyO98SxuUKN1hVf1fzVdPL+05pkqYr9MzOkraxCyUOqG5EWRIDRqQHYKGU7IWHhhjKCLdgiVsJDiNzrDnxOd0mnMJawDdWESNfOfBxCvDlAJ+T7V84CA==,iv:fuJc9KH0iStSoaqtPDqNFSoKZ0SBMvlpig8/Y64RlgM=,tag:DAQIRdHdva1i4rNDYy3fKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT2Y3bWVIcDFBYWFESXpG
            b1hHR0lxL0xJQ2tpZGQ4KzBzM3VuY3pHOFJzCjlHNkt1RlpKNmVpWm80NVNtRHda
            ZkhqeDFQYWhzd0JVazhyb0d6aGQwUzAKLS0tIFA5Z0Z4NWJuYVNWcWR4WDNRdHNX
            ZEFNQkhpYnRvVGlXVzdsMzExT1ROK3cKccTOb8Z3g/Bci9UZuhr2FhdJQJjKcXoh
            /NUj06I70wTSSSJqry+xo69h/7tkscGikYbKpYoLvpaAhFZxTqmheA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T04:28:10Z"
    mac: ENC[AES256_GCM,data:g5mzBuNeGeMekDQo8x/Oy6FoxRJMKerPjeWKLjKwzmX7eSmbaDpWKHTIe1Qp0G8/IQbfErsyektXzq/pDDBOn8Mj/JiCJTLwi3goahkKHLnDKVtPJMI1A1Lh9bRleBAPTOYZlape7TU6oTwRLuGwqBHC5tUXZ+YBRraW8f83UF0=,iv:79+xObYdi3frKndNnq3cFVf24ul3Q0A1QOyklsPEwp8=,tag:ViNA0OVmNIiZKsa9pcWwHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
