apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:+GDDMzS12pIO36cpn+Vn0q4UC0GF5KTeVXmL6/eGqFxfHBYw01qJV2SUco/CXzhoqdqttypAvLtr04spbR+MbTQwfrJrytRWphtA6hY4N3FTFZWlMTwEww==,iv:QlhJnnGt3CN7Cgt6w9OGEB3xA2+X8AjdF1jImEaWmqk=,tag:RHvJdgDvBzy54J8S5o1ysA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-27T19:06:01Z"
    mac: ENC[AES256_GCM,data:3QT6Lje5BQo6Ckgke5DFeN3LZiJH30PN7fR/AyQgN83CESmZ4ceLsAcPPLTLDeXXLhKVabn7MzybJHF7/lxgoKsFP61KYweIKGHXgGWMQQ1qre8geZXl6r3X4v2SlYbqenejE/c6coZmmsSvTp9nL4ZidMIx91Gt+RG1KiuVeaM=,iv:CHO8vrnBmb3fFXIbv3NrPQEcArMHZPaTUk4AwP862Gw=,tag:PmpOTnhu/1PHMeVpLfng7g==,type:str]
    pgp:
        - created_at: "2025-01-27T19:06:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5oXQ7yzM65bARAAo5zpM6glWoQqw1pwEim0hydIfH0kWPRhTu8A4N2KTq3r
            EOQch/rczTHuZAAbmOKVje9OAK/axMRLI4b9DcupfUvk96I/WdaosF33w/fazjW5
            a5VSvlhMWKQmeO6YUTQ/YWoaY9SJlavXI2YZp5y0ZdqRbMHgpKcEq7QbjANCS2b9
            cyClDs8ngZ/Wjc+A3RI8R/HeclwvJsTmhpCjv0o+blQIPHbTptxDrjxqmG0bMAQM
            tpwPrZdUE5rQOg0S2TKX63e7U/RLoG0m2d/k95x8eDelxHH6norq0uIGiAFPh3cU
            n9Fcs5rh0qr5t3FsgCjdVqBTqybSQ1RWW7U0HN+iuJJL2HA3vU1bJ2zqRh/0vbIT
            hEYHtf+cOpbXOuuOFVL0fP6Jyn7oBAfaFlutQ04IlJgf+xbWwXEZTMOACPrp07L4
            uXsvCHfZ2CCctNbNhMlKO2vXCLgmkH86SVcrR2yAFKuNnpuTGJSmQ3OerqHqrTPR
            2M5IDVuosQwrD2WE6kW8vwW9Rrx0ORBGCpbG2T5AJa6pJUgBGFJw3Mttg7uym0Az
            zpCaOInyPvyUmm93YqhoCQTrnolfVJAzARAj6B3H7POpO0BXIVJBOrEO/C5CuU0B
            MYIvuOZ3IQaDVY3PmB9XwRAbfejDS8hk9qA38M9wEnWu3DZ/ceb9F1pWQ2JH1aTU
            WwEJAhApPuC3tGERhvDty7uHYfq4OpDMWnP1xdAoneifwYy/CYfpaOqt8TPBq5Do
            R8dDk3oXt+VrAtgDf/XkirdrnRH38QGe6kvMddhrLJIt6MNXPpmjriYJORY=
            =WN4l
            -----END PGP MESSAGE-----
          fp: 1049D3246DF059C2C8F54D289A1743BCB333AE5B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
