apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:8QGnrPljzzOYJpoXkmeoRQUyuWxyusDFCAk7YNe1VrQ39v4dPHVywsmxJCvvNYhMUKaDcHOr3ZlmV7vy25hKpgO2cR//bLn0CMCUP56ktgcHViT46a/0pQ==,iv:IxpeLR0E4W9GjuVjdlRGYWzGHfVlumUE4Vd6oFDXFB4=,tag:Yf8VS2ORL9gV6VQX2W81+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYkI3eDdCN2ZFeWNpZUM3
            Q1JDU3ZQWFBEeldjZ2lLQXFUNForZ2V5NWhzCkxHQ1lvL29wZmZmQm1mcktvY0l4
            bkFuYUZ3dDh4Zkh1SHhxVWgzL0RkUzQKLS0tICtHbDZJekJvUXd6cFlsbHRxNk1x
            MExUellwV3lJdVdDa2p4N3FqUHB4UjgKs0UkZael2+Mv5cibwP9GGVCBnhgNhwcZ
            iV0tGy4HO9/DNT/JSLIsA+lA5V44BcquICeKEK0vpdQQhw8U653HgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T19:37:16Z"
    mac: ENC[AES256_GCM,data:26v7Fk7hfAGg/AJhRPNrrRkoL6erjZLfF6FaY3+Adj9bquW6xHUUyA2TT2zjwWE4jGvBNpUP9TWaqeMGERCd+jWhPq0DiUSn+OkkxOw8n2PAYIx8HZ0hPGrh+GM8y0Re7J1yf/t8bhQLIu5OxYWw04hnSwUzRMsXrMBVjGrk+DQ=,iv:JKtUm33Ju3+JBQ+HsuDur1kyuBhixYPMtc2v9VttyEA=,tag:KCFlAjo7tJMuyH9iSkf0kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:fo+GqY2Qk7epdho=,iv:SnWJP7XiLq8XrzAFylGVK3HUai6MTnF8Wi738hdreEI=,tag:6kiv5j57NXNNI5fOTuRvdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYkI3eDdCN2ZFeWNpZUM3
            Q1JDU3ZQWFBEeldjZ2lLQXFUNForZ2V5NWhzCkxHQ1lvL29wZmZmQm1mcktvY0l4
            bkFuYUZ3dDh4Zkh1SHhxVWgzL0RkUzQKLS0tICtHbDZJekJvUXd6cFlsbHRxNk1x
            MExUellwV3lJdVdDa2p4N3FqUHB4UjgKs0UkZael2+Mv5cibwP9GGVCBnhgNhwcZ
            iV0tGy4HO9/DNT/JSLIsA+lA5V44BcquICeKEK0vpdQQhw8U653HgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T19:37:16Z"
    mac: ENC[AES256_GCM,data:26v7Fk7hfAGg/AJhRPNrrRkoL6erjZLfF6FaY3+Adj9bquW6xHUUyA2TT2zjwWE4jGvBNpUP9TWaqeMGERCd+jWhPq0DiUSn+OkkxOw8n2PAYIx8HZ0hPGrh+GM8y0Re7J1yf/t8bhQLIu5OxYWw04hnSwUzRMsXrMBVjGrk+DQ=,iv:JKtUm33Ju3+JBQ+HsuDur1kyuBhixYPMtc2v9VttyEA=,tag:KCFlAjo7tJMuyH9iSkf0kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:OSMQmD4/FP4=,iv:Vruu/CSeYRDJRWJL3745zWznyWxQctDDrdRFS+wzGhE=,tag:ojF2o1iIy4y/XZ5yPB7TQw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:LGUM+ySvTvnxOew=,iv:opqrpYLU2saftxvQS5cn4Dt2UNxfK/qXqNApcZwsppg=,tag:7D69Ts2Pac/3GFIdbsbXDA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:iuykJBMgQOncvxXUkB2cN+YcFvY=,iv:IxBzMBgE3yoZe9Nq4GhL9RpQaH7aa3ISEs3pXrSI/6Q=,tag:N7h4MPENZk5tvQW1AFQ10g==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:diLFhqu0HgdWqIYWRfWhuvX7WbV8WW1QL50SymLbM5Q+NAu4T9zL0A==,iv:x2iFlzh+8Cg1BRQSkE155tUQNLw2FD7qOf9sTTYmxmY=,tag:25WUa8pVR8hVpOIyBSJ6UQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYkI3eDdCN2ZFeWNpZUM3
            Q1JDU3ZQWFBEeldjZ2lLQXFUNForZ2V5NWhzCkxHQ1lvL29wZmZmQm1mcktvY0l4
            bkFuYUZ3dDh4Zkh1SHhxVWgzL0RkUzQKLS0tICtHbDZJekJvUXd6cFlsbHRxNk1x
            MExUellwV3lJdVdDa2p4N3FqUHB4UjgKs0UkZael2+Mv5cibwP9GGVCBnhgNhwcZ
            iV0tGy4HO9/DNT/JSLIsA+lA5V44BcquICeKEK0vpdQQhw8U653HgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T19:37:16Z"
    mac: ENC[AES256_GCM,data:26v7Fk7hfAGg/AJhRPNrrRkoL6erjZLfF6FaY3+Adj9bquW6xHUUyA2TT2zjwWE4jGvBNpUP9TWaqeMGERCd+jWhPq0DiUSn+OkkxOw8n2PAYIx8HZ0hPGrh+GM8y0Re7J1yf/t8bhQLIu5OxYWw04hnSwUzRMsXrMBVjGrk+DQ=,iv:JKtUm33Ju3+JBQ+HsuDur1kyuBhixYPMtc2v9VttyEA=,tag:KCFlAjo7tJMuyH9iSkf0kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:EfEC1Ndu,iv:pwgIw2uUXaivEgmVvm8M2W91Gjnh4bZjqKkBb8O3rNg=,tag:EaaGFG7BjkRtsE2Kv8lQ0w==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:LGJgmg2j17chriU=,iv:YOVE/hOus1nS8RECKClgnlPbPYVMg8dcTovVgiMSfSQ=,tag:BM0K91mBJ/CjoaNNRdDjDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYkI3eDdCN2ZFeWNpZUM3
            Q1JDU3ZQWFBEeldjZ2lLQXFUNForZ2V5NWhzCkxHQ1lvL29wZmZmQm1mcktvY0l4
            bkFuYUZ3dDh4Zkh1SHhxVWgzL0RkUzQKLS0tICtHbDZJekJvUXd6cFlsbHRxNk1x
            MExUellwV3lJdVdDa2p4N3FqUHB4UjgKs0UkZael2+Mv5cibwP9GGVCBnhgNhwcZ
            iV0tGy4HO9/DNT/JSLIsA+lA5V44BcquICeKEK0vpdQQhw8U653HgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T19:37:16Z"
    mac: ENC[AES256_GCM,data:26v7Fk7hfAGg/AJhRPNrrRkoL6erjZLfF6FaY3+Adj9bquW6xHUUyA2TT2zjwWE4jGvBNpUP9TWaqeMGERCd+jWhPq0DiUSn+OkkxOw8n2PAYIx8HZ0hPGrh+GM8y0Re7J1yf/t8bhQLIu5OxYWw04hnSwUzRMsXrMBVjGrk+DQ=,iv:JKtUm33Ju3+JBQ+HsuDur1kyuBhixYPMtc2v9VttyEA=,tag:KCFlAjo7tJMuyH9iSkf0kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:GrkV+BVCkMc=,iv:HFkW64rIsserOKIsnikHnxl/zcu/b+RonGWgzTxK+K4=,tag:CbJQ2GtI9hdsm9TEoP5hKA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:xHfRtfYEGCNzosk=,iv:X/nUNhhHgVhNQ65SXTsb7le2zBxoJyd9zTEziIOgQBI=,tag:FnwhE4Gh+dTadFBsZPWD9Q==,type:str]
    PASSPHRASE: ENC[AES256_GCM,data:cm95moHsGLC7pSgfXZKQfhcZJqkNptPwIFZMQ614/FTzeA==,iv:IuftX685Hh0hdsgtj5MtDWdNJoYy+BlX3YVZ2OJ96Gw=,tag:G8RD7cP/14sSbveui8KE5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYkI3eDdCN2ZFeWNpZUM3
            Q1JDU3ZQWFBEeldjZ2lLQXFUNForZ2V5NWhzCkxHQ1lvL29wZmZmQm1mcktvY0l4
            bkFuYUZ3dDh4Zkh1SHhxVWgzL0RkUzQKLS0tICtHbDZJekJvUXd6cFlsbHRxNk1x
            MExUellwV3lJdVdDa2p4N3FqUHB4UjgKs0UkZael2+Mv5cibwP9GGVCBnhgNhwcZ
            iV0tGy4HO9/DNT/JSLIsA+lA5V44BcquICeKEK0vpdQQhw8U653HgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T19:37:16Z"
    mac: ENC[AES256_GCM,data:26v7Fk7hfAGg/AJhRPNrrRkoL6erjZLfF6FaY3+Adj9bquW6xHUUyA2TT2zjwWE4jGvBNpUP9TWaqeMGERCd+jWhPq0DiUSn+OkkxOw8n2PAYIx8HZ0hPGrh+GM8y0Re7J1yf/t8bhQLIu5OxYWw04hnSwUzRMsXrMBVjGrk+DQ=,iv:JKtUm33Ju3+JBQ+HsuDur1kyuBhixYPMtc2v9VttyEA=,tag:KCFlAjo7tJMuyH9iSkf0kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:9XK+56nmRgffuNtE,iv:b8x8UVaUQDRBl9Z4ZK6mUhBFc6Jtb4mS2p40R1kq6vY=,tag:BIta6r0k9pZfKWKAKCeZ/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYkI3eDdCN2ZFeWNpZUM3
            Q1JDU3ZQWFBEeldjZ2lLQXFUNForZ2V5NWhzCkxHQ1lvL29wZmZmQm1mcktvY0l4
            bkFuYUZ3dDh4Zkh1SHhxVWgzL0RkUzQKLS0tICtHbDZJekJvUXd6cFlsbHRxNk1x
            MExUellwV3lJdVdDa2p4N3FqUHB4UjgKs0UkZael2+Mv5cibwP9GGVCBnhgNhwcZ
            iV0tGy4HO9/DNT/JSLIsA+lA5V44BcquICeKEK0vpdQQhw8U653HgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T19:37:16Z"
    mac: ENC[AES256_GCM,data:26v7Fk7hfAGg/AJhRPNrrRkoL6erjZLfF6FaY3+Adj9bquW6xHUUyA2TT2zjwWE4jGvBNpUP9TWaqeMGERCd+jWhPq0DiUSn+OkkxOw8n2PAYIx8HZ0hPGrh+GM8y0Re7J1yf/t8bhQLIu5OxYWw04hnSwUzRMsXrMBVjGrk+DQ=,iv:JKtUm33Ju3+JBQ+HsuDur1kyuBhixYPMtc2v9VttyEA=,tag:KCFlAjo7tJMuyH9iSkf0kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
