apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:vz8FlbCCE1elQj+Je/HUJuwqIBaPXBt/lG7V6Nc7xHUeLmH6UitGO2JTNNc1Y8H/IwvysUYJDAp+9663WLL96mW6JD2dceL26Qfc15v0UJmFLeI+TLxdmw==,iv:+Bp/ZbREE5RtzA9XyvO4lmKZty4FhuaBOaAzRUEeWOg=,tag:eRi3UbF0iLOlenYQ75Vg6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-27T18:49:03Z"
    mac: ENC[AES256_GCM,data:+PaRyr1se495Y36J1OmjG/vsoYIAfjpcs9fZlsrRUbxDwD6jPGBsIOc5mB8rBvhpyH/3V+PEJY52eCrSHOBJN/IByoUP9frAGBiCkx3N00OGXHh7RJX/UGN2JwoSt8JkjXzlcXDLhgnf0IwNUg+XoxFMYZAAqFGvXUtCcYlkoH8=,iv:C0oRpizu7rMJpKvUl822uDBcp4xH/2CYYkVEgA6CpzE=,tag:ORR2M+FxFnAN5d3mrmsY4g==,type:str]
    pgp:
        - created_at: "2025-01-27T18:49:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5oXQ7yzM65bAQ//bmlgqI+Wkp9Ht9e7ruJdk1+MKDKFFXYL7acLRDO9+9pW
            KBlbZqZGCVQYCnQXvPITYC554840qts9e6dg+5dQrfuhII8LOZYRnBT8e24gZ7Ef
            F/I6ug3KgIesoqlhTHLZ8Dh/Hn5qbBMlga4a41hbfxx5I9/z8FZUy+10/Eu5jaKd
            F6pIozdX8hPHGgo9kRcQbBt8vy5CeZ3nfJpuxFhm61iNMoaa7AmyVP5kWh6CKhDH
            lE5at/ie7tmAuWqW4/MmqcmP/8/uPBnYvnEZT6CraMTof9XPRzrtG8IWK/x+vA/4
            NmnxI5BzOmfoEMQ+ha5Yz3AZLvPlGHg18elsmC1Bh9O+tHYsQwvvOOWiwUHkU9Qz
            u7TVxQ6IfE8a2Jr7FuXVdR8Ik3dOQC8/Eo2G3F91iDrrItmQ8ZiCIKzzYYRvCPg4
            i/Tyv8U/vKu4B21tcTDg844US5tBl2nOI5rxWfqeu1sPEYZgzLv9UoXEGX4LBNQe
            JokDV+CPEjQiUFBhPAFxH1Gc+3zqWXYFxPmp4va2twEDz/dDYN4ZB4junPhddqgP
            ltzoVMOITryx/TuPR9ELYtd7r160fHDxAZmOhDvNIbXUi6F15A/hX+DBc0uuegIv
            Rr1B9Dra0mmj0M5RAcojwlIa8eqzChzV8PnbT4MPqDul2347IbMSeMvsS7rE4jLU
            aAEJAhDl3nsEYkGcKJG5D9hzQ8aYDPEcUvuadYiJMOY5FtrmzN+clCPE3ci/Ya3a
            1roDorbkPsLZ2WzrKMcsyPd1T+9432d0IL7tXWc0JAek4MEu0gLRl5niuJR+TOhr
            n6N14eESB7RC
            =6Z2b
            -----END PGP MESSAGE-----
          fp: 1049D3246DF059C2C8F54D289A1743BCB333AE5B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
