apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:iTyWHNuC5Bg9bATDdKLWIpmO0ewe/PBTfiGh9DmsxpIAITKwymPawAFepf3s7hEexLZBXlG+3DjSKQ8LvImjCys1DUZQVwc0Kx1yUWC4wsX+es+WSnA+rw==,iv:BonWKom7fj4YftKK/dI1nUTBc+eiSUCi63IxhH9c21w=,tag:OSlGisSF7TBdj0M/UM8v5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNURpQllMazRyYnhhcDZM
            Wk9vU09OaHJ1WldneE5Wd2pYQ01EZGZjNzNrCnBGMVVaWVhTNlhlQ1JiVVB4UDRH
            OFM2RDNyVTYzdjBOdDBSbU8vMUVXdmcKLS0tIEVOMFFTZWsrV3diNHRHK2FhMWNM
            eHNaWXE3dWxzVHV6T1NrdzlnQ20zLzAKeRLAOBJAQVjgpFyVVNWSzZwgViwe0gyP
            pWzNrlcvTt3A759sqZaf77PXGY7RStMEx1vb2DIdRLBUco7BY1YRfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-18T03:27:56Z"
    mac: ENC[AES256_GCM,data:b9H2kwemAxkHwpiCvZl9gxaQjmVrilbWck6ktvtpMuoUr8Ulny9QkEW/Pbi850vzkyXjL1Pe0hJJm2RqTUj7iE5NaZXbtVWCm2OF9N7MdQhn+Qb/dFBZ3M7pBpQy0pJT7FT+UmDMSbmrwqUdbTSffKzAXm4RGPZS3m1ZwgIjoow=,iv:KTeCYOjxzAVDAUuXPow3fpiYhi7DTRd2X/MuxSjf4Rc=,tag:51uo57BDNAEviA8H+3DAow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QKBnUUxmh8DZLCs=,iv:9Iz51HWYdOKKrkYzEwvfZsL3/4mL4LGuondoKy3yi2o=,tag:AB5eW8/fO0sqLkjzEz5Qjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNURpQllMazRyYnhhcDZM
            Wk9vU09OaHJ1WldneE5Wd2pYQ01EZGZjNzNrCnBGMVVaWVhTNlhlQ1JiVVB4UDRH
            OFM2RDNyVTYzdjBOdDBSbU8vMUVXdmcKLS0tIEVOMFFTZWsrV3diNHRHK2FhMWNM
            eHNaWXE3dWxzVHV6T1NrdzlnQ20zLzAKeRLAOBJAQVjgpFyVVNWSzZwgViwe0gyP
            pWzNrlcvTt3A759sqZaf77PXGY7RStMEx1vb2DIdRLBUco7BY1YRfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-18T03:27:56Z"
    mac: ENC[AES256_GCM,data:b9H2kwemAxkHwpiCvZl9gxaQjmVrilbWck6ktvtpMuoUr8Ulny9QkEW/Pbi850vzkyXjL1Pe0hJJm2RqTUj7iE5NaZXbtVWCm2OF9N7MdQhn+Qb/dFBZ3M7pBpQy0pJT7FT+UmDMSbmrwqUdbTSffKzAXm4RGPZS3m1ZwgIjoow=,iv:KTeCYOjxzAVDAUuXPow3fpiYhi7DTRd2X/MuxSjf4Rc=,tag:51uo57BDNAEviA8H+3DAow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:PE5V3mswPp8=,iv:sBBTUFjb65UXOYqZRa7KcV3YwqOycEMwKRnwY6mV/JA=,tag:ff/ZxQdnhMGsIIIyMMF6eQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:hEwigHFzkJJ2tqQ=,iv:Drl35ZjU6q0kdfIX+jcBKZOTqH3VEr3W6a8GD5b5zFw=,tag:gyvI2sD4zMTxnKmRwNnd3g==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:xlJjXZNbQ1dLDy2A43SepVDapB4=,iv:ofDbAZdi9e2wpBbmbfQt+nOMxKw6EwxVIDVjFS0xcWI=,tag:rfDcKmqXN2uGhjdssjgrFA==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rKpdt4hK5L6K1fMWYAVDMkeC9kXL4Q4RE3O9ZTN4I2l7yzoBJ8qSSw==,iv:CUivz8IZxUefitAo+rtx8Hnw+tF2pdosS5NsNAbiOkQ=,tag:U7Ib8NQB+89laTm177xMlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNURpQllMazRyYnhhcDZM
            Wk9vU09OaHJ1WldneE5Wd2pYQ01EZGZjNzNrCnBGMVVaWVhTNlhlQ1JiVVB4UDRH
            OFM2RDNyVTYzdjBOdDBSbU8vMUVXdmcKLS0tIEVOMFFTZWsrV3diNHRHK2FhMWNM
            eHNaWXE3dWxzVHV6T1NrdzlnQ20zLzAKeRLAOBJAQVjgpFyVVNWSzZwgViwe0gyP
            pWzNrlcvTt3A759sqZaf77PXGY7RStMEx1vb2DIdRLBUco7BY1YRfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-18T03:27:56Z"
    mac: ENC[AES256_GCM,data:b9H2kwemAxkHwpiCvZl9gxaQjmVrilbWck6ktvtpMuoUr8Ulny9QkEW/Pbi850vzkyXjL1Pe0hJJm2RqTUj7iE5NaZXbtVWCm2OF9N7MdQhn+Qb/dFBZ3M7pBpQy0pJT7FT+UmDMSbmrwqUdbTSffKzAXm4RGPZS3m1ZwgIjoow=,iv:KTeCYOjxzAVDAUuXPow3fpiYhi7DTRd2X/MuxSjf4Rc=,tag:51uo57BDNAEviA8H+3DAow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:E2DaenbC,iv:SueToOetR6CCdVsVud5BloZt/BjPqm8YBT5Dn5xc4HU=,tag:Wyfg59wbecIDo5JE5IbyCg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:AT+G3uf45JdXa4w=,iv:tJnPeJQMASGeQMAxvbHQi50CNB/ox2RFn60LlMwO+Wo=,tag:2BsdvPoMQ10YvZngRTHc2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNURpQllMazRyYnhhcDZM
            Wk9vU09OaHJ1WldneE5Wd2pYQ01EZGZjNzNrCnBGMVVaWVhTNlhlQ1JiVVB4UDRH
            OFM2RDNyVTYzdjBOdDBSbU8vMUVXdmcKLS0tIEVOMFFTZWsrV3diNHRHK2FhMWNM
            eHNaWXE3dWxzVHV6T1NrdzlnQ20zLzAKeRLAOBJAQVjgpFyVVNWSzZwgViwe0gyP
            pWzNrlcvTt3A759sqZaf77PXGY7RStMEx1vb2DIdRLBUco7BY1YRfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-18T03:27:56Z"
    mac: ENC[AES256_GCM,data:b9H2kwemAxkHwpiCvZl9gxaQjmVrilbWck6ktvtpMuoUr8Ulny9QkEW/Pbi850vzkyXjL1Pe0hJJm2RqTUj7iE5NaZXbtVWCm2OF9N7MdQhn+Qb/dFBZ3M7pBpQy0pJT7FT+UmDMSbmrwqUdbTSffKzAXm4RGPZS3m1ZwgIjoow=,iv:KTeCYOjxzAVDAUuXPow3fpiYhi7DTRd2X/MuxSjf4Rc=,tag:51uo57BDNAEviA8H+3DAow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
