apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:9nU3SbzM92hU1EUMR2E3hLCpUjVCGL1C7VGQ+B8Wpb8pHKzZoPDYc6JKnQOQcuqWxjdXDRVDtZazxwARFB556XdYlHceuK78rs2UM70EbkVMcwKu4f1QLA==,iv:DCpWSC6sCWptgw0wwL8rY8VWGOqQO7mbYgapEmlaj1s=,tag:er1z2X/BLCBSCJGB1NMWoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTHg5eUVVa3Voa1ZxaFpG
            R0tlaUJ6UjJoUGx2ak5pVCt2Wlp4YXFBK1ZVClpDSUVueEtCYlV3cWZUbXhXR1Zm
            czQybHE2dHhFZ1RGblZyZHVyWjFtTmcKLS0tIDhuOVdJV0RnbUpMWTR1VUw1WTZC
            am5HdXVjVTY1bFdIZ05IcGtRYXFwK28Kv9j0bOQg5xnCcBcmRNcu2NnY+t9EcyoA
            3cSzN6b/TplC4ZZWNZ4WuZoyaisuQZID3y3639of2rZs0mjmZafhBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T23:58:42Z"
    mac: ENC[AES256_GCM,data:Hqw+YflQCFQwRosuSUis7Z4FxNKdG29uSaYMLyYTrGV+aHQbSLblxXQD4tHnoEn4nbMKRhpqVSHBe4jZjwYbe9GE3ilgjckSDZSrURcCpNIVs+RPr3alnIJnDw5hwJaSvEgsXDlSQudq96Cdz8mQYoAUHYdPTSzFPvnL20S6IYA=,iv:hfi3Fbg84JIaq4CSu3GHDQAR5cRDUkRCaD7IjRdMr0s=,tag:yj0wKFTjSEZdbxbEtpai+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:d0t/3VIO3oifync=,iv:23Fmgwub1lkabFHeR8eC72qYcq1cgIx4j/rqqJrtr8U=,tag:vfsSM3vlgXO+f6go3XNusQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTHg5eUVVa3Voa1ZxaFpG
            R0tlaUJ6UjJoUGx2ak5pVCt2Wlp4YXFBK1ZVClpDSUVueEtCYlV3cWZUbXhXR1Zm
            czQybHE2dHhFZ1RGblZyZHVyWjFtTmcKLS0tIDhuOVdJV0RnbUpMWTR1VUw1WTZC
            am5HdXVjVTY1bFdIZ05IcGtRYXFwK28Kv9j0bOQg5xnCcBcmRNcu2NnY+t9EcyoA
            3cSzN6b/TplC4ZZWNZ4WuZoyaisuQZID3y3639of2rZs0mjmZafhBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T23:58:42Z"
    mac: ENC[AES256_GCM,data:Hqw+YflQCFQwRosuSUis7Z4FxNKdG29uSaYMLyYTrGV+aHQbSLblxXQD4tHnoEn4nbMKRhpqVSHBe4jZjwYbe9GE3ilgjckSDZSrURcCpNIVs+RPr3alnIJnDw5hwJaSvEgsXDlSQudq96Cdz8mQYoAUHYdPTSzFPvnL20S6IYA=,iv:hfi3Fbg84JIaq4CSu3GHDQAR5cRDUkRCaD7IjRdMr0s=,tag:yj0wKFTjSEZdbxbEtpai+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:DdDExJpDBPw=,iv:LGmN6yUkSPlSKgXdwOx4ZIS1RYJb6j16C4dms1lcZcM=,tag:+67dm6SaGXBY2e2K67UZQg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YgfZ5pvfLgHnK3Y=,iv:z4f02A2nhRp1W1gwknIwRsdAnIUxqsaRTNdpnEfU6QI=,tag:8sgo9J4FFtRZf8LaTvqb8w==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:/UK3hpmbz2EJMy6Zu0cXTDNGWqk=,iv:BiGHlMevpDRzVZG0qRt2XnJoTd7bbp2u8HXHfJki850=,tag:cuI4PnqByeWjcLAWgrHgRw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:W4EcvQ8L6048WIGfJ9LlDMjuECOXQ593jGDH4tVnQACoe16hACgnWA==,iv:reH85XoLiL8+YOAHBF/CiMyILfSceWY7E+3Scv+Nreg=,tag:z5dgqB+IimV1qsuDHdGHMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTHg5eUVVa3Voa1ZxaFpG
            R0tlaUJ6UjJoUGx2ak5pVCt2Wlp4YXFBK1ZVClpDSUVueEtCYlV3cWZUbXhXR1Zm
            czQybHE2dHhFZ1RGblZyZHVyWjFtTmcKLS0tIDhuOVdJV0RnbUpMWTR1VUw1WTZC
            am5HdXVjVTY1bFdIZ05IcGtRYXFwK28Kv9j0bOQg5xnCcBcmRNcu2NnY+t9EcyoA
            3cSzN6b/TplC4ZZWNZ4WuZoyaisuQZID3y3639of2rZs0mjmZafhBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T23:58:42Z"
    mac: ENC[AES256_GCM,data:Hqw+YflQCFQwRosuSUis7Z4FxNKdG29uSaYMLyYTrGV+aHQbSLblxXQD4tHnoEn4nbMKRhpqVSHBe4jZjwYbe9GE3ilgjckSDZSrURcCpNIVs+RPr3alnIJnDw5hwJaSvEgsXDlSQudq96Cdz8mQYoAUHYdPTSzFPvnL20S6IYA=,iv:hfi3Fbg84JIaq4CSu3GHDQAR5cRDUkRCaD7IjRdMr0s=,tag:yj0wKFTjSEZdbxbEtpai+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:FR3KF3g1,iv:sApjZeTCWQDn7niugzXhnOVN2QQteHzBVhLgrOPVIDI=,tag:ekUUCutJKfSp9mlmWe87cA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:WPHUrzzWSgQgPo0=,iv:tH3xaVW2hEPwIwFACA4EhNxtENPXr0qcIfIGVW5Wl/Q=,tag:iCuWYQehxoO4C0ZQuu31kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTHg5eUVVa3Voa1ZxaFpG
            R0tlaUJ6UjJoUGx2ak5pVCt2Wlp4YXFBK1ZVClpDSUVueEtCYlV3cWZUbXhXR1Zm
            czQybHE2dHhFZ1RGblZyZHVyWjFtTmcKLS0tIDhuOVdJV0RnbUpMWTR1VUw1WTZC
            am5HdXVjVTY1bFdIZ05IcGtRYXFwK28Kv9j0bOQg5xnCcBcmRNcu2NnY+t9EcyoA
            3cSzN6b/TplC4ZZWNZ4WuZoyaisuQZID3y3639of2rZs0mjmZafhBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T23:58:42Z"
    mac: ENC[AES256_GCM,data:Hqw+YflQCFQwRosuSUis7Z4FxNKdG29uSaYMLyYTrGV+aHQbSLblxXQD4tHnoEn4nbMKRhpqVSHBe4jZjwYbe9GE3ilgjckSDZSrURcCpNIVs+RPr3alnIJnDw5hwJaSvEgsXDlSQudq96Cdz8mQYoAUHYdPTSzFPvnL20S6IYA=,iv:hfi3Fbg84JIaq4CSu3GHDQAR5cRDUkRCaD7IjRdMr0s=,tag:yj0wKFTjSEZdbxbEtpai+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
