apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:85PU95yIJGfXy/4SJvQ0JaexC+XeaQS1QWknIXppOGUvdmv9UxtE5/rL0F3nVzAyt2QAoRr5S/3m37j+RiOzrZqvTJwX7c9oYsBGW9m8KgEagnRDojpg7w==,iv:0KbDMEyvaMs+43accnf/BP2RPJLrRAXQCEJl0N9Wfmo=,tag:TbOK4j7qtoKI1vgFy2Z9vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT0pBYi8yMmJPUERTNm56
            MWVzeFB5UlU3dCtsZTJUaFFreXJ3N0loSm1BCmlSREZSbDRRRmg0ZS9KQjZOOTlt
            MGVwSGg2alp2NFhmdGdxYjFhOTdNamsKLS0tIFMzL2lUb0swVXUvYVF6TDFGc2pi
            NWZsdjUvSFFQdjl3TmY2b2ZzRkhKZWMKQ4xu7I/JFEloUWbfdKmYvBYtIwGEx+ba
            q6yIPqg1OCTmu0zxAE/dpV0T5Lyuvwq/2zNX4pn4fXPpJYvsk//FwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T18:38:57Z"
    mac: ENC[AES256_GCM,data:S6qudvqR4G60uEiPxBQnTZPfenLQWzuxXqtQVis/JvBYw7ZvFba7J+epj4cQvuhDrp2O6n2CaRHbUsIJWyw93f69SDoNy+LbxpSKPtRXuV3AasMJlhz5mTttVtohOP544O/6jUhIEuVsJK52hLLFlFSoeH+PBdUoAuIZAfaHfcY=,iv:47vYirvTvTUFhuVXkd+mT3zsCNd7Mdx69whk1RPn8p8=,tag:kZ1J4CVgbRX1Ntqcqfd9Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:G53hUTidWGzrvhU=,iv:AxEwy4+jpXufUNVamAPKAW8rnaSerEr0AcfBQa94o5Y=,tag:b+C2WVg+73llg7mFvIDqJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT0pBYi8yMmJPUERTNm56
            MWVzeFB5UlU3dCtsZTJUaFFreXJ3N0loSm1BCmlSREZSbDRRRmg0ZS9KQjZOOTlt
            MGVwSGg2alp2NFhmdGdxYjFhOTdNamsKLS0tIFMzL2lUb0swVXUvYVF6TDFGc2pi
            NWZsdjUvSFFQdjl3TmY2b2ZzRkhKZWMKQ4xu7I/JFEloUWbfdKmYvBYtIwGEx+ba
            q6yIPqg1OCTmu0zxAE/dpV0T5Lyuvwq/2zNX4pn4fXPpJYvsk//FwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T18:38:57Z"
    mac: ENC[AES256_GCM,data:S6qudvqR4G60uEiPxBQnTZPfenLQWzuxXqtQVis/JvBYw7ZvFba7J+epj4cQvuhDrp2O6n2CaRHbUsIJWyw93f69SDoNy+LbxpSKPtRXuV3AasMJlhz5mTttVtohOP544O/6jUhIEuVsJK52hLLFlFSoeH+PBdUoAuIZAfaHfcY=,iv:47vYirvTvTUFhuVXkd+mT3zsCNd7Mdx69whk1RPn8p8=,tag:kZ1J4CVgbRX1Ntqcqfd9Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:KuDqAI4xhQU=,iv:f2yB/bdA1zkp8anNsdkQzyKnsx+GrVU4nOzJT46UYo0=,tag:X26l3vFCycuKJMpxQWxkQg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rHYPiBMCi8wpakQ=,iv:s6kDICiH3/XxSqg1H2H1XAHpiY5lWXES7WK2otvFQTQ=,tag:aTb9f1/8nmPSLv5Ri/0Zjw==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:NXtDirwx+2RrclKsGoJ6n/wrSks=,iv:ddacsLOMLPqj/i5U8YQRDyeRIGfmmANgr8HsBb1KPf8=,tag:scqj8blEVmpCue6cD61rBg==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QV/M/pOToWJA7fzL1rP2UJzIYrKRTADtopoTrCM9qTOTGKtvydB61g==,iv:uozGc7ICPJSN0A+8k9ydDuTjegLR/wF2IaEiRzbQAGM=,tag:Tbi47iOgO/Pyol5apWKEBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT0pBYi8yMmJPUERTNm56
            MWVzeFB5UlU3dCtsZTJUaFFreXJ3N0loSm1BCmlSREZSbDRRRmg0ZS9KQjZOOTlt
            MGVwSGg2alp2NFhmdGdxYjFhOTdNamsKLS0tIFMzL2lUb0swVXUvYVF6TDFGc2pi
            NWZsdjUvSFFQdjl3TmY2b2ZzRkhKZWMKQ4xu7I/JFEloUWbfdKmYvBYtIwGEx+ba
            q6yIPqg1OCTmu0zxAE/dpV0T5Lyuvwq/2zNX4pn4fXPpJYvsk//FwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T18:38:57Z"
    mac: ENC[AES256_GCM,data:S6qudvqR4G60uEiPxBQnTZPfenLQWzuxXqtQVis/JvBYw7ZvFba7J+epj4cQvuhDrp2O6n2CaRHbUsIJWyw93f69SDoNy+LbxpSKPtRXuV3AasMJlhz5mTttVtohOP544O/6jUhIEuVsJK52hLLFlFSoeH+PBdUoAuIZAfaHfcY=,iv:47vYirvTvTUFhuVXkd+mT3zsCNd7Mdx69whk1RPn8p8=,tag:kZ1J4CVgbRX1Ntqcqfd9Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:Ar5ZIC2x,iv:ZZE8gc1XWKr25iIQXTKis9KiVxaGFPbo5YJgA/HS2Rs=,tag:u1i7pTyDlrzuAjjZaSI3kw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:bS12s4pQQztOr2s=,iv:OtjJYZ1RieWq3stGqqN/cVB7fGLIjZdN49b74tq+10o=,tag:0Xrcn4dO/eZVOsDBNecAHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT0pBYi8yMmJPUERTNm56
            MWVzeFB5UlU3dCtsZTJUaFFreXJ3N0loSm1BCmlSREZSbDRRRmg0ZS9KQjZOOTlt
            MGVwSGg2alp2NFhmdGdxYjFhOTdNamsKLS0tIFMzL2lUb0swVXUvYVF6TDFGc2pi
            NWZsdjUvSFFQdjl3TmY2b2ZzRkhKZWMKQ4xu7I/JFEloUWbfdKmYvBYtIwGEx+ba
            q6yIPqg1OCTmu0zxAE/dpV0T5Lyuvwq/2zNX4pn4fXPpJYvsk//FwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T18:38:57Z"
    mac: ENC[AES256_GCM,data:S6qudvqR4G60uEiPxBQnTZPfenLQWzuxXqtQVis/JvBYw7ZvFba7J+epj4cQvuhDrp2O6n2CaRHbUsIJWyw93f69SDoNy+LbxpSKPtRXuV3AasMJlhz5mTttVtohOP544O/6jUhIEuVsJK52hLLFlFSoeH+PBdUoAuIZAfaHfcY=,iv:47vYirvTvTUFhuVXkd+mT3zsCNd7Mdx69whk1RPn8p8=,tag:kZ1J4CVgbRX1Ntqcqfd9Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth
    namespace: tailscale
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:ON+fulSdagLFr0SgC5XZnvc=,iv:AxeU2xde+P8UoGu49qMW4rgiUN4/H0WtJ4JABDZJ/Ao=,tag:SE2vIRmeTgTXUs/aWED83Q==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:mC6BL6zajlRCkT/AX+muck0dLSqJXWOQWQwfzfvaXQ9ds5kCyhcYqaDUptL+KbquQKVysigHPYBSQlgfaEvy1g==,iv:W44kIefwH8RMbsT4MSCWIo9TSVUgMakxzSE6qMPI6i0=,tag:Y4rHCTJOuFTrST96oFibhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT0pBYi8yMmJPUERTNm56
            MWVzeFB5UlU3dCtsZTJUaFFreXJ3N0loSm1BCmlSREZSbDRRRmg0ZS9KQjZOOTlt
            MGVwSGg2alp2NFhmdGdxYjFhOTdNamsKLS0tIFMzL2lUb0swVXUvYVF6TDFGc2pi
            NWZsdjUvSFFQdjl3TmY2b2ZzRkhKZWMKQ4xu7I/JFEloUWbfdKmYvBYtIwGEx+ba
            q6yIPqg1OCTmu0zxAE/dpV0T5Lyuvwq/2zNX4pn4fXPpJYvsk//FwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T18:38:57Z"
    mac: ENC[AES256_GCM,data:S6qudvqR4G60uEiPxBQnTZPfenLQWzuxXqtQVis/JvBYw7ZvFba7J+epj4cQvuhDrp2O6n2CaRHbUsIJWyw93f69SDoNy+LbxpSKPtRXuV3AasMJlhz5mTttVtohOP544O/6jUhIEuVsJK52hLLFlFSoeH+PBdUoAuIZAfaHfcY=,iv:47vYirvTvTUFhuVXkd+mT3zsCNd7Mdx69whk1RPn8p8=,tag:kZ1J4CVgbRX1Ntqcqfd9Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
