apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:4yQPM1lJGimhATpkCpai6CPqxYzwWt1Q5Rf1hPesIGYRfIFBky3/SL+FSgW74Z6LvVzPbzbJ+enLbesGdR+Jl24HjjxEDDvZW105+Pt+ia+aAqw7RxkthA==,iv:5TuMeBZoXQ1cXvT1I3CZXXhmXEOV//S+wooRQ1MUZu0=,tag:xIRO86FuQdmJb1zI3cGcOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cStiN25zM2ppN1pOZnhr
            c1JTMlRiRzNERm5wTnpBRC8rd1QvUkV0dFVrCkZlMUg1b2dPYm1MN0tHUEJoSEpv
            YnpramZNYzlMbkM5SW5oNTNTb3Y1d1UKLS0tIGpPblF6Q3BNUGE0aHFReXNReTlM
            UFV5SlFuOVJOMno2Nzk3bVZEbndUOWsKaSsJ0/HcZUzkPvYAEmvFTD3oJRGgiFug
            DBAjrGxmnLqB7Au/XHBNKy7lJutJl8LK2J+mjChnaNVmk2li2N5zQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:35:44Z"
    mac: ENC[AES256_GCM,data:Up9mG11+9r90D0acqhTafQhZNiEakzhwxXjBTPQkWvo9mB4NG0/uR7cA5lRkzW1Chqw2SzAOAZ5JsI1I+hoNUrJB7yDSD7DUjVntcBIW1tvvi1yO+IzYxxBBZSm3oXmJ41bS5iumUd9ZtlP3UWyo28p+v1Iq2l8JR6bED/W5FiI=,iv:R2YWdf6+8xzbAlo8035OBLf+X3v2H8Wz0HrrVuhHOoU=,tag:HnZTU+qCU9kIFjU4/L6m2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:kAczfx73oDIvI3g=,iv:KVdnmvmshCq6EmPRb8akcPGNqKVxfZgMsBU9KvgbaZI=,tag:Rq0cTs60I4AuSrSY8ES3xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cStiN25zM2ppN1pOZnhr
            c1JTMlRiRzNERm5wTnpBRC8rd1QvUkV0dFVrCkZlMUg1b2dPYm1MN0tHUEJoSEpv
            YnpramZNYzlMbkM5SW5oNTNTb3Y1d1UKLS0tIGpPblF6Q3BNUGE0aHFReXNReTlM
            UFV5SlFuOVJOMno2Nzk3bVZEbndUOWsKaSsJ0/HcZUzkPvYAEmvFTD3oJRGgiFug
            DBAjrGxmnLqB7Au/XHBNKy7lJutJl8LK2J+mjChnaNVmk2li2N5zQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:35:44Z"
    mac: ENC[AES256_GCM,data:Up9mG11+9r90D0acqhTafQhZNiEakzhwxXjBTPQkWvo9mB4NG0/uR7cA5lRkzW1Chqw2SzAOAZ5JsI1I+hoNUrJB7yDSD7DUjVntcBIW1tvvi1yO+IzYxxBBZSm3oXmJ41bS5iumUd9ZtlP3UWyo28p+v1Iq2l8JR6bED/W5FiI=,iv:R2YWdf6+8xzbAlo8035OBLf+X3v2H8Wz0HrrVuhHOoU=,tag:HnZTU+qCU9kIFjU4/L6m2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:zP/gLWcZPhc=,iv:7KgpaAVFOQhlAoTJwk6qYNA5ioS2q6nzu5hCMGsJ28o=,tag:wW2JuyQ4i8W/OdlJN2E6Qg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:s1E5sZyyH784kF4=,iv:0Pz7EmAsb5UXUOvz8M8+V9cb1AL0q6rtMds6yT44bJE=,tag:wUgVqHgKionFnhxCc3rU1w==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:3sNhBzAoSG9Q/2aNGYIcpi4pkhU=,iv:VgUVajzTz9399v7aM0Gmt+QuXcuEgmudICDopCXfhvg=,tag:K7iEly9+CbJDMsUOp8pyRQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fgsNNU7vGXhMZO7DLLhN2cY9wmyE9JtyF6eLnvF+bRTgRCCM9DwxyA==,iv:gKdgBAlagTiYquYA/4iHofSdckp1yyixeIuzkVjiTCo=,tag:ltb6KqlX+7AR1lZYJ7B5wQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cStiN25zM2ppN1pOZnhr
            c1JTMlRiRzNERm5wTnpBRC8rd1QvUkV0dFVrCkZlMUg1b2dPYm1MN0tHUEJoSEpv
            YnpramZNYzlMbkM5SW5oNTNTb3Y1d1UKLS0tIGpPblF6Q3BNUGE0aHFReXNReTlM
            UFV5SlFuOVJOMno2Nzk3bVZEbndUOWsKaSsJ0/HcZUzkPvYAEmvFTD3oJRGgiFug
            DBAjrGxmnLqB7Au/XHBNKy7lJutJl8LK2J+mjChnaNVmk2li2N5zQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:35:44Z"
    mac: ENC[AES256_GCM,data:Up9mG11+9r90D0acqhTafQhZNiEakzhwxXjBTPQkWvo9mB4NG0/uR7cA5lRkzW1Chqw2SzAOAZ5JsI1I+hoNUrJB7yDSD7DUjVntcBIW1tvvi1yO+IzYxxBBZSm3oXmJ41bS5iumUd9ZtlP3UWyo28p+v1Iq2l8JR6bED/W5FiI=,iv:R2YWdf6+8xzbAlo8035OBLf+X3v2H8Wz0HrrVuhHOoU=,tag:HnZTU+qCU9kIFjU4/L6m2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:heqU/jnv,iv:L1fAilCKOLJcMG5kHnZzFg/trURsqh4IZZ90PnkzW1k=,tag:zgztnVGVzD3sISt5SkCF8A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:QJ7V6HKMYZapwZQ=,iv:81f/ra0vV7Hb+Om2pWq6JetYLSiUsG6lkYzMqphp0Y4=,tag:erKB4BsZkhJOQFvQ+Hh9Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cStiN25zM2ppN1pOZnhr
            c1JTMlRiRzNERm5wTnpBRC8rd1QvUkV0dFVrCkZlMUg1b2dPYm1MN0tHUEJoSEpv
            YnpramZNYzlMbkM5SW5oNTNTb3Y1d1UKLS0tIGpPblF6Q3BNUGE0aHFReXNReTlM
            UFV5SlFuOVJOMno2Nzk3bVZEbndUOWsKaSsJ0/HcZUzkPvYAEmvFTD3oJRGgiFug
            DBAjrGxmnLqB7Au/XHBNKy7lJutJl8LK2J+mjChnaNVmk2li2N5zQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:35:44Z"
    mac: ENC[AES256_GCM,data:Up9mG11+9r90D0acqhTafQhZNiEakzhwxXjBTPQkWvo9mB4NG0/uR7cA5lRkzW1Chqw2SzAOAZ5JsI1I+hoNUrJB7yDSD7DUjVntcBIW1tvvi1yO+IzYxxBBZSm3oXmJ41bS5iumUd9ZtlP3UWyo28p+v1Iq2l8JR6bED/W5FiI=,iv:R2YWdf6+8xzbAlo8035OBLf+X3v2H8Wz0HrrVuhHOoU=,tag:HnZTU+qCU9kIFjU4/L6m2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:KjNEcl8dUno=,iv:UAJNOXjt8RcQXksJobYUf5qEUVu+r7rS/9shXpl8dvI=,tag:0NNN6DR775f3D3XaWLJHHA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:vgzpQ7q/m00N/3U=,iv:6C3S1XdLaPlaURhdOSOJ/8sREFZnFRLJM+T0/OXeZFk=,tag:+3r54yzt4vTCBJCPlkE69w==,type:str]
    PASSPHRASE: ENC[AES256_GCM,data:R01Fq6scgbWODWF5snoaCRiUxs6i0FzSnShRwd0hUPvLXg==,iv:0pj5+yCaoP1NT0wZdgF0uSAo7g9jhLyqGfO0yJrOA9o=,tag:+3MXo1TAmiBh9F91uHXpQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cStiN25zM2ppN1pOZnhr
            c1JTMlRiRzNERm5wTnpBRC8rd1QvUkV0dFVrCkZlMUg1b2dPYm1MN0tHUEJoSEpv
            YnpramZNYzlMbkM5SW5oNTNTb3Y1d1UKLS0tIGpPblF6Q3BNUGE0aHFReXNReTlM
            UFV5SlFuOVJOMno2Nzk3bVZEbndUOWsKaSsJ0/HcZUzkPvYAEmvFTD3oJRGgiFug
            DBAjrGxmnLqB7Au/XHBNKy7lJutJl8LK2J+mjChnaNVmk2li2N5zQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:35:44Z"
    mac: ENC[AES256_GCM,data:Up9mG11+9r90D0acqhTafQhZNiEakzhwxXjBTPQkWvo9mB4NG0/uR7cA5lRkzW1Chqw2SzAOAZ5JsI1I+hoNUrJB7yDSD7DUjVntcBIW1tvvi1yO+IzYxxBBZSm3oXmJ41bS5iumUd9ZtlP3UWyo28p+v1Iq2l8JR6bED/W5FiI=,iv:R2YWdf6+8xzbAlo8035OBLf+X3v2H8Wz0HrrVuhHOoU=,tag:HnZTU+qCU9kIFjU4/L6m2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: product-feedback
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:43qIyZkzv97uq0kK,iv:kfueUfJZCnXql0O3Q3vzGrpvkHHhxJdXLOU+LYXoceg=,tag:nwwroeGXsg7hwbvqTNAJjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cStiN25zM2ppN1pOZnhr
            c1JTMlRiRzNERm5wTnpBRC8rd1QvUkV0dFVrCkZlMUg1b2dPYm1MN0tHUEJoSEpv
            YnpramZNYzlMbkM5SW5oNTNTb3Y1d1UKLS0tIGpPblF6Q3BNUGE0aHFReXNReTlM
            UFV5SlFuOVJOMno2Nzk3bVZEbndUOWsKaSsJ0/HcZUzkPvYAEmvFTD3oJRGgiFug
            DBAjrGxmnLqB7Au/XHBNKy7lJutJl8LK2J+mjChnaNVmk2li2N5zQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:35:44Z"
    mac: ENC[AES256_GCM,data:Up9mG11+9r90D0acqhTafQhZNiEakzhwxXjBTPQkWvo9mB4NG0/uR7cA5lRkzW1Chqw2SzAOAZ5JsI1I+hoNUrJB7yDSD7DUjVntcBIW1tvvi1yO+IzYxxBBZSm3oXmJ41bS5iumUd9ZtlP3UWyo28p+v1Iq2l8JR6bED/W5FiI=,iv:R2YWdf6+8xzbAlo8035OBLf+X3v2H8Wz0HrrVuhHOoU=,tag:HnZTU+qCU9kIFjU4/L6m2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
