apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:3Z1EFfj0UhT3KnZpaIYlW13FEfT3aka+RtCYDunME7/CxPdneWXmEQNTBynnfG6Lk0uwsHzvwlAjRf9KzX+wruYUmAL0lkcd1nOrzKWzZr9erHWnQV5tCw==,iv:DfhaHIqHD9Z0BP6m9eqjcTZvWhxokIyjgYxcQ5Q3mQI=,tag:xS7qf5dcmFm9eLt8bppD6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOVE0T1k2MU5HK2ZPTXEw
            bDhmc2xGYzVXd2tXc2FSWUEwVHIyQzNCbnpJCjVGRVYxdllqR1JXb09ZVWc0bFln
            NVJlWVVXaU5QbkNUV1lSRGZTRlBLbmMKLS0tIENjTjRSMkx4NU1MS2YydFVuT1VQ
            Y3RHK3pLa2dxaHJnVVZMT0VXVm85cFEK9LgGXGWoWVdjTM/FyNgo10weUPKYr0mE
            KUjPpQm8Tsl8j8uTD8KAqx8RFDzoHufIevYjEX2av9kNCdFP6y7P7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:58:11Z"
    mac: ENC[AES256_GCM,data:ojI9YD5nrWZIBjfucQhTrthcVJ/nC764dRjT+0dYMqqLLuIe8DJ7qxBd8m5BX8nILsp1p3kfJh4PF/JCYkl+r/F/o0my/G7EWD+OmWezylrTduqm1x+KRtDDoRLgIRgbWpP7ClQrazvL0kErIfrckvKLUre8tzZ8LdPP8TTX1ZI=,iv:Nd5SQRMwQ81l/5ll309jjrUarSz0ZE6J/3pbBGdicQE=,tag:yQmJ7ryW7uCt/azxOgurig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5AY7lOK9BLtiBCI=,iv:UeuA6A7jj+gY2aam1v2BqRHbuxOoSIdcApdhUR854FA=,tag:xtfEsS26UNYpzNK74CPuPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOVE0T1k2MU5HK2ZPTXEw
            bDhmc2xGYzVXd2tXc2FSWUEwVHIyQzNCbnpJCjVGRVYxdllqR1JXb09ZVWc0bFln
            NVJlWVVXaU5QbkNUV1lSRGZTRlBLbmMKLS0tIENjTjRSMkx4NU1MS2YydFVuT1VQ
            Y3RHK3pLa2dxaHJnVVZMT0VXVm85cFEK9LgGXGWoWVdjTM/FyNgo10weUPKYr0mE
            KUjPpQm8Tsl8j8uTD8KAqx8RFDzoHufIevYjEX2av9kNCdFP6y7P7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:58:11Z"
    mac: ENC[AES256_GCM,data:ojI9YD5nrWZIBjfucQhTrthcVJ/nC764dRjT+0dYMqqLLuIe8DJ7qxBd8m5BX8nILsp1p3kfJh4PF/JCYkl+r/F/o0my/G7EWD+OmWezylrTduqm1x+KRtDDoRLgIRgbWpP7ClQrazvL0kErIfrckvKLUre8tzZ8LdPP8TTX1ZI=,iv:Nd5SQRMwQ81l/5ll309jjrUarSz0ZE6J/3pbBGdicQE=,tag:yQmJ7ryW7uCt/azxOgurig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Lvas9ecYlmw=,iv:CfhedoXLRKtIsHYXV9aUrqcOFu29NTDY8yhrnwLe1gU=,tag:OwoHsJ0zvWmeHG/VonFTeA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:EvWrFUwY5q8lYbs=,iv:fOL+VrbgQj5qSuyx6wFWLUHian7YAe2sK88VUGtaxzQ=,tag:+yymaizGlMrD21izQzHRKQ==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:a8aLquB0chIjgI2oAvSBteY4GR4=,iv:UKdgZZj7I7qg2QPq+XYnxZFZjugJLD2Fgn+osuu8qn0=,tag:y2Uno9KNXJFz1P2q+lvqYg==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0oiPCfq15x6SsIhZeggBAT1DI6owjYW6sfADdrnlrWGeDLkHbsrkmQ==,iv:BZtUSCRtgdJq2NF3fJ1m4ZIu5MhikibnDGhMCXVeTyw=,tag:5Ui2rZssNc5uzlPgGBnr9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOVE0T1k2MU5HK2ZPTXEw
            bDhmc2xGYzVXd2tXc2FSWUEwVHIyQzNCbnpJCjVGRVYxdllqR1JXb09ZVWc0bFln
            NVJlWVVXaU5QbkNUV1lSRGZTRlBLbmMKLS0tIENjTjRSMkx4NU1MS2YydFVuT1VQ
            Y3RHK3pLa2dxaHJnVVZMT0VXVm85cFEK9LgGXGWoWVdjTM/FyNgo10weUPKYr0mE
            KUjPpQm8Tsl8j8uTD8KAqx8RFDzoHufIevYjEX2av9kNCdFP6y7P7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:58:11Z"
    mac: ENC[AES256_GCM,data:ojI9YD5nrWZIBjfucQhTrthcVJ/nC764dRjT+0dYMqqLLuIe8DJ7qxBd8m5BX8nILsp1p3kfJh4PF/JCYkl+r/F/o0my/G7EWD+OmWezylrTduqm1x+KRtDDoRLgIRgbWpP7ClQrazvL0kErIfrckvKLUre8tzZ8LdPP8TTX1ZI=,iv:Nd5SQRMwQ81l/5ll309jjrUarSz0ZE6J/3pbBGdicQE=,tag:yQmJ7ryW7uCt/azxOgurig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:bI31TxVw,iv:6fft4vTsEAne8OIURVF1UDJ58O5GhEsDeUL2NY6dzAs=,tag:hrmFAWt/IvTsUA/3/3pfrA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:wgwNN2qZ7UcqGlc=,iv:+syQ20UYHGD5I7xz22b7xtJbX2Cs7hZxuAxCCFxHqwA=,tag:FK5r2C4deq3n5uMkVrfe0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOVE0T1k2MU5HK2ZPTXEw
            bDhmc2xGYzVXd2tXc2FSWUEwVHIyQzNCbnpJCjVGRVYxdllqR1JXb09ZVWc0bFln
            NVJlWVVXaU5QbkNUV1lSRGZTRlBLbmMKLS0tIENjTjRSMkx4NU1MS2YydFVuT1VQ
            Y3RHK3pLa2dxaHJnVVZMT0VXVm85cFEK9LgGXGWoWVdjTM/FyNgo10weUPKYr0mE
            KUjPpQm8Tsl8j8uTD8KAqx8RFDzoHufIevYjEX2av9kNCdFP6y7P7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:58:11Z"
    mac: ENC[AES256_GCM,data:ojI9YD5nrWZIBjfucQhTrthcVJ/nC764dRjT+0dYMqqLLuIe8DJ7qxBd8m5BX8nILsp1p3kfJh4PF/JCYkl+r/F/o0my/G7EWD+OmWezylrTduqm1x+KRtDDoRLgIRgbWpP7ClQrazvL0kErIfrckvKLUre8tzZ8LdPP8TTX1ZI=,iv:Nd5SQRMwQ81l/5ll309jjrUarSz0ZE6J/3pbBGdicQE=,tag:yQmJ7ryW7uCt/azxOgurig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:F3tFf+yx5uI=,iv:nQKiQFMHfcF5u57ZmNMsmQr8Yakquj/oKA8Ru/sZH3w=,tag:EAS89YSXMaZZXur9/SsNrw==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:a/n75gGKwEiVjwA=,iv:Ixf05chCia88Jd3XKvbnKYu6SK5Jo54GzZnbOGaExpU=,tag:YJfACTo7VOaapxH+/1rEmg==,type:str]
    PASSPHRASE: ENC[AES256_GCM,data:vZ8maqdJUJ6sLWEcPB0qgI++ta5TrjZshTfk6JEIY/Yb/g==,iv:uHJXC8orzkoBuACBIsyGqyVF87LtOOAWbbneNdqiz1M=,tag:0jErKZlXlwVDTJtfCTdIww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOVE0T1k2MU5HK2ZPTXEw
            bDhmc2xGYzVXd2tXc2FSWUEwVHIyQzNCbnpJCjVGRVYxdllqR1JXb09ZVWc0bFln
            NVJlWVVXaU5QbkNUV1lSRGZTRlBLbmMKLS0tIENjTjRSMkx4NU1MS2YydFVuT1VQ
            Y3RHK3pLa2dxaHJnVVZMT0VXVm85cFEK9LgGXGWoWVdjTM/FyNgo10weUPKYr0mE
            KUjPpQm8Tsl8j8uTD8KAqx8RFDzoHufIevYjEX2av9kNCdFP6y7P7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:58:11Z"
    mac: ENC[AES256_GCM,data:ojI9YD5nrWZIBjfucQhTrthcVJ/nC764dRjT+0dYMqqLLuIe8DJ7qxBd8m5BX8nILsp1p3kfJh4PF/JCYkl+r/F/o0my/G7EWD+OmWezylrTduqm1x+KRtDDoRLgIRgbWpP7ClQrazvL0kErIfrckvKLUre8tzZ8LdPP8TTX1ZI=,iv:Nd5SQRMwQ81l/5ll309jjrUarSz0ZE6J/3pbBGdicQE=,tag:yQmJ7ryW7uCt/azxOgurig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: product-feedback
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:o3FBG7UlklzFxFTs,iv:6p4a7+Zl1esoActyp5CwE1+oJz88ic7CAKDhZYYJT7o=,tag:C+t091kUOml8X8VfhknEOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOVE0T1k2MU5HK2ZPTXEw
            bDhmc2xGYzVXd2tXc2FSWUEwVHIyQzNCbnpJCjVGRVYxdllqR1JXb09ZVWc0bFln
            NVJlWVVXaU5QbkNUV1lSRGZTRlBLbmMKLS0tIENjTjRSMkx4NU1MS2YydFVuT1VQ
            Y3RHK3pLa2dxaHJnVVZMT0VXVm85cFEK9LgGXGWoWVdjTM/FyNgo10weUPKYr0mE
            KUjPpQm8Tsl8j8uTD8KAqx8RFDzoHufIevYjEX2av9kNCdFP6y7P7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:58:11Z"
    mac: ENC[AES256_GCM,data:ojI9YD5nrWZIBjfucQhTrthcVJ/nC764dRjT+0dYMqqLLuIe8DJ7qxBd8m5BX8nILsp1p3kfJh4PF/JCYkl+r/F/o0my/G7EWD+OmWezylrTduqm1x+KRtDDoRLgIRgbWpP7ClQrazvL0kErIfrckvKLUre8tzZ8LdPP8TTX1ZI=,iv:Nd5SQRMwQ81l/5ll309jjrUarSz0ZE6J/3pbBGdicQE=,tag:yQmJ7ryW7uCt/azxOgurig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
