apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:+EOLIIknrbYvsAwATM/jer6yz/BL36zifX1vuk3r2Pzgalluv7rm64HjkW9XqM9F+YOJMTvJbVg78dQ4ZnKJ3xh7dAysstgzTgNfG8QuOO4VARvUk+fKVg==,iv:G+JOrvPCH5s0E3lXieMwd6oTaFPQD6lyl0sgMR/kVFA=,tag:5VhJK8bOwqYC0e4cHmOQgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnE3cS9VdVhrVWRFT2Ix
            UVZ0L2dMa1pKdkl1Z3JHRGg3T3B2dGt5VTJjCk1WWXdLWnI3WERyaExxL3lrNVpk
            NjliRUcwaTIrL1pzd29OK2JvRktpMjgKLS0tIHYwb0IwYVdOcnZaR0Jmd2ZmalZq
            L0N2Sk5DT3BtV0o5QUwyYkJiajZ0WTgKlnFdTjojdIhT1HGCKNs5/Oc3NaHUE60+
            r9mOv2oKF5fVtvlnY06klRVHtXRXLZsmbRkA6cqcIif9f8AzhMsMow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:41:02Z"
    mac: ENC[AES256_GCM,data:R8nMD7eJMs7DggBmAySPN3o4LtHZVx6Y4CePi/rhFa9bghYcwi2IV9ZxZhyb6+PAJSsF1Eb6lTMm536tJ7XC2P2mD6C+tTQYdsFaU06aOXati35213B+H+Y4q/PY0e/woaTp8iVHjxffn5j6EGc6cXaynlLD2NJq9UY19ew9Ij0=,iv:uF7lQnEITzchTEgXAbUN2VxXb9TTlQfVmYc6WVaB3sA=,tag:GNnN716g9oBpPnSkEeWyCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: keycloak
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:EFsczoSZWiu4m88=,iv:T946xtDP/sdcmDEKdeXXiTw8UoFSjFuLbwUBg01gBmY=,tag:Li8YeWSy/0T2oS4xOfzOKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnE3cS9VdVhrVWRFT2Ix
            UVZ0L2dMa1pKdkl1Z3JHRGg3T3B2dGt5VTJjCk1WWXdLWnI3WERyaExxL3lrNVpk
            NjliRUcwaTIrL1pzd29OK2JvRktpMjgKLS0tIHYwb0IwYVdOcnZaR0Jmd2ZmalZq
            L0N2Sk5DT3BtV0o5QUwyYkJiajZ0WTgKlnFdTjojdIhT1HGCKNs5/Oc3NaHUE60+
            r9mOv2oKF5fVtvlnY06klRVHtXRXLZsmbRkA6cqcIif9f8AzhMsMow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:41:02Z"
    mac: ENC[AES256_GCM,data:R8nMD7eJMs7DggBmAySPN3o4LtHZVx6Y4CePi/rhFa9bghYcwi2IV9ZxZhyb6+PAJSsF1Eb6lTMm536tJ7XC2P2mD6C+tTQYdsFaU06aOXati35213B+H+Y4q/PY0e/woaTp8iVHjxffn5j6EGc6cXaynlLD2NJq9UY19ew9Ij0=,iv:uF7lQnEITzchTEgXAbUN2VxXb9TTlQfVmYc6WVaB3sA=,tag:GNnN716g9oBpPnSkEeWyCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:aFwmMHxGTNI=,iv:BLGwvUz/4KrK62f5ZZSawvPBjV82dKgujzAgQ8mmmUc=,tag:fDKWSxtDJwf/xA4w4g5YGQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:o3elqSVW6JpR9T4=,iv:8guOfUgctToc+MNAZuYQPc3a1f31HMdxIqWw+JhyGZk=,tag:81o+hyzoQa/y374sncGinA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:Ftx5TPF2Kqc/MOeoXK/HDx9UxRc=,iv:6iAvHZzNi6l5ojooaUQ8LEfGQn6FEuWKAK5Jw5HbrLg=,tag:dWTqSRZeJ2tUka0Rc0rLKA==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GBeqpnbMi5J6zTAZam98ID5OxPODOZAsgZBD19nv4lS/F8XFSQXkwg==,iv:IkIWWZRyUrXHM80B4BCMB60IAcf29ghTO9jV0jVdNEU=,tag:NGsYNWaggJo240XJJf/7sA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnE3cS9VdVhrVWRFT2Ix
            UVZ0L2dMa1pKdkl1Z3JHRGg3T3B2dGt5VTJjCk1WWXdLWnI3WERyaExxL3lrNVpk
            NjliRUcwaTIrL1pzd29OK2JvRktpMjgKLS0tIHYwb0IwYVdOcnZaR0Jmd2ZmalZq
            L0N2Sk5DT3BtV0o5QUwyYkJiajZ0WTgKlnFdTjojdIhT1HGCKNs5/Oc3NaHUE60+
            r9mOv2oKF5fVtvlnY06klRVHtXRXLZsmbRkA6cqcIif9f8AzhMsMow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:41:02Z"
    mac: ENC[AES256_GCM,data:R8nMD7eJMs7DggBmAySPN3o4LtHZVx6Y4CePi/rhFa9bghYcwi2IV9ZxZhyb6+PAJSsF1Eb6lTMm536tJ7XC2P2mD6C+tTQYdsFaU06aOXati35213B+H+Y4q/PY0e/woaTp8iVHjxffn5j6EGc6cXaynlLD2NJq9UY19ew9Ij0=,iv:uF7lQnEITzchTEgXAbUN2VxXb9TTlQfVmYc6WVaB3sA=,tag:GNnN716g9oBpPnSkEeWyCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:LYr1y7+Y,iv:HTDa0bkXNeYREN2gzwpPrJgVgAaBp+stjGbsmjSFuYE=,tag:FL2fQsuEN+er51DNwR0fNg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:caJ1nnO62nv5Thg=,iv:sOxZTXWzqSsx4B9dDl0HEwUqdz7WkaKZ9xBS8fypzD8=,tag:OtwuSY2VK9HqVxuakxc/sQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnE3cS9VdVhrVWRFT2Ix
            UVZ0L2dMa1pKdkl1Z3JHRGg3T3B2dGt5VTJjCk1WWXdLWnI3WERyaExxL3lrNVpk
            NjliRUcwaTIrL1pzd29OK2JvRktpMjgKLS0tIHYwb0IwYVdOcnZaR0Jmd2ZmalZq
            L0N2Sk5DT3BtV0o5QUwyYkJiajZ0WTgKlnFdTjojdIhT1HGCKNs5/Oc3NaHUE60+
            r9mOv2oKF5fVtvlnY06klRVHtXRXLZsmbRkA6cqcIif9f8AzhMsMow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:41:02Z"
    mac: ENC[AES256_GCM,data:R8nMD7eJMs7DggBmAySPN3o4LtHZVx6Y4CePi/rhFa9bghYcwi2IV9ZxZhyb6+PAJSsF1Eb6lTMm536tJ7XC2P2mD6C+tTQYdsFaU06aOXati35213B+H+Y4q/PY0e/woaTp8iVHjxffn5j6EGc6cXaynlLD2NJq9UY19ew9Ij0=,iv:uF7lQnEITzchTEgXAbUN2VxXb9TTlQfVmYc6WVaB3sA=,tag:GNnN716g9oBpPnSkEeWyCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:NjSxikLNP0A=,iv:QPJkMbb2NzpQcN4oxVsoqIp5gpDdNeRVjKHLm0Tjdr0=,tag:GPAs3dThuo10e0M+syl/CA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:sckxhEUFPW6AScg=,iv:JyGHdk3XA8M0eoz6iR/E6sJewXIZZr+r2Jl1Ad3SvHA=,tag:eUbWFIzozHCBhVt41l/Z1A==,type:str]
    PASSPHRASE: ENC[AES256_GCM,data:F5NkyuARfSoZVW17rXrhWMwFTAfG299InRlAqWgZj4JGmw==,iv:Hcy4VAJt7KvvDlx3AIqKSDw1nkLADgOWYhNzULEps70=,tag:k0W+nZ5lJSmrj5NihbRUOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnE3cS9VdVhrVWRFT2Ix
            UVZ0L2dMa1pKdkl1Z3JHRGg3T3B2dGt5VTJjCk1WWXdLWnI3WERyaExxL3lrNVpk
            NjliRUcwaTIrL1pzd29OK2JvRktpMjgKLS0tIHYwb0IwYVdOcnZaR0Jmd2ZmalZq
            L0N2Sk5DT3BtV0o5QUwyYkJiajZ0WTgKlnFdTjojdIhT1HGCKNs5/Oc3NaHUE60+
            r9mOv2oKF5fVtvlnY06klRVHtXRXLZsmbRkA6cqcIif9f8AzhMsMow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:41:02Z"
    mac: ENC[AES256_GCM,data:R8nMD7eJMs7DggBmAySPN3o4LtHZVx6Y4CePi/rhFa9bghYcwi2IV9ZxZhyb6+PAJSsF1Eb6lTMm536tJ7XC2P2mD6C+tTQYdsFaU06aOXati35213B+H+Y4q/PY0e/woaTp8iVHjxffn5j6EGc6cXaynlLD2NJq9UY19ew9Ij0=,iv:uF7lQnEITzchTEgXAbUN2VxXb9TTlQfVmYc6WVaB3sA=,tag:GNnN716g9oBpPnSkEeWyCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: product-feedback
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:TiyOERG5ZgHmqZJT,iv:+YvhTxEoUjRE6W6EPPus9CtQbOkeTPcLYYBEwKbobdU=,tag:jz3FwFLbWEDHIjxkHX1dsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnE3cS9VdVhrVWRFT2Ix
            UVZ0L2dMa1pKdkl1Z3JHRGg3T3B2dGt5VTJjCk1WWXdLWnI3WERyaExxL3lrNVpk
            NjliRUcwaTIrL1pzd29OK2JvRktpMjgKLS0tIHYwb0IwYVdOcnZaR0Jmd2ZmalZq
            L0N2Sk5DT3BtV0o5QUwyYkJiajZ0WTgKlnFdTjojdIhT1HGCKNs5/Oc3NaHUE60+
            r9mOv2oKF5fVtvlnY06klRVHtXRXLZsmbRkA6cqcIif9f8AzhMsMow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:41:02Z"
    mac: ENC[AES256_GCM,data:R8nMD7eJMs7DggBmAySPN3o4LtHZVx6Y4CePi/rhFa9bghYcwi2IV9ZxZhyb6+PAJSsF1Eb6lTMm536tJ7XC2P2mD6C+tTQYdsFaU06aOXati35213B+H+Y4q/PY0e/woaTp8iVHjxffn5j6EGc6cXaynlLD2NJq9UY19ew9Ij0=,iv:uF7lQnEITzchTEgXAbUN2VxXb9TTlQfVmYc6WVaB3sA=,tag:GNnN716g9oBpPnSkEeWyCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_DB_USERNAME: ENC[AES256_GCM,data:9kded4FOk6c=,iv:P18MF7i0y6X94OzH4BUYot57NUohXOWpwnZE5QtMzPw=,tag:07PE5XG+qYuqx0sZEu/oZQ==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:OMs/Q/NbFjflqeFcraYaazKm8aI=,iv:8EgqqTu444TlIh+wM0AuxACk0J7CloANxOPtynI+d/U=,tag:aiI5i9aB3+PIOURbuj1VQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnE3cS9VdVhrVWRFT2Ix
            UVZ0L2dMa1pKdkl1Z3JHRGg3T3B2dGt5VTJjCk1WWXdLWnI3WERyaExxL3lrNVpk
            NjliRUcwaTIrL1pzd29OK2JvRktpMjgKLS0tIHYwb0IwYVdOcnZaR0Jmd2ZmalZq
            L0N2Sk5DT3BtV0o5QUwyYkJiajZ0WTgKlnFdTjojdIhT1HGCKNs5/Oc3NaHUE60+
            r9mOv2oKF5fVtvlnY06klRVHtXRXLZsmbRkA6cqcIif9f8AzhMsMow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:41:02Z"
    mac: ENC[AES256_GCM,data:R8nMD7eJMs7DggBmAySPN3o4LtHZVx6Y4CePi/rhFa9bghYcwi2IV9ZxZhyb6+PAJSsF1Eb6lTMm536tJ7XC2P2mD6C+tTQYdsFaU06aOXati35213B+H+Y4q/PY0e/woaTp8iVHjxffn5j6EGc6cXaynlLD2NJq9UY19ew9Ij0=,iv:uF7lQnEITzchTEgXAbUN2VxXb9TTlQfVmYc6WVaB3sA=,tag:GNnN716g9oBpPnSkEeWyCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:PrMOeh0=,iv:1/AjzA7V8GsY3YxY81+MRR4GIk3DUyJ320RAVa/ui9A=,tag:smzeoglsOO3SddhWga6HCQ==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:4ddTs27ydKtUXLZqQZhF0R9GaPU=,iv:zo3bfRlt6SacDTAYPcs/Bi+kocpnl3jQykhdpB+FYFw=,tag:2gS5ZnmP90mSuw7ngQcj0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnE3cS9VdVhrVWRFT2Ix
            UVZ0L2dMa1pKdkl1Z3JHRGg3T3B2dGt5VTJjCk1WWXdLWnI3WERyaExxL3lrNVpk
            NjliRUcwaTIrL1pzd29OK2JvRktpMjgKLS0tIHYwb0IwYVdOcnZaR0Jmd2ZmalZq
            L0N2Sk5DT3BtV0o5QUwyYkJiajZ0WTgKlnFdTjojdIhT1HGCKNs5/Oc3NaHUE60+
            r9mOv2oKF5fVtvlnY06klRVHtXRXLZsmbRkA6cqcIif9f8AzhMsMow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:41:02Z"
    mac: ENC[AES256_GCM,data:R8nMD7eJMs7DggBmAySPN3o4LtHZVx6Y4CePi/rhFa9bghYcwi2IV9ZxZhyb6+PAJSsF1Eb6lTMm536tJ7XC2P2mD6C+tTQYdsFaU06aOXati35213B+H+Y4q/PY0e/woaTp8iVHjxffn5j6EGc6cXaynlLD2NJq9UY19ew9Ij0=,iv:uF7lQnEITzchTEgXAbUN2VxXb9TTlQfVmYc6WVaB3sA=,tag:GNnN716g9oBpPnSkEeWyCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: seaweedfs
type: Opaque
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:eC2VPDXWn6QSrQ0eVYRntzf76Eo8h/NZhIPFMPL7HA+FzXYGce7wQDgV3ISx2v+9u2D2rr17TIUFCE376EJD1xUmQWMGbAKlOBka8UglSSGIAKWqYXa1bAgGKZtPaWY0IsITPOtgKtyNOOxCt1LVdUYGYgJ+OrXIVpzEj3fvQaExKUhwhrRznGFN3QsiKann9mCm5RXmlnbpnflH5jIcv3qLZC/ovy1L6kVT4tT0R9jm673JEFgwQ0rLD/S0kr3qdgc/UiervTo4dA/08pmNDRB8MribDnvwjqL0lsM5O6tUxulikZ5+Y4wTvLjhHavdS9dkPuHREKvBA0EvVbqH6879AcMbGcBAqtOkE1lOStK2LBjLWc4rFvaZy6phcav7rm+7sFdQWro6obBMQetYXdhiMNfrGce0q1aejrT1vQf2uMCZjTQofg6nKeItx87aMQ==,iv:1HREZmT4jWr0UuIlt00rdJPdtRmG0Amp17rypX4C7xU=,tag:G6HcQxavRlHfwYvpOlmQ6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnE3cS9VdVhrVWRFT2Ix
            UVZ0L2dMa1pKdkl1Z3JHRGg3T3B2dGt5VTJjCk1WWXdLWnI3WERyaExxL3lrNVpk
            NjliRUcwaTIrL1pzd29OK2JvRktpMjgKLS0tIHYwb0IwYVdOcnZaR0Jmd2ZmalZq
            L0N2Sk5DT3BtV0o5QUwyYkJiajZ0WTgKlnFdTjojdIhT1HGCKNs5/Oc3NaHUE60+
            r9mOv2oKF5fVtvlnY06klRVHtXRXLZsmbRkA6cqcIif9f8AzhMsMow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:41:02Z"
    mac: ENC[AES256_GCM,data:R8nMD7eJMs7DggBmAySPN3o4LtHZVx6Y4CePi/rhFa9bghYcwi2IV9ZxZhyb6+PAJSsF1Eb6lTMm536tJ7XC2P2mD6C+tTQYdsFaU06aOXati35213B+H+Y4q/PY0e/woaTp8iVHjxffn5j6EGc6cXaynlLD2NJq9UY19ew9Ij0=,iv:uF7lQnEITzchTEgXAbUN2VxXb9TTlQfVmYc6WVaB3sA=,tag:GNnN716g9oBpPnSkEeWyCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-auth
    namespace: product-feedback
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: dopamine-kick
type: Opaque
stringData:
    CLIENT_SECRET: ENC[AES256_GCM,data:E9nKl1vpR4TG+yh1YI+Q8iNaAg4AQWByUCxoDCIx5WQ=,iv:IqkRpnqiXkm+yZstYjVTHW6xbFCQVPR0nwAGOUPTcWM=,tag:6P0X/5MuOywZDb3B/TT93A==,type:str]
    ADMIN_CLIENT_SECRET: ENC[AES256_GCM,data:PGFSHKvgwlcA/+rrSKTYdPwY/wXFc0k8qsyT643wofk=,iv:JAzTXo4RHCa5hlzwqXRjKAARd4wEn33vkRqtJDlsiDM=,tag:pguxTFdvNKOD9dLwVemA+w==,type:str]
    DOPAMINE_KICK_CLIENT_SECRET: ENC[AES256_GCM,data:LmammV37IKaxr4mPOOqkOWajdrSo4dXfIAjxmwLqnGc=,iv:Hcd6zunzwm9zNnuYq2A3WjpdaEILwWXJv+PTjPmrPRo=,tag:/Mm+lR4I30ousz9BBUkPrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnE3cS9VdVhrVWRFT2Ix
            UVZ0L2dMa1pKdkl1Z3JHRGg3T3B2dGt5VTJjCk1WWXdLWnI3WERyaExxL3lrNVpk
            NjliRUcwaTIrL1pzd29OK2JvRktpMjgKLS0tIHYwb0IwYVdOcnZaR0Jmd2ZmalZq
            L0N2Sk5DT3BtV0o5QUwyYkJiajZ0WTgKlnFdTjojdIhT1HGCKNs5/Oc3NaHUE60+
            r9mOv2oKF5fVtvlnY06klRVHtXRXLZsmbRkA6cqcIif9f8AzhMsMow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:41:02Z"
    mac: ENC[AES256_GCM,data:R8nMD7eJMs7DggBmAySPN3o4LtHZVx6Y4CePi/rhFa9bghYcwi2IV9ZxZhyb6+PAJSsF1Eb6lTMm536tJ7XC2P2mD6C+tTQYdsFaU06aOXati35213B+H+Y4q/PY0e/woaTp8iVHjxffn5j6EGc6cXaynlLD2NJq9UY19ew9Ij0=,iv:uF7lQnEITzchTEgXAbUN2VxXb9TTlQfVmYc6WVaB3sA=,tag:GNnN716g9oBpPnSkEeWyCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: blobstorage-auth
    namespace: product-feedback
type: Opaque
stringData:
    BLOB_ACCESS_KEY: ENC[AES256_GCM,data:yGpXeQOL8blnqIre,iv:dqLnt5kBMsvNOlc3KJLTu8tvIEAydqWvoxhScXh97gY=,tag:NhJRkJV31UvhNKiM6+VeTA==,type:str]
    BLOB_SECRET_KEY: ENC[AES256_GCM,data:lKwMP4aqLESq9CEH,iv:0nwW9wCsyb9G4Z7Y3Bb0KSBZFZf52lFYFCfPKSHCu2E=,tag:99S+sOh7co3Mml4Lf82tBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnE3cS9VdVhrVWRFT2Ix
            UVZ0L2dMa1pKdkl1Z3JHRGg3T3B2dGt5VTJjCk1WWXdLWnI3WERyaExxL3lrNVpk
            NjliRUcwaTIrL1pzd29OK2JvRktpMjgKLS0tIHYwb0IwYVdOcnZaR0Jmd2ZmalZq
            L0N2Sk5DT3BtV0o5QUwyYkJiajZ0WTgKlnFdTjojdIhT1HGCKNs5/Oc3NaHUE60+
            r9mOv2oKF5fVtvlnY06klRVHtXRXLZsmbRkA6cqcIif9f8AzhMsMow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:41:02Z"
    mac: ENC[AES256_GCM,data:R8nMD7eJMs7DggBmAySPN3o4LtHZVx6Y4CePi/rhFa9bghYcwi2IV9ZxZhyb6+PAJSsF1Eb6lTMm536tJ7XC2P2mD6C+tTQYdsFaU06aOXati35213B+H+Y4q/PY0e/woaTp8iVHjxffn5j6EGc6cXaynlLD2NJq9UY19ew9Ij0=,iv:uF7lQnEITzchTEgXAbUN2VxXb9TTlQfVmYc6WVaB3sA=,tag:GNnN716g9oBpPnSkEeWyCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
