apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:4ep4h8wS2i12JA2QPlqGFghh2flTn9lSrXxtF1nSa4VlKh4b/pom2XG9Pq/GQcMSBTSBSWLzo/21gPkyTYuvbbpZ0TbesayJ309j+XmpB7TWO1ll8uQ1OA==,iv:4zQ9hnG4iU3rQ152g4APrxcfgeSfy/9bT4KOIoST3Tk=,tag:aN3N1wbrwEi7hi07rQBlJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamNnZ3VHeHdzd2FGVitz
            WDM2NGJ6bks2ekI2VmFlUm5pUkh2a1E4ekg4CnJDREFBM2ZYekJPT2VXa3hJVDIx
            QVU5VCsrdExjbHhPd2ZFZDZlZzJFYmcKLS0tIDBxTk40N2FORWlTanRYcFhxY0Ux
            eVNyOW1scjRCRjlDWmk1WlFJUnB6K28K7JDfhhecWyRuC3MO7UxbNBMJQY/Wt9e/
            Y9zoE03JhdGY7R2zIDLjLGIXfJkWxk9X3CSmG0kvvQcorg87B2z76g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:56:16Z"
    mac: ENC[AES256_GCM,data:BhzebVWtDXALCb9cL9uyBUMYFVOSGFmOkrScEMEUj88/ZVjvmNNKF0sxNK89J0PNlZNZ34EArrThtyUbCbtJ89WprKvgCU3yCM5wXHOFiQks2sA4cKkd+VCvfrpUU+zHsRqAeTzIbKpu69Yk/gWtpiG/Am17822cPC823AUvCg4=,iv:AmFb24jS5FU/VQ161jU7UzhoRNwsCipg0FXvbZdnGrg=,tag:TRW7aT7QJx9Vw9jOg5Clvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: keycloak
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Zpi09pIkOHA4FtM=,iv:yBzYZ5X2ctF00+kmYNwSEmDY19wz1RScE4uot6+b9Wk=,tag:xpMV3lB9EsGhS1Veh0tWKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamNnZ3VHeHdzd2FGVitz
            WDM2NGJ6bks2ekI2VmFlUm5pUkh2a1E4ekg4CnJDREFBM2ZYekJPT2VXa3hJVDIx
            QVU5VCsrdExjbHhPd2ZFZDZlZzJFYmcKLS0tIDBxTk40N2FORWlTanRYcFhxY0Ux
            eVNyOW1scjRCRjlDWmk1WlFJUnB6K28K7JDfhhecWyRuC3MO7UxbNBMJQY/Wt9e/
            Y9zoE03JhdGY7R2zIDLjLGIXfJkWxk9X3CSmG0kvvQcorg87B2z76g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:56:16Z"
    mac: ENC[AES256_GCM,data:BhzebVWtDXALCb9cL9uyBUMYFVOSGFmOkrScEMEUj88/ZVjvmNNKF0sxNK89J0PNlZNZ34EArrThtyUbCbtJ89WprKvgCU3yCM5wXHOFiQks2sA4cKkd+VCvfrpUU+zHsRqAeTzIbKpu69Yk/gWtpiG/Am17822cPC823AUvCg4=,iv:AmFb24jS5FU/VQ161jU7UzhoRNwsCipg0FXvbZdnGrg=,tag:TRW7aT7QJx9Vw9jOg5Clvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:n06LVvLiJLk=,iv:uM4ah5tsCfqOdCdvrkwlqaOPIhOAjHz3t93VZRsL3eo=,tag:EV42To5PqAjIy6FbJiAdjQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0G7XpI45nY2K2ck=,iv:buNtLl5ZTz7OchGnIBhOmfoZcMQpPNwyxVW8xls1Vq4=,tag:nT6MtlouOjD1L2AJ77GhPw==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:iWhqkK7GK8Kc4cUP+dR7A2JXu7A=,iv:f7ik9jUwwg+E+zxFZlugxdrHYlOyOmjGYIh+3xXJoKI=,tag:65Hb376vy1ZJXPOFQ43tuw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:D8LyNNMlCXVGewziOXjYG9+GIVNR1jpl5tqEJA8eqsDHceZSVRttBQ==,iv:v6lhoPFqlPWVSl+h5APfb2volUJHYRuCUlFvA+aOMnQ=,tag:ho1XTIl3Exv3WOlpifVvig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamNnZ3VHeHdzd2FGVitz
            WDM2NGJ6bks2ekI2VmFlUm5pUkh2a1E4ekg4CnJDREFBM2ZYekJPT2VXa3hJVDIx
            QVU5VCsrdExjbHhPd2ZFZDZlZzJFYmcKLS0tIDBxTk40N2FORWlTanRYcFhxY0Ux
            eVNyOW1scjRCRjlDWmk1WlFJUnB6K28K7JDfhhecWyRuC3MO7UxbNBMJQY/Wt9e/
            Y9zoE03JhdGY7R2zIDLjLGIXfJkWxk9X3CSmG0kvvQcorg87B2z76g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:56:16Z"
    mac: ENC[AES256_GCM,data:BhzebVWtDXALCb9cL9uyBUMYFVOSGFmOkrScEMEUj88/ZVjvmNNKF0sxNK89J0PNlZNZ34EArrThtyUbCbtJ89WprKvgCU3yCM5wXHOFiQks2sA4cKkd+VCvfrpUU+zHsRqAeTzIbKpu69Yk/gWtpiG/Am17822cPC823AUvCg4=,iv:AmFb24jS5FU/VQ161jU7UzhoRNwsCipg0FXvbZdnGrg=,tag:TRW7aT7QJx9Vw9jOg5Clvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:jbnZlHDM,iv:YGgMzHDhJ4Hpt4KysWmc9IJyMcuSRPaxeg5bAXVb2eY=,tag:DejgW7zLoSr4qUrYinfWpw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:wPpusJToF2oxNkU=,iv:bGcG8Mxsxln4cqvSCyEBX0kPqMeTvkV3uXVSyRGkuUM=,tag:mQjlaRQeZaWBqsepg8SSRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamNnZ3VHeHdzd2FGVitz
            WDM2NGJ6bks2ekI2VmFlUm5pUkh2a1E4ekg4CnJDREFBM2ZYekJPT2VXa3hJVDIx
            QVU5VCsrdExjbHhPd2ZFZDZlZzJFYmcKLS0tIDBxTk40N2FORWlTanRYcFhxY0Ux
            eVNyOW1scjRCRjlDWmk1WlFJUnB6K28K7JDfhhecWyRuC3MO7UxbNBMJQY/Wt9e/
            Y9zoE03JhdGY7R2zIDLjLGIXfJkWxk9X3CSmG0kvvQcorg87B2z76g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:56:16Z"
    mac: ENC[AES256_GCM,data:BhzebVWtDXALCb9cL9uyBUMYFVOSGFmOkrScEMEUj88/ZVjvmNNKF0sxNK89J0PNlZNZ34EArrThtyUbCbtJ89WprKvgCU3yCM5wXHOFiQks2sA4cKkd+VCvfrpUU+zHsRqAeTzIbKpu69Yk/gWtpiG/Am17822cPC823AUvCg4=,iv:AmFb24jS5FU/VQ161jU7UzhoRNwsCipg0FXvbZdnGrg=,tag:TRW7aT7QJx9Vw9jOg5Clvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:Uc40eP36lRg=,iv:D4yNMJwuTzFjqzMpFEHWU7YY56+Ijv5kybI6bA6ZPpw=,tag:ZAR8MisUZAhP2APFDOd0SA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:oZd8rSGrkLDXIv4=,iv:RW2sfxCrgSWCW3VuQDjGTu+Jnw5VRvidWdNw45ni5sU=,tag:34a+u/VjebAZYuwll7L2tw==,type:str]
    PASSPHRASE: ENC[AES256_GCM,data:QwtpCDN3e2cjsZ3aX7E1VoRjeRobyjqfQewjjInBwXDnAA==,iv:KpZtwNDJFRtrTfxY/hZrEO1QbZLwRnuq33GTuN8Br9M=,tag:KABGzJ2m6vsVY+0I518W5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamNnZ3VHeHdzd2FGVitz
            WDM2NGJ6bks2ekI2VmFlUm5pUkh2a1E4ekg4CnJDREFBM2ZYekJPT2VXa3hJVDIx
            QVU5VCsrdExjbHhPd2ZFZDZlZzJFYmcKLS0tIDBxTk40N2FORWlTanRYcFhxY0Ux
            eVNyOW1scjRCRjlDWmk1WlFJUnB6K28K7JDfhhecWyRuC3MO7UxbNBMJQY/Wt9e/
            Y9zoE03JhdGY7R2zIDLjLGIXfJkWxk9X3CSmG0kvvQcorg87B2z76g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:56:16Z"
    mac: ENC[AES256_GCM,data:BhzebVWtDXALCb9cL9uyBUMYFVOSGFmOkrScEMEUj88/ZVjvmNNKF0sxNK89J0PNlZNZ34EArrThtyUbCbtJ89WprKvgCU3yCM5wXHOFiQks2sA4cKkd+VCvfrpUU+zHsRqAeTzIbKpu69Yk/gWtpiG/Am17822cPC823AUvCg4=,iv:AmFb24jS5FU/VQ161jU7UzhoRNwsCipg0FXvbZdnGrg=,tag:TRW7aT7QJx9Vw9jOg5Clvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: product-feedback
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: dopamine-kick
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:yykVqDtMgisoGndl,iv:xV4W++7GusfMoExVFuckm0OYmdHGP93A2lAxAHrthXc=,tag:+/8VCmVz4lQ/yW1ajTciLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamNnZ3VHeHdzd2FGVitz
            WDM2NGJ6bks2ekI2VmFlUm5pUkh2a1E4ekg4CnJDREFBM2ZYekJPT2VXa3hJVDIx
            QVU5VCsrdExjbHhPd2ZFZDZlZzJFYmcKLS0tIDBxTk40N2FORWlTanRYcFhxY0Ux
            eVNyOW1scjRCRjlDWmk1WlFJUnB6K28K7JDfhhecWyRuC3MO7UxbNBMJQY/Wt9e/
            Y9zoE03JhdGY7R2zIDLjLGIXfJkWxk9X3CSmG0kvvQcorg87B2z76g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:56:16Z"
    mac: ENC[AES256_GCM,data:BhzebVWtDXALCb9cL9uyBUMYFVOSGFmOkrScEMEUj88/ZVjvmNNKF0sxNK89J0PNlZNZ34EArrThtyUbCbtJ89WprKvgCU3yCM5wXHOFiQks2sA4cKkd+VCvfrpUU+zHsRqAeTzIbKpu69Yk/gWtpiG/Am17822cPC823AUvCg4=,iv:AmFb24jS5FU/VQ161jU7UzhoRNwsCipg0FXvbZdnGrg=,tag:TRW7aT7QJx9Vw9jOg5Clvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_DB_USERNAME: ENC[AES256_GCM,data:UcarPplEagQ=,iv:1JFBKPHWn8lkc+GSZsKR4s3YXFx8xezer2l2eBRqxhE=,tag:1BZ8h+Ql0pyX0rVqsEuoDQ==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:tsV12d3Q9fup5yUCXTCIp6Wed6c=,iv:3BH/Vu4YYLDnlA6+bxA5QgPBjxMTYADDA/3mkV3dLPc=,tag:KvRbpLcEy2tne3Yc3c7YRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamNnZ3VHeHdzd2FGVitz
            WDM2NGJ6bks2ekI2VmFlUm5pUkh2a1E4ekg4CnJDREFBM2ZYekJPT2VXa3hJVDIx
            QVU5VCsrdExjbHhPd2ZFZDZlZzJFYmcKLS0tIDBxTk40N2FORWlTanRYcFhxY0Ux
            eVNyOW1scjRCRjlDWmk1WlFJUnB6K28K7JDfhhecWyRuC3MO7UxbNBMJQY/Wt9e/
            Y9zoE03JhdGY7R2zIDLjLGIXfJkWxk9X3CSmG0kvvQcorg87B2z76g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:56:16Z"
    mac: ENC[AES256_GCM,data:BhzebVWtDXALCb9cL9uyBUMYFVOSGFmOkrScEMEUj88/ZVjvmNNKF0sxNK89J0PNlZNZ34EArrThtyUbCbtJ89WprKvgCU3yCM5wXHOFiQks2sA4cKkd+VCvfrpUU+zHsRqAeTzIbKpu69Yk/gWtpiG/Am17822cPC823AUvCg4=,iv:AmFb24jS5FU/VQ161jU7UzhoRNwsCipg0FXvbZdnGrg=,tag:TRW7aT7QJx9Vw9jOg5Clvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:/8uzqqQ=,iv:0GcX3VR3/adfAAAWoEIG2QXGXYtl4gcST/ZK0CZD4BA=,tag:mIP1LrE7Lm7/Zt4W5MUX9A==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:y1fJGE/qg+D9e7eiO2O7SU+Ruvc=,iv:iRAJiVG7QdzXi/aGa1ICvXht13SlTLoWxsMZ02Cl7tE=,tag:XS/oEsgARQFR3cnaOHBb5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamNnZ3VHeHdzd2FGVitz
            WDM2NGJ6bks2ekI2VmFlUm5pUkh2a1E4ekg4CnJDREFBM2ZYekJPT2VXa3hJVDIx
            QVU5VCsrdExjbHhPd2ZFZDZlZzJFYmcKLS0tIDBxTk40N2FORWlTanRYcFhxY0Ux
            eVNyOW1scjRCRjlDWmk1WlFJUnB6K28K7JDfhhecWyRuC3MO7UxbNBMJQY/Wt9e/
            Y9zoE03JhdGY7R2zIDLjLGIXfJkWxk9X3CSmG0kvvQcorg87B2z76g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:56:16Z"
    mac: ENC[AES256_GCM,data:BhzebVWtDXALCb9cL9uyBUMYFVOSGFmOkrScEMEUj88/ZVjvmNNKF0sxNK89J0PNlZNZ34EArrThtyUbCbtJ89WprKvgCU3yCM5wXHOFiQks2sA4cKkd+VCvfrpUU+zHsRqAeTzIbKpu69Yk/gWtpiG/Am17822cPC823AUvCg4=,iv:AmFb24jS5FU/VQ161jU7UzhoRNwsCipg0FXvbZdnGrg=,tag:TRW7aT7QJx9Vw9jOg5Clvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: seaweedfs
type: Opaque
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:DDluPKOuw1TiJDAA1L1GqpkZcSRtFvxR+OLcQoPTsPb3kLFcib4yP9X0nMsoyzaTYnsbOsg/Wu3HmTsEFrOvdPs0KAHJp9DDxKStwvKd9G1baNaNCeDiC67TGzDSBb64jBRFppZzEeQwUEanhCNfBI9/QQElL2w0bmHn71C3YOzWacHmjcmMO/Gnl7kSyUS9yl0iSlQDTyhVnjuFpT21bsJHtVgKay8dA5Xz+UabnisQAowHtIOFKPIzm8Y/3QxeoCBnFi1UiGDqoeeH7FH6NyBFc3j2qnOyDlrXHOcbOwwQVQXe3vbwNtYBEZn3ydnIMJw9rsq0ipDkLRVfUaM/UnhzPYBQ8tI6Y1ok9sgD7RZTkdJ7+dLOgFCYvTy9wPnh96LVB9gLAMH7jHv8hTlkjBZClwiVu6H6L4jMPbLsx2mP2JVHQDql70+b2RxdzXpsUg==,iv:f2i4G3ZtD3vBuVinaFaf/76QZXRpLz6cliNWF6AC6ew=,tag:pqZvZpB2EAM3vD1uNpsozQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamNnZ3VHeHdzd2FGVitz
            WDM2NGJ6bks2ekI2VmFlUm5pUkh2a1E4ekg4CnJDREFBM2ZYekJPT2VXa3hJVDIx
            QVU5VCsrdExjbHhPd2ZFZDZlZzJFYmcKLS0tIDBxTk40N2FORWlTanRYcFhxY0Ux
            eVNyOW1scjRCRjlDWmk1WlFJUnB6K28K7JDfhhecWyRuC3MO7UxbNBMJQY/Wt9e/
            Y9zoE03JhdGY7R2zIDLjLGIXfJkWxk9X3CSmG0kvvQcorg87B2z76g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:56:16Z"
    mac: ENC[AES256_GCM,data:BhzebVWtDXALCb9cL9uyBUMYFVOSGFmOkrScEMEUj88/ZVjvmNNKF0sxNK89J0PNlZNZ34EArrThtyUbCbtJ89WprKvgCU3yCM5wXHOFiQks2sA4cKkd+VCvfrpUU+zHsRqAeTzIbKpu69Yk/gWtpiG/Am17822cPC823AUvCg4=,iv:AmFb24jS5FU/VQ161jU7UzhoRNwsCipg0FXvbZdnGrg=,tag:TRW7aT7QJx9Vw9jOg5Clvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-auth
    namespace: product-feedback
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: dopamine-kick
type: Opaque
stringData:
    CLIENT_SECRET: ENC[AES256_GCM,data:BZeFZ3rRqbw8AcLuuCSnYKEtMVpOj7l+5CX7hJcrG7Q=,iv:0CUd+lZh74XUYPM5eW1IBuY9hDin0TQUPiIV1KPVRwE=,tag:YDfJrRBt+dzqdUD5cxWApg==,type:str]
    ADMIN_CLIENT_SECRET: ENC[AES256_GCM,data:nrYNUcPTUqWT90kt4UJJjjX42OVRYlPfIYaMB6dZ7+o=,iv:JTHfntvMwabuVRZcSEyz87x8LV6UyZoju7aZA6J/QWg=,tag:QNtineP4/9CTiFlJPmcUmg==,type:str]
    DOPAMINE_KICK_CLIENT_SECRET: ENC[AES256_GCM,data:KHDGi/BI7LMpIsBPKrkxWCSmhP6fXUxus6eTjOcQreY=,iv:9W+UhQPstxHedIRx6SQChaGMSFmOoINiq7SvUgvM82Y=,tag:DNE0pwzrdwJ1JX6qkqItnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamNnZ3VHeHdzd2FGVitz
            WDM2NGJ6bks2ekI2VmFlUm5pUkh2a1E4ekg4CnJDREFBM2ZYekJPT2VXa3hJVDIx
            QVU5VCsrdExjbHhPd2ZFZDZlZzJFYmcKLS0tIDBxTk40N2FORWlTanRYcFhxY0Ux
            eVNyOW1scjRCRjlDWmk1WlFJUnB6K28K7JDfhhecWyRuC3MO7UxbNBMJQY/Wt9e/
            Y9zoE03JhdGY7R2zIDLjLGIXfJkWxk9X3CSmG0kvvQcorg87B2z76g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:56:16Z"
    mac: ENC[AES256_GCM,data:BhzebVWtDXALCb9cL9uyBUMYFVOSGFmOkrScEMEUj88/ZVjvmNNKF0sxNK89J0PNlZNZ34EArrThtyUbCbtJ89WprKvgCU3yCM5wXHOFiQks2sA4cKkd+VCvfrpUU+zHsRqAeTzIbKpu69Yk/gWtpiG/Am17822cPC823AUvCg4=,iv:AmFb24jS5FU/VQ161jU7UzhoRNwsCipg0FXvbZdnGrg=,tag:TRW7aT7QJx9Vw9jOg5Clvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: blobstorage-auth
    namespace: product-feedback
type: Opaque
stringData:
    BLOB_ACCESS_KEY: ENC[AES256_GCM,data:iemc0nqXRRkBF437,iv:nbm3sV5FHmev13NfyMOmiQ5eH6GV4jHHQaX8knYvSow=,tag:NgYDlhvIV1+vlpbdVQg/sQ==,type:str]
    BLOB_SECRET_KEY: ENC[AES256_GCM,data:9/MhX06WZRnCh7Te,iv:2sO5oP7k1a5ICfD3erGSvZyCSEbkqPbXbcIJJDgDEwo=,tag:+snw2VwlSU/3WgenP93gpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamNnZ3VHeHdzd2FGVitz
            WDM2NGJ6bks2ekI2VmFlUm5pUkh2a1E4ekg4CnJDREFBM2ZYekJPT2VXa3hJVDIx
            QVU5VCsrdExjbHhPd2ZFZDZlZzJFYmcKLS0tIDBxTk40N2FORWlTanRYcFhxY0Ux
            eVNyOW1scjRCRjlDWmk1WlFJUnB6K28K7JDfhhecWyRuC3MO7UxbNBMJQY/Wt9e/
            Y9zoE03JhdGY7R2zIDLjLGIXfJkWxk9X3CSmG0kvvQcorg87B2z76g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:56:16Z"
    mac: ENC[AES256_GCM,data:BhzebVWtDXALCb9cL9uyBUMYFVOSGFmOkrScEMEUj88/ZVjvmNNKF0sxNK89J0PNlZNZ34EArrThtyUbCbtJ89WprKvgCU3yCM5wXHOFiQks2sA4cKkd+VCvfrpUU+zHsRqAeTzIbKpu69Yk/gWtpiG/Am17822cPC823AUvCg4=,iv:AmFb24jS5FU/VQ161jU7UzhoRNwsCipg0FXvbZdnGrg=,tag:TRW7aT7QJx9Vw9jOg5Clvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
