apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:cosMfPPllqaNOIxmAG7AGUebCQ==,iv:aky7bnJMpmXrJbzTIlBVrZmNiAZI5I/dzFkEWlpm97Y=,tag:x8y22zH31KX6E6OpcBjSdw==,type:str]
    namespace: ENC[AES256_GCM,data:kFaILo/SMEBZGYK15ZA+ow==,iv:OknFQuO69H7UgzZtr6MhcJlrWm2rKkw/dnB4MXbp6zY=,tag:LZY+B4gNOSrFleCudLI/0g==,type:str]
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:5jVHUTR2gJKNop2TBzbFHAzxOUU3/NYRKPv07ChINN37foAmvlq2qanAW+aIlNCLJyvqVjD0FgrnaJVZvi340gXmDkLpiER6nQZj9RtzWfrROem+nw9dbQ==,iv:AHzbhrhNab21CRgnZmztTHmi7pZ/HE7j3QvkVKjOvrU=,tag:UE20BygGXIn3JNb6fjkbPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-27T19:03:22Z"
    mac: ENC[AES256_GCM,data:fKY6dSrKb1ZfwnqZ9dC2FF1dr4QuWM2YO1k22584z+6M5FZS37wPIrOH1hBPB3b8xiLK5e9H0OZ8cKnzcpO+Q2YyVD6BJQdARmqtO1oW3Eivrn+G+GD7LFlOGvgDfgm71mXe8oAb3ebJPfnwLP4WYTPys79EceIBiEXBTjs24FI=,iv:ZNyTIiONKHIGSg4oSSXCQ50tRQLIbgjDxPVZp5XIocQ=,tag:ZorSw3qoza3Kxxuj6Mg7Uw==,type:str]
    pgp:
        - created_at: "2025-01-27T19:03:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5oXQ7yzM65bAQ//Sferzh9QEalZ3870O58vk4ubh2rTjB7M9LZ2X9KPnzn2
            JTduIWOCjN/DGPPx2CAl3uGKT9cDbLmd2YuSGRgLFXHzG6x6I8yOa9YUa7F32j+k
            Fv4JnwnKP5a9IsWP/AYeCP7dyJqmIClFgoyeGS+HKJAPf8PB+zsdWqBKo/PpLKLz
            jldZ+AY+7OrvsATzJQF5Mv5+aURgfFv+TM3Gww+33Oe2XEQSNSo0/UGWushrwoT/
            aetPzUOHxB44MjbgU2zMQP72571uShJz17gsdn2p/Q7Sas83tO7X+19Nu4gvkws5
            ffYSJIiBs1E2Hx36/hx58S7HevycM7B09UWMfaVGQCWV36Ug0NMaHFW9/ydj/YYw
            CX/sXPvjejonl0JyF7cp8kJmRWrs7QH3qy4JzeGYfMUy6d8upCWDsd9QyF3ops81
            04trYKtRp7KeQoblMDsaFRIDDm2uaN2wXvSswtuBxI/xBXL+l1SO2YuiK2rLs1Z6
            TIQw0bredfeRq5HU0CxQkQdtR2+CxA7gyadx8QRsrQdtubMRv2Yz25JZG2DBy0A6
            he2ZrXVKEVinpqa/G5RZiELJANf3Wo0DvNLXcDRyI2V6Rz1rEs1d6ZCnuYqRV1l0
            b3JjD0GBgfArBrrBj5HarX4c9S98czYZU8NrkUfK7Nya01NH011vy2OVlBWyNXrU
            aAEJAhAC6mgyrIlAG8niNVj0YvTfSVz7MP+b6d4+uGjqO/ckoXFViks6bU6ayJs3
            oR+a5O9YsM1cGNuea4cibtlZYJJcWaVRErQK5WkupGZjhsotUQrlrTAYSOJPQWjg
            Ksf6PN7AJEUD
            =gOTR
            -----END PGP MESSAGE-----
          fp: 1049D3246DF059C2C8F54D289A1743BCB333AE5B
    encrypted_regex: ^(data|stringData|metadata)$
    version: 3.9.2
