apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:HTMHofQO3If1o3g4LFDKkAP4/bS7Ai2b3zhjUv/W80N10cbvNCjugE40w3qHDtFjfvl8ZzSpMdvWfDSCfrZOvVK/N9vENuYLgj7THeRuLCuMXhzpFz0wMw==,iv:vSLoVXgGlRA1bBfs6c6DN5RhKLErO6nwrvTdpQtOMHE=,tag:R38ZLvH4P9/ZR0M30imDHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZmpyZmdQU25UZDF5S054
            SEJNdlV5ZlQzVUN2NkFDQ01LWnBubVg0TzIwCjRoemtyb3N2SGlab214Z3A5OGc2
            VDFxU2ZzMlVvQXQ0ZTdGU3pzYUZrbHMKLS0tIFp6SEtSd0ZIakI1dlFHcHp3SEw2
            ZmZyZWZ1V0lFYS92WUxlTlRWeGg4WWcKe+y2mSGsln9qOXxGQdCZM9IX2FGWtxYR
            /MSQddNjC5myRAQpqtWoHzO9I5bJvUGH15F9EuD3QCdWtfC9n8LyGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T22:42:29Z"
    mac: ENC[AES256_GCM,data:nKZy9xFzjZJ6y+hv+kPUwzYdWF+WGy+nMcd725KjDOe60tE5QssVdhBlF50TpGoJrA6dfRxslVWEyfnEbUH0LaLbX164UDeGUPBxxjaTg2cWZgTJSfuVUqzEpLPBZDD5QLL4Ydr5CmTl6NZfsAm9f6qJHD7SF2r/PCR5CnkR/t8=,iv:BoVfuDKMG71kGQGcjivW6Nb/A6BdDhYdYrwfmUq/M34=,tag:pvyvcrswp14tLABlUsD1Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XxnpmA2Tuc3kmsk=,iv:kK1MWjVbl+x8Vv0QDdOsGL8KB/gQpQPD0IZhFDewQ5Q=,tag:sej7mBXk0BIJxuMhCNNfdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZmpyZmdQU25UZDF5S054
            SEJNdlV5ZlQzVUN2NkFDQ01LWnBubVg0TzIwCjRoemtyb3N2SGlab214Z3A5OGc2
            VDFxU2ZzMlVvQXQ0ZTdGU3pzYUZrbHMKLS0tIFp6SEtSd0ZIakI1dlFHcHp3SEw2
            ZmZyZWZ1V0lFYS92WUxlTlRWeGg4WWcKe+y2mSGsln9qOXxGQdCZM9IX2FGWtxYR
            /MSQddNjC5myRAQpqtWoHzO9I5bJvUGH15F9EuD3QCdWtfC9n8LyGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T22:42:29Z"
    mac: ENC[AES256_GCM,data:nKZy9xFzjZJ6y+hv+kPUwzYdWF+WGy+nMcd725KjDOe60tE5QssVdhBlF50TpGoJrA6dfRxslVWEyfnEbUH0LaLbX164UDeGUPBxxjaTg2cWZgTJSfuVUqzEpLPBZDD5QLL4Ydr5CmTl6NZfsAm9f6qJHD7SF2r/PCR5CnkR/t8=,iv:BoVfuDKMG71kGQGcjivW6Nb/A6BdDhYdYrwfmUq/M34=,tag:pvyvcrswp14tLABlUsD1Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:WJ8dR6mZjuI=,iv:ej6IVutWriGV+PuZWugyYHcyD806aVDQGCRHKz337Cc=,tag:u9Lx2HzhjuQGEGXkaPYl6g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:grvjJWEb07NrZt0=,iv:ZpxzMAdh5eMGsjGmy4ippEgDo8D4nkbvcUyLwigHL9g=,tag:V1RihFiSYZm6aL/Vmps3mw==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:MQovZytuSzxCp8dMCJTxnYIOwzQ=,iv:YJjUIF7paBvvuwdSQIApkZWJZI8/MNMR8ZBZQnOHesI=,tag:ykVByQwFVux8bVog8kVj9g==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sgDLPILc1SxAMQZ72SPE2x9+Y/r/o+t+Z6p3Akyhs0xOr8cUUYX1fQ==,iv:cfEZOp/ZeGuF6Jsjbh9VY0nUVPbNF/xRBjokSzQh0ZM=,tag:KxS1e+7d/FzJFss4a4PW7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZmpyZmdQU25UZDF5S054
            SEJNdlV5ZlQzVUN2NkFDQ01LWnBubVg0TzIwCjRoemtyb3N2SGlab214Z3A5OGc2
            VDFxU2ZzMlVvQXQ0ZTdGU3pzYUZrbHMKLS0tIFp6SEtSd0ZIakI1dlFHcHp3SEw2
            ZmZyZWZ1V0lFYS92WUxlTlRWeGg4WWcKe+y2mSGsln9qOXxGQdCZM9IX2FGWtxYR
            /MSQddNjC5myRAQpqtWoHzO9I5bJvUGH15F9EuD3QCdWtfC9n8LyGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T22:42:29Z"
    mac: ENC[AES256_GCM,data:nKZy9xFzjZJ6y+hv+kPUwzYdWF+WGy+nMcd725KjDOe60tE5QssVdhBlF50TpGoJrA6dfRxslVWEyfnEbUH0LaLbX164UDeGUPBxxjaTg2cWZgTJSfuVUqzEpLPBZDD5QLL4Ydr5CmTl6NZfsAm9f6qJHD7SF2r/PCR5CnkR/t8=,iv:BoVfuDKMG71kGQGcjivW6Nb/A6BdDhYdYrwfmUq/M34=,tag:pvyvcrswp14tLABlUsD1Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:f5tCv0UZ,iv:DMwWRaGArZuJp02AffVeof6X15NRu5O0LP8LmZI26qE=,tag:IwTlPvAPvwkPZspV7BfVZw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:bRg3qvCfECZxivo=,iv:bPpyrc5Af2T7uQUhF48FuFcO68p6ChUhmwNDUpqxP/E=,tag:9ztiqRHlCTLCRSzOgcPf5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZmpyZmdQU25UZDF5S054
            SEJNdlV5ZlQzVUN2NkFDQ01LWnBubVg0TzIwCjRoemtyb3N2SGlab214Z3A5OGc2
            VDFxU2ZzMlVvQXQ0ZTdGU3pzYUZrbHMKLS0tIFp6SEtSd0ZIakI1dlFHcHp3SEw2
            ZmZyZWZ1V0lFYS92WUxlTlRWeGg4WWcKe+y2mSGsln9qOXxGQdCZM9IX2FGWtxYR
            /MSQddNjC5myRAQpqtWoHzO9I5bJvUGH15F9EuD3QCdWtfC9n8LyGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T22:42:29Z"
    mac: ENC[AES256_GCM,data:nKZy9xFzjZJ6y+hv+kPUwzYdWF+WGy+nMcd725KjDOe60tE5QssVdhBlF50TpGoJrA6dfRxslVWEyfnEbUH0LaLbX164UDeGUPBxxjaTg2cWZgTJSfuVUqzEpLPBZDD5QLL4Ydr5CmTl6NZfsAm9f6qJHD7SF2r/PCR5CnkR/t8=,iv:BoVfuDKMG71kGQGcjivW6Nb/A6BdDhYdYrwfmUq/M34=,tag:pvyvcrswp14tLABlUsD1Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:4m+NHJ804RM=,iv:lFSWR9v1TTTFvln+E8DXrgrDys1ZbwoRA/DTPUoQMfQ=,tag:QgqVfXjKuc/IH4llEIalWw==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:h6SAAMNZGBb2Sa0=,iv:1yeST7PvHGhl8WQYQWSIisIYhYKZNgYyytsOJ2rjBLI=,tag:2EtLg3sO+/2KhsgVk13SAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZmpyZmdQU25UZDF5S054
            SEJNdlV5ZlQzVUN2NkFDQ01LWnBubVg0TzIwCjRoemtyb3N2SGlab214Z3A5OGc2
            VDFxU2ZzMlVvQXQ0ZTdGU3pzYUZrbHMKLS0tIFp6SEtSd0ZIakI1dlFHcHp3SEw2
            ZmZyZWZ1V0lFYS92WUxlTlRWeGg4WWcKe+y2mSGsln9qOXxGQdCZM9IX2FGWtxYR
            /MSQddNjC5myRAQpqtWoHzO9I5bJvUGH15F9EuD3QCdWtfC9n8LyGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T22:42:29Z"
    mac: ENC[AES256_GCM,data:nKZy9xFzjZJ6y+hv+kPUwzYdWF+WGy+nMcd725KjDOe60tE5QssVdhBlF50TpGoJrA6dfRxslVWEyfnEbUH0LaLbX164UDeGUPBxxjaTg2cWZgTJSfuVUqzEpLPBZDD5QLL4Ydr5CmTl6NZfsAm9f6qJHD7SF2r/PCR5CnkR/t8=,iv:BoVfuDKMG71kGQGcjivW6Nb/A6BdDhYdYrwfmUq/M34=,tag:pvyvcrswp14tLABlUsD1Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
