apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:XOlz6XlknjPGm34uUO4kofFcGD+nGLfb6iANdqNNFTxaZTfe7JKPMzWepRFEtT+7srXzLAeHyi17w6VxE19awEwpafMJRgm+1NCOikBJJrHtdXoyf5DoJw==,iv:e+l76s68jECp+3oHAhatv2VK7fkVXngPXRSUWWn+t4Y=,tag:7T6pXcNHRhg++sN/Ob3rFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SU1qVFZPRnorSGozTHFD
            UGFDazM0eW1XNGJYOUNoSVpsUkVQNmZVaTFVCklMbWp5RHNzTE1qNVF0WTBRUndO
            VEU5bjREN1NUR25neUQ1M0xTc0lNR1kKLS0tIC9SR1JoQTdEa3hlNWNwejFxdFRO
            NkdwUFN0a2dyV2VxMWczMHN6R3lDS0UKnzRyx6TPO+2e/DJ2hjrXWc7nIIMR3a08
            g4ytW2JdwwN0ZzI6moN/NFwrZ0jl4K2qHVQX57Hy/r1geeVJmgKP/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T07:22:03Z"
    mac: ENC[AES256_GCM,data:onfA/02kUYcyR+FqkiUwEF72BCRUpu7ibE+Us2uowpaeFMGmfvfmadXAd8eaeSy83P0R/ZSfNXNsKP5XgT7UKKV4v4D+O4KlOrJW9G+H9l/wQiVKJbM9r8H/3RXbvkaG1giaDd+7GKFI62Ts981fLFv5oNAOZ9UKTXxqCpvPUWY=,iv:Xps7Y2v4jZxvafB4URTfWesYK0My1MWjlkvtJDoO284=,tag:DLG2YN7TlEucVbxuuOqqVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Al9VGruyALmOPDM=,iv:Dq9cHCPSUxJ7lJ2gATLPRz+UWAQBeVpI/qgQ/lzkBX0=,tag:xPgmkcBJIXyc1Oej6+hr4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SU1qVFZPRnorSGozTHFD
            UGFDazM0eW1XNGJYOUNoSVpsUkVQNmZVaTFVCklMbWp5RHNzTE1qNVF0WTBRUndO
            VEU5bjREN1NUR25neUQ1M0xTc0lNR1kKLS0tIC9SR1JoQTdEa3hlNWNwejFxdFRO
            NkdwUFN0a2dyV2VxMWczMHN6R3lDS0UKnzRyx6TPO+2e/DJ2hjrXWc7nIIMR3a08
            g4ytW2JdwwN0ZzI6moN/NFwrZ0jl4K2qHVQX57Hy/r1geeVJmgKP/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T07:22:03Z"
    mac: ENC[AES256_GCM,data:onfA/02kUYcyR+FqkiUwEF72BCRUpu7ibE+Us2uowpaeFMGmfvfmadXAd8eaeSy83P0R/ZSfNXNsKP5XgT7UKKV4v4D+O4KlOrJW9G+H9l/wQiVKJbM9r8H/3RXbvkaG1giaDd+7GKFI62Ts981fLFv5oNAOZ9UKTXxqCpvPUWY=,iv:Xps7Y2v4jZxvafB4URTfWesYK0My1MWjlkvtJDoO284=,tag:DLG2YN7TlEucVbxuuOqqVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:szajUD07FR0=,iv:R08bfupfX11htxFxOruVLdtv6XdnuXtmZErLdfd6J4E=,tag:nsy6+gwxCNZlLKbHO1txZw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WHgWH9ExkWX8/E0=,iv:ebbRApEljfSGcMSLrQ/Vm0D9rnO2vbQf8vp68fXOM3M=,tag:Eodux4SrbqIZNWHcng4qNA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:20mCOLNJG0g0q8DnECfiizZDqJY=,iv:B21IgC7xpXJmOlLW7l3+hnIdoY51r9XirG8bpQugO9s=,tag:ZJtJkJft9rl4+4nihYTeTw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+71zRoUI+HhPP7nnY1ePpoFMPscQ6kpuEO13Rrv/e8mFHWiqblakTg==,iv:ty9j7rtM7RBn/9V+/teL4TljZWYWTBc1oqC32qgBlS4=,tag:7v2Ih+UCin3ZPVmWvmb+8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SU1qVFZPRnorSGozTHFD
            UGFDazM0eW1XNGJYOUNoSVpsUkVQNmZVaTFVCklMbWp5RHNzTE1qNVF0WTBRUndO
            VEU5bjREN1NUR25neUQ1M0xTc0lNR1kKLS0tIC9SR1JoQTdEa3hlNWNwejFxdFRO
            NkdwUFN0a2dyV2VxMWczMHN6R3lDS0UKnzRyx6TPO+2e/DJ2hjrXWc7nIIMR3a08
            g4ytW2JdwwN0ZzI6moN/NFwrZ0jl4K2qHVQX57Hy/r1geeVJmgKP/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T07:22:03Z"
    mac: ENC[AES256_GCM,data:onfA/02kUYcyR+FqkiUwEF72BCRUpu7ibE+Us2uowpaeFMGmfvfmadXAd8eaeSy83P0R/ZSfNXNsKP5XgT7UKKV4v4D+O4KlOrJW9G+H9l/wQiVKJbM9r8H/3RXbvkaG1giaDd+7GKFI62Ts981fLFv5oNAOZ9UKTXxqCpvPUWY=,iv:Xps7Y2v4jZxvafB4URTfWesYK0My1MWjlkvtJDoO284=,tag:DLG2YN7TlEucVbxuuOqqVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
