apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:VkODgry/Nd3hLlroj9zxGFkdPGLMLE30Gss5VMLAEoAxboQ04Cu6j+zd1d2mZLnT0f3788IxDYDIiIS/BP7sVHsK1mjPEtmFXlGASsS4OL2h1L2SCnKB8Q==,iv:5Ix4uk1XTlv+i1O7gxU/XE18c9G4GkH/QlzbwVqMoHw=,tag:N7P+UOEt/EdVvaTeCpq4VA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-27T19:11:19Z"
    mac: ENC[AES256_GCM,data:lXUsv0zp2VGI9YZ/kiTTZE6IZUmeHE4+FEoaBBm4Dy5gFpEYZ0Vq/aVygqzTNtEAEOo4OTjtPNi1YdfsHRxLrmiGiFyzSoecaJrSxWS93VJzr6u2/rZEdzj7qeJNXyLDQP49gNfa6HnD0i0M0l+NDiOVFvaDgq/4bs+B0lWuOMA=,iv:QApmZMoYbBdQybTUO7dPucgAbNSV79EdwQe3/4a6ESg=,tag:oasnVC+OJa7ipLRKWKwbWA==,type:str]
    pgp:
        - created_at: "2025-01-27T19:11:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5oXQ7yzM65bAQ//U8ticEtE05YSAkgviXcT9f8OYzwGWlz6KE4sYi5xdpiF
            iGU/Rm8ahJZPAts98aD2qgJA5I6bg4688Hr0vhM+Z8ePqBUnA4kWt6gqGU47Fm7h
            v9qrW2UmQXStjxo5km9iH6oab5zkVx6CRqb/RzLY8TNjw15k1JoTvgSIJ6UZ0zJf
            xt16DfVWxzidnEAn6mWLaHdu/LcegbCerHnFLiGAvzwPjg1xpfpyq9rbXUe0zzuj
            ftiV+NfjmbqDu0pQAGJk790ih7Z5ONdgxOJoEkUOr3JZj0rC60XWlpHv8o+B6r23
            Q6ZvJzLffCRfoelF6qyyhUhqLtF9fDHt9dgeh0IQOswWNPsoMOe2ynN+UTRkFl4Z
            4fBfUr0vqkpydTlKal/FcCMo9t+34FPEwAtYY3b+JswJiyme/ehBaw6uR5Ka31D9
            Hg8e+M/GECd8Dl2KmXFs3bA4BTIMHxjpr3tHMBovuIAtiRLwx9I8i2MBcJWRhGme
            r4rp2V4a1ESG73fNB59UHR6mz9dvmxHaxMuXSlEVVo5ebTXQHtiyh6G2O7PAGCvr
            qyyvKZX4cV2yI/zn2RgQVksJXFFGxzA2tx4PW9XJSvb6efRovvdlWztXHR0nFegO
            dk45bBow1YicUFyzMl5d5gpL9U9U66XMLedU0PMSLwazbG0++LEzA/d0R9Dt8n7U
            aAEJAhAz+0D5QQcGjQTNaLjWymecbkVu1R4Q7oD5aog5sQP5Ud8NLCmxyvHWSxmX
            B0TUNVKFPw+1lzNrcjoqcI9YCd1EW0jPrrawiWbVCBc5VyD1XFBbAesOBt3iJlyE
            eVBZGlxUCye7
            =kNC/
            -----END PGP MESSAGE-----
          fp: 1049D3246DF059C2C8F54D289A1743BCB333AE5B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
