apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:KI9UGoEda4xU+39F0zomsbbL3hR7SLhUm4DmWZppEsitOHPQe4k2mVmPyEjdYs21lPdyPHK62whbI5yi8JFBBaazVlp4VR6cNy7PrUMGsec69Mfwi8RNGw==,iv:66nep+QiGGpcU5jVv2QzTpK2Uc3s4c336/OmVXecabk=,tag:iYIkkp37hJtjtvfWLblg/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WHJiblphS1FKTUJOcmUx
            emhHZW1kVmRtUk15anVaTmhJRGdYWSsvd1EwCjZYMGlGRjlCLzlCOWRnZ09sQ2lh
            VEpIVW1LMWp6Vk5TRjVwTmFsSmIxTFkKLS0tIHhZeDdaajM3eTRHZ3h2YkRPZUQx
            RDJPcHNPeTd6S0NsRHVaS1FwN1c0VGMKwDaEISNb5+LHvbF82lFN3KzP8kPJSHof
            FrfcanApA8xqp88te1m0pNgVefGvz2X6FxVYuQujHH3Q4301levorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:58:42Z"
    mac: ENC[AES256_GCM,data:6lEyeI1dO3jjfu1r6mmbz5urotiuC+ejOSws4wS/BuUX3zGsvaj31OXoo9gUjb7peMI1iwG2+9DoAA8kNcd+7XhQ8GdxPynsuHWJMi65BykldQZCBhF8wyTgjBn40W+ajIBrFQ/sAKF3SssM5zZtu6l0J6UU8Kk1ltH1k39Wkbc=,iv:OBJ0Mpn2qVAsK33UAwfEcXS0+Nv8GBDWx/uRX9/We2I=,tag:KUKa45AeqKNJbIkH5Rjprw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: keycloak
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:DwXCX/P1MMUGQJ4=,iv:/3en9hoJzATgj/ayiIFHS6JgpclOocmsdI9At0MyfTA=,tag:UpSOdhzlpvubdG7iL1vEsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WHJiblphS1FKTUJOcmUx
            emhHZW1kVmRtUk15anVaTmhJRGdYWSsvd1EwCjZYMGlGRjlCLzlCOWRnZ09sQ2lh
            VEpIVW1LMWp6Vk5TRjVwTmFsSmIxTFkKLS0tIHhZeDdaajM3eTRHZ3h2YkRPZUQx
            RDJPcHNPeTd6S0NsRHVaS1FwN1c0VGMKwDaEISNb5+LHvbF82lFN3KzP8kPJSHof
            FrfcanApA8xqp88te1m0pNgVefGvz2X6FxVYuQujHH3Q4301levorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:58:42Z"
    mac: ENC[AES256_GCM,data:6lEyeI1dO3jjfu1r6mmbz5urotiuC+ejOSws4wS/BuUX3zGsvaj31OXoo9gUjb7peMI1iwG2+9DoAA8kNcd+7XhQ8GdxPynsuHWJMi65BykldQZCBhF8wyTgjBn40W+ajIBrFQ/sAKF3SssM5zZtu6l0J6UU8Kk1ltH1k39Wkbc=,iv:OBJ0Mpn2qVAsK33UAwfEcXS0+Nv8GBDWx/uRX9/We2I=,tag:KUKa45AeqKNJbIkH5Rjprw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:HkgG++RIv84=,iv:z2weSGjmji3/tIyZgB/oeDUdOcqM1qLZoMZq+alPe+c=,tag:Xuj4VI5zO+NaOrSsVDuHbQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3cBvExgCgC5PLec=,iv:DBoB0DiUj06Bu8TZmHF1ELBvI0o0RycEJDqZQkhTgeY=,tag:e/LXiN/1BEE6YUSH0LcAeg==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:QmpUDNCN/2qNPaoJtrAXx1fbmpI=,iv:rfbp/qAQU3/nwd/e7uNYTkl573Qd2whGTW2p98g+K6w=,tag:VF4ldDa9ZI1ulrzDdhqufw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:YQLxP9i5WnWENldbZxLTjc1+fgwHyxQjJ3E4ZXjITpKy6iD2Q+cz1g==,iv:e2pqezCOF03SfBkUFNwR4azQwfmggzDdzgnOjdxGv+A=,tag:4F6+n7/A/j7HhPWizgmJwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WHJiblphS1FKTUJOcmUx
            emhHZW1kVmRtUk15anVaTmhJRGdYWSsvd1EwCjZYMGlGRjlCLzlCOWRnZ09sQ2lh
            VEpIVW1LMWp6Vk5TRjVwTmFsSmIxTFkKLS0tIHhZeDdaajM3eTRHZ3h2YkRPZUQx
            RDJPcHNPeTd6S0NsRHVaS1FwN1c0VGMKwDaEISNb5+LHvbF82lFN3KzP8kPJSHof
            FrfcanApA8xqp88te1m0pNgVefGvz2X6FxVYuQujHH3Q4301levorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:58:42Z"
    mac: ENC[AES256_GCM,data:6lEyeI1dO3jjfu1r6mmbz5urotiuC+ejOSws4wS/BuUX3zGsvaj31OXoo9gUjb7peMI1iwG2+9DoAA8kNcd+7XhQ8GdxPynsuHWJMi65BykldQZCBhF8wyTgjBn40W+ajIBrFQ/sAKF3SssM5zZtu6l0J6UU8Kk1ltH1k39Wkbc=,iv:OBJ0Mpn2qVAsK33UAwfEcXS0+Nv8GBDWx/uRX9/We2I=,tag:KUKa45AeqKNJbIkH5Rjprw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:vt7K/til,iv:/3ZzC+XYff5y772Rc5YsOx1IcVbx0Wd4xlWEWG3FG94=,tag:fdA86snpDltavmKX5ORaZA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:OzWutrneUVB3ASY=,iv:7yVStsc5LqYxuFZn8JtSsG9DQAljTlYeOyC94sy1Z30=,tag:+6guFR1QXLiNZAWN+IPA2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WHJiblphS1FKTUJOcmUx
            emhHZW1kVmRtUk15anVaTmhJRGdYWSsvd1EwCjZYMGlGRjlCLzlCOWRnZ09sQ2lh
            VEpIVW1LMWp6Vk5TRjVwTmFsSmIxTFkKLS0tIHhZeDdaajM3eTRHZ3h2YkRPZUQx
            RDJPcHNPeTd6S0NsRHVaS1FwN1c0VGMKwDaEISNb5+LHvbF82lFN3KzP8kPJSHof
            FrfcanApA8xqp88te1m0pNgVefGvz2X6FxVYuQujHH3Q4301levorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:58:42Z"
    mac: ENC[AES256_GCM,data:6lEyeI1dO3jjfu1r6mmbz5urotiuC+ejOSws4wS/BuUX3zGsvaj31OXoo9gUjb7peMI1iwG2+9DoAA8kNcd+7XhQ8GdxPynsuHWJMi65BykldQZCBhF8wyTgjBn40W+ajIBrFQ/sAKF3SssM5zZtu6l0J6UU8Kk1ltH1k39Wkbc=,iv:OBJ0Mpn2qVAsK33UAwfEcXS0+Nv8GBDWx/uRX9/We2I=,tag:KUKa45AeqKNJbIkH5Rjprw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:ctpeWJDE6BQ=,iv:AHyRdEKdVhDHvx3ZXJmvSDvq06Pr/BL3tn2OdLfTe70=,tag:pkZRn3ZT2RrlMH/AkZ2PfQ==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:0v1Xxf2zgwCUyRs=,iv:wMsMLhWIO1bAB6YjYRb8msR2SpfkQlkiFg88Gz/4fAA=,tag:ncLQXirIwC0opyeeVj9Vdg==,type:str]
    PASSPHRASE: ENC[AES256_GCM,data:s7JJONMqHcX7KbCtbJyUldoURSKeOgxprHTwGXiT/l3uUQ==,iv:7AS6xZ4ingKKPUeyAas/Qnd7eWCTklRlebVMUPK2KJA=,tag:wFgmaeasGgPApmjHfwIy3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WHJiblphS1FKTUJOcmUx
            emhHZW1kVmRtUk15anVaTmhJRGdYWSsvd1EwCjZYMGlGRjlCLzlCOWRnZ09sQ2lh
            VEpIVW1LMWp6Vk5TRjVwTmFsSmIxTFkKLS0tIHhZeDdaajM3eTRHZ3h2YkRPZUQx
            RDJPcHNPeTd6S0NsRHVaS1FwN1c0VGMKwDaEISNb5+LHvbF82lFN3KzP8kPJSHof
            FrfcanApA8xqp88te1m0pNgVefGvz2X6FxVYuQujHH3Q4301levorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:58:42Z"
    mac: ENC[AES256_GCM,data:6lEyeI1dO3jjfu1r6mmbz5urotiuC+ejOSws4wS/BuUX3zGsvaj31OXoo9gUjb7peMI1iwG2+9DoAA8kNcd+7XhQ8GdxPynsuHWJMi65BykldQZCBhF8wyTgjBn40W+ajIBrFQ/sAKF3SssM5zZtu6l0J6UU8Kk1ltH1k39Wkbc=,iv:OBJ0Mpn2qVAsK33UAwfEcXS0+Nv8GBDWx/uRX9/We2I=,tag:KUKa45AeqKNJbIkH5Rjprw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: product-feedback,dopamine-kick
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:4TCyb1GoeIDjBiDw,iv:2IjXBDL437dLr+XkBIrdXHd74I9dq8H+kM511OmC+MQ=,tag:5ciuRd69IUS04m6HztmHBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WHJiblphS1FKTUJOcmUx
            emhHZW1kVmRtUk15anVaTmhJRGdYWSsvd1EwCjZYMGlGRjlCLzlCOWRnZ09sQ2lh
            VEpIVW1LMWp6Vk5TRjVwTmFsSmIxTFkKLS0tIHhZeDdaajM3eTRHZ3h2YkRPZUQx
            RDJPcHNPeTd6S0NsRHVaS1FwN1c0VGMKwDaEISNb5+LHvbF82lFN3KzP8kPJSHof
            FrfcanApA8xqp88te1m0pNgVefGvz2X6FxVYuQujHH3Q4301levorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:58:42Z"
    mac: ENC[AES256_GCM,data:6lEyeI1dO3jjfu1r6mmbz5urotiuC+ejOSws4wS/BuUX3zGsvaj31OXoo9gUjb7peMI1iwG2+9DoAA8kNcd+7XhQ8GdxPynsuHWJMi65BykldQZCBhF8wyTgjBn40W+ajIBrFQ/sAKF3SssM5zZtu6l0J6UU8Kk1ltH1k39Wkbc=,iv:OBJ0Mpn2qVAsK33UAwfEcXS0+Nv8GBDWx/uRX9/We2I=,tag:KUKa45AeqKNJbIkH5Rjprw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_DB_USERNAME: ENC[AES256_GCM,data:vZWYkwLS7l4=,iv:MlRNkrExhplPJukwKh0kMKcUnBhJrne85xh8xOnTBp8=,tag:D76YndMBmks1TvPZOh9LgQ==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:zzuepu0Clds1tDHbQLxRToIEWzg=,iv:uy29PanH7hCFr3ArXHf/eiLD0vDi7dlcXB4xg9bwYJg=,tag:RYrleuNH3b+1Yb9HH+oAIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WHJiblphS1FKTUJOcmUx
            emhHZW1kVmRtUk15anVaTmhJRGdYWSsvd1EwCjZYMGlGRjlCLzlCOWRnZ09sQ2lh
            VEpIVW1LMWp6Vk5TRjVwTmFsSmIxTFkKLS0tIHhZeDdaajM3eTRHZ3h2YkRPZUQx
            RDJPcHNPeTd6S0NsRHVaS1FwN1c0VGMKwDaEISNb5+LHvbF82lFN3KzP8kPJSHof
            FrfcanApA8xqp88te1m0pNgVefGvz2X6FxVYuQujHH3Q4301levorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:58:42Z"
    mac: ENC[AES256_GCM,data:6lEyeI1dO3jjfu1r6mmbz5urotiuC+ejOSws4wS/BuUX3zGsvaj31OXoo9gUjb7peMI1iwG2+9DoAA8kNcd+7XhQ8GdxPynsuHWJMi65BykldQZCBhF8wyTgjBn40W+ajIBrFQ/sAKF3SssM5zZtu6l0J6UU8Kk1ltH1k39Wkbc=,iv:OBJ0Mpn2qVAsK33UAwfEcXS0+Nv8GBDWx/uRX9/We2I=,tag:KUKa45AeqKNJbIkH5Rjprw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:z7qEu4c=,iv:60YdyFk8i9R7I42J67DuBlWacbLsk/x+04tGj0YYSm0=,tag:UBpXWJtdUG+w1XyP0KMnEw==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:+xtvmJqeOfNo94IXgDdmpKfGMuA=,iv:OwZg/ueZoRqhYoKeTvtr1PBnZWLxHkyTbGBPratxjn4=,tag:jRQ6iEaCpPtfDFXhQLKNQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WHJiblphS1FKTUJOcmUx
            emhHZW1kVmRtUk15anVaTmhJRGdYWSsvd1EwCjZYMGlGRjlCLzlCOWRnZ09sQ2lh
            VEpIVW1LMWp6Vk5TRjVwTmFsSmIxTFkKLS0tIHhZeDdaajM3eTRHZ3h2YkRPZUQx
            RDJPcHNPeTd6S0NsRHVaS1FwN1c0VGMKwDaEISNb5+LHvbF82lFN3KzP8kPJSHof
            FrfcanApA8xqp88te1m0pNgVefGvz2X6FxVYuQujHH3Q4301levorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:58:42Z"
    mac: ENC[AES256_GCM,data:6lEyeI1dO3jjfu1r6mmbz5urotiuC+ejOSws4wS/BuUX3zGsvaj31OXoo9gUjb7peMI1iwG2+9DoAA8kNcd+7XhQ8GdxPynsuHWJMi65BykldQZCBhF8wyTgjBn40W+ajIBrFQ/sAKF3SssM5zZtu6l0J6UU8Kk1ltH1k39Wkbc=,iv:OBJ0Mpn2qVAsK33UAwfEcXS0+Nv8GBDWx/uRX9/We2I=,tag:KUKa45AeqKNJbIkH5Rjprw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: seaweedfs
type: Opaque
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:GIIdizVXVtvrQrwoZW+mFhivfqV43NRigx0dqYl1SYFRmg+3aqaq/yonym+SOyLUUFTibPCoBfPZpcAwbo4hW5e6w3IjW1iaD+mwxTxtP7PdsUhr3bQtsGRaOrReNxr9XJROKx6ncUVmdkxNWMnMOqchiSMqqpovAOSEGvHcrLDA11uI5Vr4Tl9u+esME9/wR3xLoA3UlTQFz4AVuRKlYVpKnyaq+7nAEGvdw/SjXG5cjCzGzb3+k3v5lwfoIoJTk4usQ5NT3nAzcbi8J/TpHriTCo+KpOFNBjgWfFD5BeH4AcmgXwyh5dEykath0VyA4lIc4zp+sdAuIz+JEkY7RSpynqQyILQelJWGeOfOnanhzxyaZImLB9soxs2uxKdcGE83qy3R3fNjiuZggXVdEpw6pyuOhPn8/9v4BztYHtZBLMz1F10FZHSG2IpXUctTFQ==,iv:MK836bjdATLvAEn6N6q5FUYAO07jJ72xSUTW351tMgU=,tag:1YNFYpPm/gG4mUrPmi1yuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WHJiblphS1FKTUJOcmUx
            emhHZW1kVmRtUk15anVaTmhJRGdYWSsvd1EwCjZYMGlGRjlCLzlCOWRnZ09sQ2lh
            VEpIVW1LMWp6Vk5TRjVwTmFsSmIxTFkKLS0tIHhZeDdaajM3eTRHZ3h2YkRPZUQx
            RDJPcHNPeTd6S0NsRHVaS1FwN1c0VGMKwDaEISNb5+LHvbF82lFN3KzP8kPJSHof
            FrfcanApA8xqp88te1m0pNgVefGvz2X6FxVYuQujHH3Q4301levorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:58:42Z"
    mac: ENC[AES256_GCM,data:6lEyeI1dO3jjfu1r6mmbz5urotiuC+ejOSws4wS/BuUX3zGsvaj31OXoo9gUjb7peMI1iwG2+9DoAA8kNcd+7XhQ8GdxPynsuHWJMi65BykldQZCBhF8wyTgjBn40W+ajIBrFQ/sAKF3SssM5zZtu6l0J6UU8Kk1ltH1k39Wkbc=,iv:OBJ0Mpn2qVAsK33UAwfEcXS0+Nv8GBDWx/uRX9/We2I=,tag:KUKa45AeqKNJbIkH5Rjprw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-auth
    namespace: product-feedback
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: dopamine-kick
type: Opaque
stringData:
    CLIENT_SECRET: ENC[AES256_GCM,data:xjwc3Mp0rNo0CyQP3o2cgudSijPOOKZrlDLS2pUQFdU=,iv:c8BRINi5VeTt2bPTD88geN/+1A57HkesPQ7uon6EjTM=,tag:fm/f71ioFzosiaStJmHpeA==,type:str]
    ADMIN_CLIENT_SECRET: ENC[AES256_GCM,data:oMMHW6tNfqI3qeP67XC5lCiUiYN0dn0A0C7tOfXDkuc=,iv:jTAsiu+uJx8V+N1Wo9JqQnkdrDyyzvlMNMThjQPc7eM=,tag:tvAt+TVXt1Uhs2nXUI9BZA==,type:str]
    DOPAMINE_KICK_CLIENT_SECRET: ENC[AES256_GCM,data:t5eJm/xjxicd7YnHGJm8UTL5WSPQpweOk7xYBKd3JSY=,iv:733ZJ5aLNOt5Vaaj4htnKdKugzlsy+azYZxZteyh4M0=,tag:6MIk4sntMMdFycMSqf99Gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WHJiblphS1FKTUJOcmUx
            emhHZW1kVmRtUk15anVaTmhJRGdYWSsvd1EwCjZYMGlGRjlCLzlCOWRnZ09sQ2lh
            VEpIVW1LMWp6Vk5TRjVwTmFsSmIxTFkKLS0tIHhZeDdaajM3eTRHZ3h2YkRPZUQx
            RDJPcHNPeTd6S0NsRHVaS1FwN1c0VGMKwDaEISNb5+LHvbF82lFN3KzP8kPJSHof
            FrfcanApA8xqp88te1m0pNgVefGvz2X6FxVYuQujHH3Q4301levorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:58:42Z"
    mac: ENC[AES256_GCM,data:6lEyeI1dO3jjfu1r6mmbz5urotiuC+ejOSws4wS/BuUX3zGsvaj31OXoo9gUjb7peMI1iwG2+9DoAA8kNcd+7XhQ8GdxPynsuHWJMi65BykldQZCBhF8wyTgjBn40W+ajIBrFQ/sAKF3SssM5zZtu6l0J6UU8Kk1ltH1k39Wkbc=,iv:OBJ0Mpn2qVAsK33UAwfEcXS0+Nv8GBDWx/uRX9/We2I=,tag:KUKa45AeqKNJbIkH5Rjprw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: blobstorage-auth
    namespace: product-feedback
type: Opaque
stringData:
    BLOB_ACCESS_KEY: ENC[AES256_GCM,data:ROV7iEFGSLT4FE0k,iv:gENUqqNcTmtmWEuUt8kdXgQFeCOoOJlXZvGtL21GeE8=,tag:8sPraF3Dek76u7pbjI0rAQ==,type:str]
    BLOB_SECRET_KEY: ENC[AES256_GCM,data:+O6ehRo6TJEMSSfl,iv:f+0kFj9xGTZ2efLMFXDBcrLMi0fifGfUIWn8g0YWn8s=,tag:1nB9CnqS6cDEnJcTKqQmag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WHJiblphS1FKTUJOcmUx
            emhHZW1kVmRtUk15anVaTmhJRGdYWSsvd1EwCjZYMGlGRjlCLzlCOWRnZ09sQ2lh
            VEpIVW1LMWp6Vk5TRjVwTmFsSmIxTFkKLS0tIHhZeDdaajM3eTRHZ3h2YkRPZUQx
            RDJPcHNPeTd6S0NsRHVaS1FwN1c0VGMKwDaEISNb5+LHvbF82lFN3KzP8kPJSHof
            FrfcanApA8xqp88te1m0pNgVefGvz2X6FxVYuQujHH3Q4301levorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:58:42Z"
    mac: ENC[AES256_GCM,data:6lEyeI1dO3jjfu1r6mmbz5urotiuC+ejOSws4wS/BuUX3zGsvaj31OXoo9gUjb7peMI1iwG2+9DoAA8kNcd+7XhQ8GdxPynsuHWJMi65BykldQZCBhF8wyTgjBn40W+ajIBrFQ/sAKF3SssM5zZtu6l0J6UU8Kk1ltH1k39Wkbc=,iv:OBJ0Mpn2qVAsK33UAwfEcXS0+Nv8GBDWx/uRX9/We2I=,tag:KUKa45AeqKNJbIkH5Rjprw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
