apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:R6ZlqPtynMV/gNGQvm45Nf1fM4hTALjoPe5HQ9jBTksPsAo65OdoI3uM6Gjz3RMtilbnN9zElw+HX8CBBx8lyxFkS2B26eHAxb8oM5cYqv/w1sWrI15QoQ==,iv:C+Car8CpiFqYM26fBSwpWLQ6vVF3L8ceqs+xucIlSDo=,tag:bTxbHCwrzkXL4Rve+ZaIqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSXIzR3o1bFBHVkprdXZx
            YXRqaDZRZnZ5aEJpRnE1dzNRMGRIYWtidEdVCisyYlRoY04rVnpYRFRMSTV1SkNB
            Y2I3V1JxeDBmTEdHemdvcklhK2JNTk0KLS0tIFNTUjIwOWJJZjJWOFRsMnpEdHRS
            S0F1NWlUN2FQQjBJTWdpSTdkeDlENDQKIYo10OG0pmVxMcVIwkfi9U/WgPB9CrCT
            CZhzdXEI6v/fP5xBeFafT0uQfe535diCD2vXGO/LVCjj3IeLrp0BLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T22:38:08Z"
    mac: ENC[AES256_GCM,data:YinQMK/8Z+J9UxGYMUOS8yHwMwqKdjPEL2lHMjYx0PhQ71VTl1aJVp6hN3sHqCSAMlfrrU4w9H82CejWWbeo9xbDru+pZ+h/wPgrwwWAnTZKs0uupOXpEY7vgOzrT8ZkgoTxUwpK0AEX81jLjufQ9FOlbBfZNlRDnLoqNd2E1ao=,iv:iYCs1bX9/29xXQ0wnO8i5kvyrlOBzE4ANH1xp49tqoA=,tag:wZFhamIPYVuIN0eb+47JwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:fA74N1Okfh6RPSw=,iv:fhMD+SYLljYTuyVYxvGPZA65ACja1jM5JsdrD7eiBgg=,tag:8xTsNe2bqzEa9yTdy66UJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSXIzR3o1bFBHVkprdXZx
            YXRqaDZRZnZ5aEJpRnE1dzNRMGRIYWtidEdVCisyYlRoY04rVnpYRFRMSTV1SkNB
            Y2I3V1JxeDBmTEdHemdvcklhK2JNTk0KLS0tIFNTUjIwOWJJZjJWOFRsMnpEdHRS
            S0F1NWlUN2FQQjBJTWdpSTdkeDlENDQKIYo10OG0pmVxMcVIwkfi9U/WgPB9CrCT
            CZhzdXEI6v/fP5xBeFafT0uQfe535diCD2vXGO/LVCjj3IeLrp0BLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T22:38:08Z"
    mac: ENC[AES256_GCM,data:YinQMK/8Z+J9UxGYMUOS8yHwMwqKdjPEL2lHMjYx0PhQ71VTl1aJVp6hN3sHqCSAMlfrrU4w9H82CejWWbeo9xbDru+pZ+h/wPgrwwWAnTZKs0uupOXpEY7vgOzrT8ZkgoTxUwpK0AEX81jLjufQ9FOlbBfZNlRDnLoqNd2E1ao=,iv:iYCs1bX9/29xXQ0wnO8i5kvyrlOBzE4ANH1xp49tqoA=,tag:wZFhamIPYVuIN0eb+47JwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:mEq7lEHlRcI=,iv:HK6NUjHgzRh7NxO23XRMbcGt1/0gtofwqffv9k+gGYY=,tag:0dXstW2eeVpAByRyKRwgzQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PP7aVAfrnoZTo7Y=,iv:vSoZZGKudLTr1ejKSkIscQ/WCEXO7HdYRUrEb6I7bwk=,tag:pJdmjLBqOAOPy/N9qqdfZg==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:9rzRAr0UrtZc+7NFz55LqqqX1oU=,iv:z3L3GMEqujysAOntHUeRvFppj1y2lavqnJLJs2mgYyI=,tag:9CrO2CsUIMA6INVy/3xG3g==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gOeTOKbTsgqg2Fe7d+asnFntsURaR8rw2YUD6Y3hkiyLv+iGMo3dKA==,iv:wla14icnkCx8OeEtPkguLIhpL9gC6EDosWG5sWsl4aE=,tag:43AK75Vl968xNHFb2GLBUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSXIzR3o1bFBHVkprdXZx
            YXRqaDZRZnZ5aEJpRnE1dzNRMGRIYWtidEdVCisyYlRoY04rVnpYRFRMSTV1SkNB
            Y2I3V1JxeDBmTEdHemdvcklhK2JNTk0KLS0tIFNTUjIwOWJJZjJWOFRsMnpEdHRS
            S0F1NWlUN2FQQjBJTWdpSTdkeDlENDQKIYo10OG0pmVxMcVIwkfi9U/WgPB9CrCT
            CZhzdXEI6v/fP5xBeFafT0uQfe535diCD2vXGO/LVCjj3IeLrp0BLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T22:38:08Z"
    mac: ENC[AES256_GCM,data:YinQMK/8Z+J9UxGYMUOS8yHwMwqKdjPEL2lHMjYx0PhQ71VTl1aJVp6hN3sHqCSAMlfrrU4w9H82CejWWbeo9xbDru+pZ+h/wPgrwwWAnTZKs0uupOXpEY7vgOzrT8ZkgoTxUwpK0AEX81jLjufQ9FOlbBfZNlRDnLoqNd2E1ao=,iv:iYCs1bX9/29xXQ0wnO8i5kvyrlOBzE4ANH1xp49tqoA=,tag:wZFhamIPYVuIN0eb+47JwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:vygunYleC60=,iv:IZzasqFR22FahwgxxtJ4ZgDW1FCA9VOBP/1TyO0Wjfc=,tag:XRfE32wprwEH+MUvX4LYfw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:bRx9Lt6vBWB1UUg=,iv:FOTUwnSiqEPQzo9xQlZ2vBZ2OTgFjfhT/n16VEb9BuQ=,tag:5gMlzlu56M9d8SVDClO+LA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSXIzR3o1bFBHVkprdXZx
            YXRqaDZRZnZ5aEJpRnE1dzNRMGRIYWtidEdVCisyYlRoY04rVnpYRFRMSTV1SkNB
            Y2I3V1JxeDBmTEdHemdvcklhK2JNTk0KLS0tIFNTUjIwOWJJZjJWOFRsMnpEdHRS
            S0F1NWlUN2FQQjBJTWdpSTdkeDlENDQKIYo10OG0pmVxMcVIwkfi9U/WgPB9CrCT
            CZhzdXEI6v/fP5xBeFafT0uQfe535diCD2vXGO/LVCjj3IeLrp0BLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T22:38:08Z"
    mac: ENC[AES256_GCM,data:YinQMK/8Z+J9UxGYMUOS8yHwMwqKdjPEL2lHMjYx0PhQ71VTl1aJVp6hN3sHqCSAMlfrrU4w9H82CejWWbeo9xbDru+pZ+h/wPgrwwWAnTZKs0uupOXpEY7vgOzrT8ZkgoTxUwpK0AEX81jLjufQ9FOlbBfZNlRDnLoqNd2E1ao=,iv:iYCs1bX9/29xXQ0wnO8i5kvyrlOBzE4ANH1xp49tqoA=,tag:wZFhamIPYVuIN0eb+47JwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
