apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:YN+Kyvifpn5PxT8cY58ftM77PgoZe3KHsZd8Y4bXFh9GGYLNanHnOGKbgzuoSQJaHj8eSrhspezP6WP1rl/Da3zh6biLbNUuPKrXgoop5oLouZFUVS07mA==,iv:j/ccrNgUjq3vFqE+xGOyFnLZw3OVHJoVi71wyG3DrMs=,tag:GaLI2bNuxJa6hxbeHAANzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NjJFekxSZ1MzRDZxNmt6
            YzIwenkra2JDNW1nL20vR04zNC9uOTAyc21zCjZtd1ZqbWVtWUdwNlg0M241RFVr
            K2RkUXMzQUpoRUxrNDZKd0lzRFMvQncKLS0tIG9rdHFMckxHNjdHbnYzT2lZaGc3
            Q2JBaDYvWlZIWTZCMHpGeGtBZUlXa28K2ahRRyTdNSizAbiIo6AJmtrRcZAIwfli
            q0lO2jrR9mNTcSAA0ZRQ2a3tJAJDdk+hG9MuuAHbGhSy43z2wUmaGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:52:12Z"
    mac: ENC[AES256_GCM,data:rctZVCznIuuSQJYEc4p9wehkeVtidLzDQ4cDdja5vFKwUBY6OG4TNRIvbklJVlwGCQQs1QTsqfGUmKdT3XpYPjflpuQK7p7iiy6o6QSXeDMw+F1G4n31arM48G+K1MJ5WJaEF2Mp4IDds/gskCCECua5nd6GCTeqCwWWEhuNcBk=,iv:3nsWNpdLoRS3N4mIqmrTOoeMPLj/rLt/s6XG0GkZyMQ=,tag:N933ahGJgYwrUbKd0GE0hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZF0mgA1EclYVDfQ=,iv:YJi3eOCjuJW+2g72z5RpDgM7bC3lv+/neDXLREp740o=,tag:HQ1+vOzZHJmsJsGGEPuNIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NjJFekxSZ1MzRDZxNmt6
            YzIwenkra2JDNW1nL20vR04zNC9uOTAyc21zCjZtd1ZqbWVtWUdwNlg0M241RFVr
            K2RkUXMzQUpoRUxrNDZKd0lzRFMvQncKLS0tIG9rdHFMckxHNjdHbnYzT2lZaGc3
            Q2JBaDYvWlZIWTZCMHpGeGtBZUlXa28K2ahRRyTdNSizAbiIo6AJmtrRcZAIwfli
            q0lO2jrR9mNTcSAA0ZRQ2a3tJAJDdk+hG9MuuAHbGhSy43z2wUmaGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:52:12Z"
    mac: ENC[AES256_GCM,data:rctZVCznIuuSQJYEc4p9wehkeVtidLzDQ4cDdja5vFKwUBY6OG4TNRIvbklJVlwGCQQs1QTsqfGUmKdT3XpYPjflpuQK7p7iiy6o6QSXeDMw+F1G4n31arM48G+K1MJ5WJaEF2Mp4IDds/gskCCECua5nd6GCTeqCwWWEhuNcBk=,iv:3nsWNpdLoRS3N4mIqmrTOoeMPLj/rLt/s6XG0GkZyMQ=,tag:N933ahGJgYwrUbKd0GE0hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:dC1Tr1/eCZg=,iv:hECZrqJlB/UVfURLRMFztJaTcth8p6kVz+qxXH4lo/8=,tag:ztO5rYK+M/shbzauOaFrMg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:gSx0wDZXtuntzIs=,iv:uyG240wyLpin5+55ARMPLxrQtOFJrbGsMUQ6uNQH8wU=,tag:e/kj5VokvJksZaS7kZNOJQ==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:JPY+27tvk3LCxxul/zsWK9wOkZA=,iv:+3krRP2UCik+JCHEiyDmYruVnDrHbJ2xpuSiBDmVHdA=,tag:xBzQ+prntYpq2FffznymRw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kkDmc6OOk/aHhhuJRznTkKvbFm4BBk/cNA04SMlB7xH8AklF4aKp5w==,iv:C7LHdKDJrnlRoJVKe5rn8YtauzJGVVPiCXycO2orZpE=,tag:+XdreWEjiEwpeeu+SC0QxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NjJFekxSZ1MzRDZxNmt6
            YzIwenkra2JDNW1nL20vR04zNC9uOTAyc21zCjZtd1ZqbWVtWUdwNlg0M241RFVr
            K2RkUXMzQUpoRUxrNDZKd0lzRFMvQncKLS0tIG9rdHFMckxHNjdHbnYzT2lZaGc3
            Q2JBaDYvWlZIWTZCMHpGeGtBZUlXa28K2ahRRyTdNSizAbiIo6AJmtrRcZAIwfli
            q0lO2jrR9mNTcSAA0ZRQ2a3tJAJDdk+hG9MuuAHbGhSy43z2wUmaGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:52:12Z"
    mac: ENC[AES256_GCM,data:rctZVCznIuuSQJYEc4p9wehkeVtidLzDQ4cDdja5vFKwUBY6OG4TNRIvbklJVlwGCQQs1QTsqfGUmKdT3XpYPjflpuQK7p7iiy6o6QSXeDMw+F1G4n31arM48G+K1MJ5WJaEF2Mp4IDds/gskCCECua5nd6GCTeqCwWWEhuNcBk=,iv:3nsWNpdLoRS3N4mIqmrTOoeMPLj/rLt/s6XG0GkZyMQ=,tag:N933ahGJgYwrUbKd0GE0hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:uAcxRNcz,iv:Euc7HoQxM2Px5CxQnpCvLdl7KoLXZRf2B0unPsVc7+o=,tag:HcK/KYBqLiLW88rPg0XZ9g==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:eJ+SHsXw2ul6rAQ=,iv:Wya9Uf2SxXNrE1giBfPGdACMz1zu9vB+qIYVGtKqq68=,tag:bmb6f5Sz/FtQYVkRiYgxHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NjJFekxSZ1MzRDZxNmt6
            YzIwenkra2JDNW1nL20vR04zNC9uOTAyc21zCjZtd1ZqbWVtWUdwNlg0M241RFVr
            K2RkUXMzQUpoRUxrNDZKd0lzRFMvQncKLS0tIG9rdHFMckxHNjdHbnYzT2lZaGc3
            Q2JBaDYvWlZIWTZCMHpGeGtBZUlXa28K2ahRRyTdNSizAbiIo6AJmtrRcZAIwfli
            q0lO2jrR9mNTcSAA0ZRQ2a3tJAJDdk+hG9MuuAHbGhSy43z2wUmaGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:52:12Z"
    mac: ENC[AES256_GCM,data:rctZVCznIuuSQJYEc4p9wehkeVtidLzDQ4cDdja5vFKwUBY6OG4TNRIvbklJVlwGCQQs1QTsqfGUmKdT3XpYPjflpuQK7p7iiy6o6QSXeDMw+F1G4n31arM48G+K1MJ5WJaEF2Mp4IDds/gskCCECua5nd6GCTeqCwWWEhuNcBk=,iv:3nsWNpdLoRS3N4mIqmrTOoeMPLj/rLt/s6XG0GkZyMQ=,tag:N933ahGJgYwrUbKd0GE0hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:T6r0DFmoTbQ=,iv:S/JLLOe8FJsHYro/cQqbciB4LwDT1W2IZXJw/RNNbZU=,tag:0CvhR0So2qteX+cpopQZBw==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:7IWhA0Y/fuQEfJM=,iv:5+K69Pg6h4oePkFUd22KZ9OZh1ykbucmaIXsiH52Z0I=,tag:3sUsfLu9SEEYBRGyzrPL8Q==,type:str]
    PASSPHRASE: ENC[AES256_GCM,data:rk47X6TC7o+6AFhBnZSoXl3yecN+7bMhd5hKT/DIjAAJkg==,iv:wLBmiA3L2PvktKko/HjWrVH94hu2Nty7nsDwPZn8q4g=,tag:hSWsGMQT8KKrNVZNRIJ0/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NjJFekxSZ1MzRDZxNmt6
            YzIwenkra2JDNW1nL20vR04zNC9uOTAyc21zCjZtd1ZqbWVtWUdwNlg0M241RFVr
            K2RkUXMzQUpoRUxrNDZKd0lzRFMvQncKLS0tIG9rdHFMckxHNjdHbnYzT2lZaGc3
            Q2JBaDYvWlZIWTZCMHpGeGtBZUlXa28K2ahRRyTdNSizAbiIo6AJmtrRcZAIwfli
            q0lO2jrR9mNTcSAA0ZRQ2a3tJAJDdk+hG9MuuAHbGhSy43z2wUmaGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:52:12Z"
    mac: ENC[AES256_GCM,data:rctZVCznIuuSQJYEc4p9wehkeVtidLzDQ4cDdja5vFKwUBY6OG4TNRIvbklJVlwGCQQs1QTsqfGUmKdT3XpYPjflpuQK7p7iiy6o6QSXeDMw+F1G4n31arM48G+K1MJ5WJaEF2Mp4IDds/gskCCECua5nd6GCTeqCwWWEhuNcBk=,iv:3nsWNpdLoRS3N4mIqmrTOoeMPLj/rLt/s6XG0GkZyMQ=,tag:N933ahGJgYwrUbKd0GE0hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: product-feedback
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:LSbJOZzu2lqPffcR,iv:Gqw7guI/4gb0f3iGHAQwouz4COgFNEIu6K8A52KJoqw=,tag:np6zQOMcrO6CuaZSoYeOtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NjJFekxSZ1MzRDZxNmt6
            YzIwenkra2JDNW1nL20vR04zNC9uOTAyc21zCjZtd1ZqbWVtWUdwNlg0M241RFVr
            K2RkUXMzQUpoRUxrNDZKd0lzRFMvQncKLS0tIG9rdHFMckxHNjdHbnYzT2lZaGc3
            Q2JBaDYvWlZIWTZCMHpGeGtBZUlXa28K2ahRRyTdNSizAbiIo6AJmtrRcZAIwfli
            q0lO2jrR9mNTcSAA0ZRQ2a3tJAJDdk+hG9MuuAHbGhSy43z2wUmaGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:52:12Z"
    mac: ENC[AES256_GCM,data:rctZVCznIuuSQJYEc4p9wehkeVtidLzDQ4cDdja5vFKwUBY6OG4TNRIvbklJVlwGCQQs1QTsqfGUmKdT3XpYPjflpuQK7p7iiy6o6QSXeDMw+F1G4n31arM48G+K1MJ5WJaEF2Mp4IDds/gskCCECua5nd6GCTeqCwWWEhuNcBk=,iv:3nsWNpdLoRS3N4mIqmrTOoeMPLj/rLt/s6XG0GkZyMQ=,tag:N933ahGJgYwrUbKd0GE0hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
