apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:NtNLFM/nQxzwhv4exwSjlLAnXJUJOQ/e/XnPy9qDhsATT535C65e3J5iKFemOhILp5D+QK2HF66ZW6Kp4K9S0XajgDMU/vL9sXW5g3v/PrrGYKoqpvLn7g==,iv:yZcIRJx2D+kG8qgWjagtqp3k0IkReWxTzbiw/7Rz3FI=,tag:bSu7kzZafipu8J5Y4vnmDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L2dCampING10aWlCcGpZ
            OXBRQXJSZmVNSGVyQ2dFVVJyMFR0T29hK1dnCkh1a2FjeFZ2T2lINTVXcm5ZWmpW
            aGEzWHBLbUVLN2preVhNaVFET0EwbjgKLS0tIGdQS1ovUUxFMjdzYk1taHh2bDhW
            YTRrUmJHQWdSZXRvd1JqMTUrcHRsR28KYl3ICQ8KZsPH5i7gl9c6eUB2ie1nfABq
            ElOvHa6VcgnjHg6sliNVZHldZ4Hx+lyZjpkGhWUhWmEan/0IGhbRCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T07:19:17Z"
    mac: ENC[AES256_GCM,data:ZkZ3qdZpaTJsKDOt1ADskhZsYXF2rlWDBgtVNOeczGSk2JPOW3muJxZqxexGg+OfFwLPXyvz68XX86q1zGh/tUsmlfLIMdvHJ3yIfXyKX0+gFBsTcaRmmIyY+jojnwcWZlEXpQs5rNh2mX8SmiNcU5hkDQcNNczZHl6FpggOQwg=,iv:jwmk8cbbZc43rQPlvjRIQBnPfvZHDZN+D8YxFsKqZ4U=,tag:XfH/zpHOVh/3l/0ou76tMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:g5kC2z2ThZN27Cg=,iv:yhfUB2cIvN4K/2sxsFRzrzByqFM320yeWulAo2ZpOvw=,tag:AGOmkchpio4iTstw+XEneg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L2dCampING10aWlCcGpZ
            OXBRQXJSZmVNSGVyQ2dFVVJyMFR0T29hK1dnCkh1a2FjeFZ2T2lINTVXcm5ZWmpW
            aGEzWHBLbUVLN2preVhNaVFET0EwbjgKLS0tIGdQS1ovUUxFMjdzYk1taHh2bDhW
            YTRrUmJHQWdSZXRvd1JqMTUrcHRsR28KYl3ICQ8KZsPH5i7gl9c6eUB2ie1nfABq
            ElOvHa6VcgnjHg6sliNVZHldZ4Hx+lyZjpkGhWUhWmEan/0IGhbRCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T07:19:17Z"
    mac: ENC[AES256_GCM,data:ZkZ3qdZpaTJsKDOt1ADskhZsYXF2rlWDBgtVNOeczGSk2JPOW3muJxZqxexGg+OfFwLPXyvz68XX86q1zGh/tUsmlfLIMdvHJ3yIfXyKX0+gFBsTcaRmmIyY+jojnwcWZlEXpQs5rNh2mX8SmiNcU5hkDQcNNczZHl6FpggOQwg=,iv:jwmk8cbbZc43rQPlvjRIQBnPfvZHDZN+D8YxFsKqZ4U=,tag:XfH/zpHOVh/3l/0ou76tMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:2ZySCUVkYYc=,iv:9mJ2ThKUvC0eq6hk6kfcuXFOuDXnMbBen1n8wFffe7c=,tag:r2XWxpUxBKHRJpnplVlrwg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Cy8VjZC/82gZLLw=,iv:2edCjqpoDcqvWKjp3omk8lohNj2pt18xc0tX5Fmrb+I=,tag:jyhUm3cOoknMHBbSXKp02A==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:CIhhIuNradAl20d9iSFMP65NS7Y=,iv:x1GbhUc3UlzNgqvzNm3KfKEzieVt+yN1bFMRGMiw+Ss=,tag:24KnGgHs76K2HI5Ij8EVGg==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6UK+k/+bzIT2KzGYiQfmeeh/l3XkR496ERYCQNS9rYq3yBbkjKYsGA==,iv:GatF6Z4fV66ecmT16TDwlE2HHkxRzkn3FtrjvdiULS8=,tag:fpnzNx73J0nBBlnUepv01w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L2dCampING10aWlCcGpZ
            OXBRQXJSZmVNSGVyQ2dFVVJyMFR0T29hK1dnCkh1a2FjeFZ2T2lINTVXcm5ZWmpW
            aGEzWHBLbUVLN2preVhNaVFET0EwbjgKLS0tIGdQS1ovUUxFMjdzYk1taHh2bDhW
            YTRrUmJHQWdSZXRvd1JqMTUrcHRsR28KYl3ICQ8KZsPH5i7gl9c6eUB2ie1nfABq
            ElOvHa6VcgnjHg6sliNVZHldZ4Hx+lyZjpkGhWUhWmEan/0IGhbRCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T07:19:17Z"
    mac: ENC[AES256_GCM,data:ZkZ3qdZpaTJsKDOt1ADskhZsYXF2rlWDBgtVNOeczGSk2JPOW3muJxZqxexGg+OfFwLPXyvz68XX86q1zGh/tUsmlfLIMdvHJ3yIfXyKX0+gFBsTcaRmmIyY+jojnwcWZlEXpQs5rNh2mX8SmiNcU5hkDQcNNczZHl6FpggOQwg=,iv:jwmk8cbbZc43rQPlvjRIQBnPfvZHDZN+D8YxFsKqZ4U=,tag:XfH/zpHOVh/3l/0ou76tMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
