apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:9TjWPeciE4gxWSHEIwW6LMyDEKgDHaaJN4HQiQ6ut8GpTZ2kPQmz9wo3M5eZz2UQyxjMH5MGro06mIpYTgloC5k1TqY4hJr/QGYi/7Wiv8yqEPx7RPldnA==,iv:SSMH5n5oA256KbeR3D50D48kCUKPQDLxTYaOLJM6N0s=,tag:cuOFQKTJrNmIAmL2kaR4Sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OE9uL1BTRjZMTWVyMHJO
            cjFhMVRSbmZMQ3Y0WHBSTXl0bEhCNTdUR0NFCjVjR0N3bXZMVWVISksxRTNWS1Qv
            WHUyUHdlcWJlbFZIem5yZi9IWGVTUEEKLS0tIEdMNHhicXQvV2ttY2tUUHJRMWtB
            bkJoLzcrbUpKdVlzNkdOTmpra3Bra2sKNb85HHRJNrd0mIj2SjQtPwE5v/Cta35/
            AvnAMHi9h6AqporrABbWRPa/zH8q+18pggD/DBNegitYkW2DdqFfjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T23:00:03Z"
    mac: ENC[AES256_GCM,data:gd2pyP+nO9tyxu+Azwq1ipqFrx90/3PTPRbw+x0twOKRGBt4eyF1LJkR/XsaiAaINFxYqx+Nk8TyE1yzZOxgQr3/prqA3KM0U0t2W6neLBGeyzOeFliNJLprNS5wgpo3h26+IB/l80YM+D9ZfQWbjX9lyYHYQeWIuv+W0xnzmas=,iv:8ualhHuOmt/AcyWUO7QSIj5FklXKbCiSSO8Gtjjh+WY=,tag:XsFcdoRLxAtPdtqt5AXKlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: keycloak
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XGN5zUU04rRfOe4=,iv:Sxc6zsmdQV1qbStE7EBhn4iAoRxoGHjFubPnqe6AvtY=,tag:5o6wRmfQaWFFln0v71tndA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OE9uL1BTRjZMTWVyMHJO
            cjFhMVRSbmZMQ3Y0WHBSTXl0bEhCNTdUR0NFCjVjR0N3bXZMVWVISksxRTNWS1Qv
            WHUyUHdlcWJlbFZIem5yZi9IWGVTUEEKLS0tIEdMNHhicXQvV2ttY2tUUHJRMWtB
            bkJoLzcrbUpKdVlzNkdOTmpra3Bra2sKNb85HHRJNrd0mIj2SjQtPwE5v/Cta35/
            AvnAMHi9h6AqporrABbWRPa/zH8q+18pggD/DBNegitYkW2DdqFfjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T23:00:03Z"
    mac: ENC[AES256_GCM,data:gd2pyP+nO9tyxu+Azwq1ipqFrx90/3PTPRbw+x0twOKRGBt4eyF1LJkR/XsaiAaINFxYqx+Nk8TyE1yzZOxgQr3/prqA3KM0U0t2W6neLBGeyzOeFliNJLprNS5wgpo3h26+IB/l80YM+D9ZfQWbjX9lyYHYQeWIuv+W0xnzmas=,iv:8ualhHuOmt/AcyWUO7QSIj5FklXKbCiSSO8Gtjjh+WY=,tag:XsFcdoRLxAtPdtqt5AXKlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:iQUPFoS+VsU=,iv:jXCdI1plTUbufmRuAh+paqKs0spjYAJLXmf458kvGUU=,tag:pfkdJx6uvpZErLObOOSHZQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:BIKyXsqOEN0BWqU=,iv:1cAQPS/Eaq4nL83wXmNDCqq+EOMYv0j1JVCZNvt54GM=,tag:4C0V2duelBUwba8QsuIKsg==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:I0qe9KHN1xBbuLB5wN4Ij3C0VD8=,iv:JlxM8cbHgQm6wnUty2PaJCyrfDy+5JNxAX7Y4JsExgQ=,tag:bmNoWLe6LzgEyGRbM7wS5A==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3LlN7LWNJOIJyroxiwjss6Ujhmh/KrOR+YGOmqYQN6GSZk7jel/K2g==,iv:uPIYuUpfTYlYZ6QYn2fN1Eukpy7n8uOoTFz8I+XLMDs=,tag:SOF5CFL2ecigS+vkDq5wsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OE9uL1BTRjZMTWVyMHJO
            cjFhMVRSbmZMQ3Y0WHBSTXl0bEhCNTdUR0NFCjVjR0N3bXZMVWVISksxRTNWS1Qv
            WHUyUHdlcWJlbFZIem5yZi9IWGVTUEEKLS0tIEdMNHhicXQvV2ttY2tUUHJRMWtB
            bkJoLzcrbUpKdVlzNkdOTmpra3Bra2sKNb85HHRJNrd0mIj2SjQtPwE5v/Cta35/
            AvnAMHi9h6AqporrABbWRPa/zH8q+18pggD/DBNegitYkW2DdqFfjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T23:00:03Z"
    mac: ENC[AES256_GCM,data:gd2pyP+nO9tyxu+Azwq1ipqFrx90/3PTPRbw+x0twOKRGBt4eyF1LJkR/XsaiAaINFxYqx+Nk8TyE1yzZOxgQr3/prqA3KM0U0t2W6neLBGeyzOeFliNJLprNS5wgpo3h26+IB/l80YM+D9ZfQWbjX9lyYHYQeWIuv+W0xnzmas=,iv:8ualhHuOmt/AcyWUO7QSIj5FklXKbCiSSO8Gtjjh+WY=,tag:XsFcdoRLxAtPdtqt5AXKlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:uAURYgD9,iv:QfDKTOKpnxFCbO7D4vw/qkHgq1qbOBfvf9jUyEGnMy0=,tag:1nEuyEN6M+5OsTI0kKLjEA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:N69noEGKN0IOh5c=,iv:1SqGryGKz89fgLlEWPwg2HdBTwEpL65KzPSqrjHjyJo=,tag:dW5WLAhyJqhYu3s5wwDxwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OE9uL1BTRjZMTWVyMHJO
            cjFhMVRSbmZMQ3Y0WHBSTXl0bEhCNTdUR0NFCjVjR0N3bXZMVWVISksxRTNWS1Qv
            WHUyUHdlcWJlbFZIem5yZi9IWGVTUEEKLS0tIEdMNHhicXQvV2ttY2tUUHJRMWtB
            bkJoLzcrbUpKdVlzNkdOTmpra3Bra2sKNb85HHRJNrd0mIj2SjQtPwE5v/Cta35/
            AvnAMHi9h6AqporrABbWRPa/zH8q+18pggD/DBNegitYkW2DdqFfjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T23:00:03Z"
    mac: ENC[AES256_GCM,data:gd2pyP+nO9tyxu+Azwq1ipqFrx90/3PTPRbw+x0twOKRGBt4eyF1LJkR/XsaiAaINFxYqx+Nk8TyE1yzZOxgQr3/prqA3KM0U0t2W6neLBGeyzOeFliNJLprNS5wgpo3h26+IB/l80YM+D9ZfQWbjX9lyYHYQeWIuv+W0xnzmas=,iv:8ualhHuOmt/AcyWUO7QSIj5FklXKbCiSSO8Gtjjh+WY=,tag:XsFcdoRLxAtPdtqt5AXKlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:8LfUBlxqRRo=,iv:iLEDCzlr9wz/Ot+DKxq8NMdwqhrdfGaTA30LF4jv/UA=,tag:K7R6CUlGFXrUspobX262rA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:6Gji+jgKc41AnFk=,iv:p+xmKFU1OiKGV3tkWp3SmzXgCl1NFVSSqKupUwQfPNQ=,tag:+O/OEYUFEfc+RqrwcbasZA==,type:str]
    PASSPHRASE: ENC[AES256_GCM,data:xaPnSxwxO2bwttIYm8jGu7884lxAGtr8PfcItxRast6YqA==,iv:QLE3bSIXA0iSAMhclA071VH4UIAVFHdZ4vAxh2CvL8g=,tag:KsexHgEuEAU+U29JfsqCoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OE9uL1BTRjZMTWVyMHJO
            cjFhMVRSbmZMQ3Y0WHBSTXl0bEhCNTdUR0NFCjVjR0N3bXZMVWVISksxRTNWS1Qv
            WHUyUHdlcWJlbFZIem5yZi9IWGVTUEEKLS0tIEdMNHhicXQvV2ttY2tUUHJRMWtB
            bkJoLzcrbUpKdVlzNkdOTmpra3Bra2sKNb85HHRJNrd0mIj2SjQtPwE5v/Cta35/
            AvnAMHi9h6AqporrABbWRPa/zH8q+18pggD/DBNegitYkW2DdqFfjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T23:00:03Z"
    mac: ENC[AES256_GCM,data:gd2pyP+nO9tyxu+Azwq1ipqFrx90/3PTPRbw+x0twOKRGBt4eyF1LJkR/XsaiAaINFxYqx+Nk8TyE1yzZOxgQr3/prqA3KM0U0t2W6neLBGeyzOeFliNJLprNS5wgpo3h26+IB/l80YM+D9ZfQWbjX9lyYHYQeWIuv+W0xnzmas=,iv:8ualhHuOmt/AcyWUO7QSIj5FklXKbCiSSO8Gtjjh+WY=,tag:XsFcdoRLxAtPdtqt5AXKlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: product-feedback
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:TLzdl77wKMrHGowK,iv:2JbicIO6ySm16Ql5btz8HXPDxxtH9oFHis/zu4Fpw8M=,tag:yl0Je5uPycFiZoZ2jbl6Og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OE9uL1BTRjZMTWVyMHJO
            cjFhMVRSbmZMQ3Y0WHBSTXl0bEhCNTdUR0NFCjVjR0N3bXZMVWVISksxRTNWS1Qv
            WHUyUHdlcWJlbFZIem5yZi9IWGVTUEEKLS0tIEdMNHhicXQvV2ttY2tUUHJRMWtB
            bkJoLzcrbUpKdVlzNkdOTmpra3Bra2sKNb85HHRJNrd0mIj2SjQtPwE5v/Cta35/
            AvnAMHi9h6AqporrABbWRPa/zH8q+18pggD/DBNegitYkW2DdqFfjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T23:00:03Z"
    mac: ENC[AES256_GCM,data:gd2pyP+nO9tyxu+Azwq1ipqFrx90/3PTPRbw+x0twOKRGBt4eyF1LJkR/XsaiAaINFxYqx+Nk8TyE1yzZOxgQr3/prqA3KM0U0t2W6neLBGeyzOeFliNJLprNS5wgpo3h26+IB/l80YM+D9ZfQWbjX9lyYHYQeWIuv+W0xnzmas=,iv:8ualhHuOmt/AcyWUO7QSIj5FklXKbCiSSO8Gtjjh+WY=,tag:XsFcdoRLxAtPdtqt5AXKlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_DB_USERNAME: ENC[AES256_GCM,data:flbR2WbFnLo=,iv:sbJ6jbKwTUP3BMT4eWsb0Vr6PF7ZU9zqEW6DHQMwqUE=,tag:E0MsvAwTXd3xFTs7YNd6MA==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:AHvYSx8D/T9OBPCm1OESZM5Zg1g=,iv:U0ZMrI1vy4oxM0GWydegdhbcWP7B/XujPTg3RG7dEmw=,tag:4YMXRXtxXJNxGUxkSFpIPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OE9uL1BTRjZMTWVyMHJO
            cjFhMVRSbmZMQ3Y0WHBSTXl0bEhCNTdUR0NFCjVjR0N3bXZMVWVISksxRTNWS1Qv
            WHUyUHdlcWJlbFZIem5yZi9IWGVTUEEKLS0tIEdMNHhicXQvV2ttY2tUUHJRMWtB
            bkJoLzcrbUpKdVlzNkdOTmpra3Bra2sKNb85HHRJNrd0mIj2SjQtPwE5v/Cta35/
            AvnAMHi9h6AqporrABbWRPa/zH8q+18pggD/DBNegitYkW2DdqFfjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T23:00:03Z"
    mac: ENC[AES256_GCM,data:gd2pyP+nO9tyxu+Azwq1ipqFrx90/3PTPRbw+x0twOKRGBt4eyF1LJkR/XsaiAaINFxYqx+Nk8TyE1yzZOxgQr3/prqA3KM0U0t2W6neLBGeyzOeFliNJLprNS5wgpo3h26+IB/l80YM+D9ZfQWbjX9lyYHYQeWIuv+W0xnzmas=,iv:8ualhHuOmt/AcyWUO7QSIj5FklXKbCiSSO8Gtjjh+WY=,tag:XsFcdoRLxAtPdtqt5AXKlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials
    namespace: keycloak
type: Opaque
stringData:
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:wAWfdo8=,iv:sqWx+2e9t27Z8LqKynDhyJcQz/7FSHpPEs5APvxiSZU=,tag:NqfDJv3SVYe01sN0e9Ok+A==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:0Z/TMUqWjXnDRCMvd/2sMKgbFFQ=,iv:voLuV8C+cxfi/wnsmgXn+2D9QRJ+D9LmY2ZH8/7A9Xc=,tag:51G7pLgrX7XN17tg8zxpgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OE9uL1BTRjZMTWVyMHJO
            cjFhMVRSbmZMQ3Y0WHBSTXl0bEhCNTdUR0NFCjVjR0N3bXZMVWVISksxRTNWS1Qv
            WHUyUHdlcWJlbFZIem5yZi9IWGVTUEEKLS0tIEdMNHhicXQvV2ttY2tUUHJRMWtB
            bkJoLzcrbUpKdVlzNkdOTmpra3Bra2sKNb85HHRJNrd0mIj2SjQtPwE5v/Cta35/
            AvnAMHi9h6AqporrABbWRPa/zH8q+18pggD/DBNegitYkW2DdqFfjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T23:00:03Z"
    mac: ENC[AES256_GCM,data:gd2pyP+nO9tyxu+Azwq1ipqFrx90/3PTPRbw+x0twOKRGBt4eyF1LJkR/XsaiAaINFxYqx+Nk8TyE1yzZOxgQr3/prqA3KM0U0t2W6neLBGeyzOeFliNJLprNS5wgpo3h26+IB/l80YM+D9ZfQWbjX9lyYHYQeWIuv+W0xnzmas=,iv:8ualhHuOmt/AcyWUO7QSIj5FklXKbCiSSO8Gtjjh+WY=,tag:XsFcdoRLxAtPdtqt5AXKlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
