apiVersion: v1
kind: Secret
metadata:
    name: sqlconnectionstring
    namespace: product-feedback
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    SQL_CONNECTION_STRING: ENC[AES256_GCM,data:RogbAvSPjIEQLKh5e3VI0dQjHEN7y+RqoNbvRpnQ5QALotFOqNG7Y6cBVdKJHaseJ6swjmdLkPcgBz97T9ICHZePb15uzkg3kK3s+bUeJUlqJz30zvkGJA==,iv:SWbKCt6ECxrzviejjYI+q54RyxkOQkKqRA1FGlijefs=,tag:SlpdsK0TTbPPG/h5accsHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bW9IRkxENG0rT0t6dG0x
            OGFDQ2xmRUFKQzJWZ1RjbHBJSUNvQVVnQlI0CjdidHZHUWl5RTlLUXlzVnNSb3kr
            ZlFXNDZLRml0bEtPNmRGWDcxR0U4UUUKLS0tIE54d2oxRnlxL3Y4QlRtME1xL3Vr
            MlBFTjR5OTJ0VjhFeDJwM0daTWFvSjAKXtWSY32Rlhq032omYvv83uWSj8bMlQY1
            TNOTd4mPcSB8SvoodWuBbhxsldhyvkPgyvtE46vNSaXiFPufi49o9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T00:24:39Z"
    mac: ENC[AES256_GCM,data:zbPdvCECzXRT6fad63UwjIgqhR3cchVV8MVnhJcaF6PhPpLPg4iYSIccAUExX7fuflqFro/giM9RjvSF67b2EhPco6bPFQy6T+qr/YPSUtvG9ptuTkJ7Iq4gwHcFU70rmDdCOcXqFa5qpBZ+Iom30yMq5Hir79FhtX9I0K8KpiY=,iv:sOQ+IPKVu+Anf4TCavEsCaIxkJmZbrPrHyUqT5bMZtQ=,tag:G6NrejpUaB8+gLPNgt8luw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
    annotations:
        enc.suffix: encrypted
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:I4whhurPKt2Ywus=,iv:1AxMAWFu7zylj657jVJcvXpdDx7YQhYfCqfonkMkbFw=,tag:GXOVjTumfY4hM0uKiXpEfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bW9IRkxENG0rT0t6dG0x
            OGFDQ2xmRUFKQzJWZ1RjbHBJSUNvQVVnQlI0CjdidHZHUWl5RTlLUXlzVnNSb3kr
            ZlFXNDZLRml0bEtPNmRGWDcxR0U4UUUKLS0tIE54d2oxRnlxL3Y4QlRtME1xL3Vr
            MlBFTjR5OTJ0VjhFeDJwM0daTWFvSjAKXtWSY32Rlhq032omYvv83uWSj8bMlQY1
            TNOTd4mPcSB8SvoodWuBbhxsldhyvkPgyvtE46vNSaXiFPufi49o9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T00:24:39Z"
    mac: ENC[AES256_GCM,data:zbPdvCECzXRT6fad63UwjIgqhR3cchVV8MVnhJcaF6PhPpLPg4iYSIccAUExX7fuflqFro/giM9RjvSF67b2EhPco6bPFQy6T+qr/YPSUtvG9ptuTkJ7Iq4gwHcFU70rmDdCOcXqFa5qpBZ+Iom30yMq5Hir79FhtX9I0K8KpiY=,iv:sOQ+IPKVu+Anf4TCavEsCaIxkJmZbrPrHyUqT5bMZtQ=,tag:G6NrejpUaB8+gLPNgt8luw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-credentials
    namespace: backup
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Pur1x7291c8=,iv:No4032maPLVT5+zLh1oE9mx3gkr8j/WjwUeu/Ea6ggI=,tag:nsXjjWrdQRrIg7SQ5PMNOA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:w/HiHvO2ahnkRU0=,iv:BRvy6NKHDf03WvfSCLMvlXmCwfA5imR6dyuJGrVa6H8=,tag:y0eOHl2AHgl4+jbRqBAkOA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:44J9dyIQttb+PnR/0tL8rY8ZuTY=,iv:tur7WJZQq/dvbxxfaKUP8kcs5d7OdLK7vpULywGNrrQ=,tag:et62gPeYOj4UvjdDn/GeiQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:praHH2GbCOF/uMDCw1tu7k6tIC9aiL85kc0TAJKlSWOgRLnScXR+Ww==,iv:DqojjHuJZIXf7JdlkulFGLa9XCe8OfGyGVAVyS7PqRQ=,tag:FZN/d+G/J0ynfXZlAJOzrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bW9IRkxENG0rT0t6dG0x
            OGFDQ2xmRUFKQzJWZ1RjbHBJSUNvQVVnQlI0CjdidHZHUWl5RTlLUXlzVnNSb3kr
            ZlFXNDZLRml0bEtPNmRGWDcxR0U4UUUKLS0tIE54d2oxRnlxL3Y4QlRtME1xL3Vr
            MlBFTjR5OTJ0VjhFeDJwM0daTWFvSjAKXtWSY32Rlhq032omYvv83uWSj8bMlQY1
            TNOTd4mPcSB8SvoodWuBbhxsldhyvkPgyvtE46vNSaXiFPufi49o9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T00:24:39Z"
    mac: ENC[AES256_GCM,data:zbPdvCECzXRT6fad63UwjIgqhR3cchVV8MVnhJcaF6PhPpLPg4iYSIccAUExX7fuflqFro/giM9RjvSF67b2EhPco6bPFQy6T+qr/YPSUtvG9ptuTkJ7Iq4gwHcFU70rmDdCOcXqFa5qpBZ+Iom30yMq5Hir79FhtX9I0K8KpiY=,iv:sOQ+IPKVu+Anf4TCavEsCaIxkJmZbrPrHyUqT5bMZtQ=,tag:G6NrejpUaB8+gLPNgt8luw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:NTyBDq0f,iv:l57Jz3C5BTUcy22B34jzSXnrCRKUPDtpPR/987I596E=,tag:X4mF2DWiQZb/TNdqreyrBQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:D0Q6i0sx8QVv318=,iv:2Wq/aNDXfgXNc+9qLe5quGcqaSt3owXXEF2+/uaPYTA=,tag:AEldX7Et46D0igwPUynf8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bW9IRkxENG0rT0t6dG0x
            OGFDQ2xmRUFKQzJWZ1RjbHBJSUNvQVVnQlI0CjdidHZHUWl5RTlLUXlzVnNSb3kr
            ZlFXNDZLRml0bEtPNmRGWDcxR0U4UUUKLS0tIE54d2oxRnlxL3Y4QlRtME1xL3Vr
            MlBFTjR5OTJ0VjhFeDJwM0daTWFvSjAKXtWSY32Rlhq032omYvv83uWSj8bMlQY1
            TNOTd4mPcSB8SvoodWuBbhxsldhyvkPgyvtE46vNSaXiFPufi49o9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T00:24:39Z"
    mac: ENC[AES256_GCM,data:zbPdvCECzXRT6fad63UwjIgqhR3cchVV8MVnhJcaF6PhPpLPg4iYSIccAUExX7fuflqFro/giM9RjvSF67b2EhPco6bPFQy6T+qr/YPSUtvG9ptuTkJ7Iq4gwHcFU70rmDdCOcXqFa5qpBZ+Iom30yMq5Hir79FhtX9I0K8KpiY=,iv:sOQ+IPKVu+Anf4TCavEsCaIxkJmZbrPrHyUqT5bMZtQ=,tag:G6NrejpUaB8+gLPNgt8luw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:0+209N/YY5A=,iv:wx1ppSYWGJprMLtRxQLC2Mq132tjb8w4RNUsd9OU0pM=,tag:9bXEg0/ERctAZs08mgJjiA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:/grSgqjrXzhk10c=,iv:QDlxUlzp5I9JIhTtycNAhYLoOmjQ5HXPDQ7zEOZ3Kk8=,tag:cJtmIv0QbFtcgknODvMjHw==,type:str]
    PASSPHRASE: ENC[AES256_GCM,data:hKFlPtfEQznMF3D5dmpPnM2AEOzVC3e2pmcgOmbqFpZebQ==,iv:KBFG9Q0o6x4Bx2qFBBBbHdwPWmMYQEt5nKZbTqUo550=,tag:5PGZlFzbaSxCnvMg78M8rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bW9IRkxENG0rT0t6dG0x
            OGFDQ2xmRUFKQzJWZ1RjbHBJSUNvQVVnQlI0CjdidHZHUWl5RTlLUXlzVnNSb3kr
            ZlFXNDZLRml0bEtPNmRGWDcxR0U4UUUKLS0tIE54d2oxRnlxL3Y4QlRtME1xL3Vr
            MlBFTjR5OTJ0VjhFeDJwM0daTWFvSjAKXtWSY32Rlhq032omYvv83uWSj8bMlQY1
            TNOTd4mPcSB8SvoodWuBbhxsldhyvkPgyvtE46vNSaXiFPufi49o9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T00:24:39Z"
    mac: ENC[AES256_GCM,data:zbPdvCECzXRT6fad63UwjIgqhR3cchVV8MVnhJcaF6PhPpLPg4iYSIccAUExX7fuflqFro/giM9RjvSF67b2EhPco6bPFQy6T+qr/YPSUtvG9ptuTkJ7Iq4gwHcFU70rmDdCOcXqFa5qpBZ+Iom30yMq5Hir79FhtX9I0K8KpiY=,iv:sOQ+IPKVu+Anf4TCavEsCaIxkJmZbrPrHyUqT5bMZtQ=,tag:G6NrejpUaB8+gLPNgt8luw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
