apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      name: http
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-discovery
  namespace: keycloak
spec:
  selector:
    app: keycloak
  clusterIP: None
  type: ClusterIP
---
apiVersion: apps/v1
# Use a stateful setup to ensure that for a rolling update Pods are restarted with a rolling strategy one-by-one.
# This prevents losing in-memory information stored redundantly in two Pods.
kind: StatefulSet
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  serviceName: keycloak-discovery
  # Run with one replica to save resources, or with two replicas to allow for rolling updates for configuration changes
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: init-db
          image: postgres:15
          env:
            - name: PGHOST
              value: "postgres-db.database.svc.cluster.local"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres # Reflected from database namespace
                  key: POSTGRES_PASSWORD
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-credentials
                  key: KC_DB_USERNAME
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-credentials
                  key: KC_DB_PASSWORD
          resources:
            requests:
              ephemeral-storage: "50Mi"
            limits:
              ephemeral-storage: "100Mi"
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until pg_isready -h $PGHOST -p $PGPORT -U $PGUSER; do
                sleep 2
              done
              echo "PostgreSQL is ready. Creating database and user..."
              psql -v ON_ERROR_STOP=1 <<-EOSQL
                DO \$\$
                BEGIN
                  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${KC_DB_USERNAME}') THEN
                    CREATE USER ${KC_DB_USERNAME} WITH PASSWORD '${KC_DB_PASSWORD}';
                  END IF;
                END
                \$\$;
              EOSQL

              psql -v ON_ERROR_STOP=1 <<-EOSQL
                SELECT 'CREATE DATABASE keycloak OWNER ${KC_DB_USERNAME}'
                WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'keycloak')\gexec
              EOSQL

              psql -d keycloak -v ON_ERROR_STOP=1 <<-EOSQL
                GRANT ALL ON SCHEMA public TO ${KC_DB_USERNAME};
                GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${KC_DB_USERNAME};
                GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${KC_DB_USERNAME};
              EOSQL
              echo "Database setup complete."
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.4.7
          args: ["start"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-credentials
                  key: KC_BOOTSTRAP_ADMIN_USERNAME
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-credentials
                  key: KC_BOOTSTRAP_ADMIN_PASSWORD
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "true"
            - name: KC_HOSTNAME
              value: "identity.alexbartleynees.com"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: "KC_CACHE"
              value: "ispn"
            # Passing the Pod's IP primary address to the JGroups clustering as this is required in IPv6 only setups
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # Instruct JGroups which DNS hostname to use to discover other Keycloak nodes
            # Needs to be unique for each Keycloak cluster
            - name: KC_CACHE_EMBEDDED_NETWORK_BIND_ADDRESS
              value: "$(POD_IP)"
            - name: "KC_DB_URL_DATABASE"
              value: "keycloak"
            - name: "KC_DB_URL_HOST"
              value: "postgres-db.database.svc.cluster.local"
            - name: "KC_DB"
              value: "postgres"
            - name: "KC_DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-credentials
                  key: KC_DB_PASSWORD
            - name: "KC_DB_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-credentials
                  key: KC_DB_USERNAME
          ports:
            - name: http
              containerPort: 8080
            - name: jgroups
              containerPort: 7800
            - name: jgroups-fd
              containerPort: 57800
          startupProbe:
            httpGet:
              path: /health/started
              port: 9000
            periodSeconds: 1
            failureThreshold: 600
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            periodSeconds: 10
            failureThreshold: 3
          resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
              ephemeral-storage: "1Gi"
            requests:
              cpu: 500m
              memory: 1700Mi
              ephemeral-storage: "200Mi"
