apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: default
  source:
    chart: openebs
    repoURL: https://openebs.github.io/openebs
    targetRevision: 4.3.0
    helm:
      values: |
        openebsNDM:
          enabled: false
        webhook:
          enabled: false
        engines:
          replicated:
            mayastor:
              enabled: false

        localpv-provisioner:
          enabled: true
          openebsNDM:
            enabled: false
          hostpathClass:
            enabled: true
            name: "openebs-hostpath"
            isDefaultClass: true
            reclaimPolicy: "Delete"
            volumeBindingMode: "Immediate"  
            basePath: "/var/openebs/local"
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
