apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seafiles
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alex-bartleynees/portfolio-cluster.git
    targetRevision: HEAD
    path: components/seafiles
  destination:
    server: https://kubernetes.default.svc
    namespace: files
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
