apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-site
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/alex-bartleynees/portfolio.git
      path: deployment/helm-charts/portfolio-site
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
    - repoURL: registry-1.docker.io/creativefree
      targetRevision: 0.4.0
      chart: my-ingress-chart
      helm:
        valueFiles:
          - $values/components/ingress/portfolio-site-ingress-values.yaml
    - repoURL: "https://github.com/alex-bartleynees/portfolio-cluster.git"
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-site
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
